### ISSUE TITLE
Hubs configuration - Allow config of specified labels of the hub home page and project about page to be customised

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1004]
Some hub implementations require to change the labels or text for some elements in public facing pages to be more in accordance with a particular hub nomenclature.

If no custom label has been entered for an element then it should default to display the default text (what currently displays). 

**Hub project finder page**
- [x]  ‘Showing X of Y projects’

**Project About page**
- [x] Change the ‘About the project’ 
- [x] Change the ‘Aim’ 
- [x] Change the ‘Description’ 
- [x] Change the ‘Project information’ 
- [x] Change the ‘Program name’
- [x] Change the ‘Subprogram name’ 
- [x] Over the map, change ‘Project Area’

**Comment by javier-molina** [comment]
Testing OK
