### ISSUE TITLE
UI consistency

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#101]
* Ensure all Delete button look the same
* Check other buttons and basic screen layouts for consistency
* Ensure all clickable links are styled correctly (mouse pointer changes, underline on hover, etc) - e.g. the Project link in breadcrumb is not right.

(covers item 29)

**Comment by temi** [comment]
there are a couple more commits before this. It is there in branch 101.

**Comment by temi** [comment]
i have done a manual merge unfortunately. Hence cannot issue a PR.
