### ISSUE TITLE
Additional Hub config options - Allow config of specified elements of the hub home page, project about page and project survey page to be optionally displayed

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1010]
Some hub implementations do not require the display of the following page elements and independently configurable options to not display them needs to be provided at the hub level, applicable for all projects and programs associated with a particular hub. Default is to display.

**Hub project finder page**
- [x]  "getting started" and "What's this" buttons. 
- [x] Project status indicator (list and grid views independently)
- [x] Project tags (list view)
- [x] Project logo image placeholder (list and grid views independently)

**Project Page**
- [x] Blog tab
- [x] Project status 

**Project About page**
- [x] Project originally registered in
- [x] This project is contributing data to the Atlas of Living Australia.
- [x] You can participate in this project in
- [x] UN Regions
- [x] Countries
- [x] Science types
- [ ] ~~Allow displayed labels to be customised for **Program name** and **Sub-program name** attributes~~ (Covered in #1004)

**Project survey list page**
 - [x] Download XLSX template

**Comment by javier-molina** [comment]
Hide project status indicator on project finder.

There should be two separate entries:
Hide project status indicator on project finder (list view)
Hide project status indicator on project finder (grid view)

**Comment by javier-molina** [comment]
Looks like  'You can participate in this project in' and 'Countries' are working in an AND pattern, we should keep only the former.

**Comment by temi** [comment]
Good catch. I am also adding for project image placeholder.

**Comment by temi** [comment]
@pbrenton When you say 'countries' and 'science types', are you referring to project's edit page?

**Comment by javier-molina** [comment]
@pbrenton  
One more question from image above re: Project status, I'm of the idea of removing the "Project status label as it is very far from the actual content to make it meaningful. 

This would be more consistent with the list view where only the actual status (Project ongoing, etc) is displayed and not the label. Would you agree with that or do you have another preference for that "Project status" label?

**Comment by pbrenton** [comment]
Hi Javier,

Status at the project level is important for citizen science projects and also works projects and therefore must not be removed from the templates. However, the Hub config option top not display in a given hub context will still allow for projects which appear in other hubs as well to still display correctly with status in those other hubs.

In terms of whether the label is displayed or not, your point is fair, the status value can display and still be interpreted adequately without needing the label to display as well. Let’s discuss on Monday.

Cheers

Peter

**Comment by pbrenton** [comment]
Hi Temi,
Yes, that would be right.
