### ISSUE TITLE
Add more hub styling configuration options and elements

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1011]
- [x] Separate class definitions for the "getting started"/"What's this" buttons and the project survey list page "Add record"/"View records" buttons and allow independent background, border and text styling.
- [ ] Separate body background styling of hub pages and survey/activity pages and allow them to be independently styled.
- [x] Add border-color. border-radius and border-width options to all button styling options.
- [x] Add support for "transparent" on buttons and pages.
- [ ] Add font-family and font-size options for all text styling settings.
- [x] Extend footer styling options to support "fat-footer" element layouts, including logo and background image support.
- [x] Add more components to the styling options, including: tags, 
- [x] Add option to select the default base map display for the project extent map on project "About" pages.
- [x] Add an styling option for orange bar in image below
![screen shot 2019-03-07 at 5 15 03 pm](https://user-images.githubusercontent.com/8326394/53936163-0b2e5480-40fd-11e9-93bf-c4594f2457bb.png)

Change layout of hub styling config page to be more intuitive, with page components laid out logically and styling elements clustered with each associated component,  as well as a graphic displaying the setting.

**Comment by javier-molina** [comment]
@pbrenton  I have a few questions for this ticket, would you mind clarifying those when you have a chance?

> [] Separate body background styling of hub pages and survey/activity pages and allow them to be independently styled.

1. Do hub pages include PF, project page including its tabs (About, Blog, Surveys and so on?) and sites
2. Do survey and activity pages include only: All records, View, Create/Edit? 

3. What does "separate body background styling" and "independently styled" mean? 
Does it mean that for the current settings below (plus new settings) will be now applied separate for 1. and 2. (Do we want separate footer and header definitions for 1. and 2?)

![Screen Shot 2019-03-18 at 10 39 00 am](https://user-images.githubusercontent.com/8326394/54499849-88ae5c00-496a-11e9-9501-b1e1cab912b1.png)

> [] Add font-family and font-size options for all text styling settings. 

Font-family could be very browser/platform dependant so we need to be careful  with this setting.

> [] Extend footer styling options to support "fat-footer" element layouts, including logo and background image support.

I take it we need to be able to specify whether the logo is aligned left or right, any other setting you see makes sense?

**Comment by javier-molina** [comment]
Test Ok
