### ISSUE TITLE
Survey Models > Update models to handle records

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#103]
Update the JSON form templates to include the ```record: true``` option and any ```dwcAttribute: ...``` mappings necessary to create occurrence Records.

**Comment by pbrenton** [comment]
Mark to spend some time with Peter completing the mapping for header and sites attributes.

**Comment by m-r-c** [comment]
Header and site attributes have been mapped (#104).

We need to move the ```record: true``` field up to the top level (same level as ```dataModel``` and ```modelName```) in the output models because I put it in the wrong place the first time.

**Comment by m-r-c** [comment]
This has been done now.
