### ISSUE TITLE
Sightings - add Edit button to record view for record owner/admin

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#1033]
We are now getting links back from biocache to biocollect. E.g. one of my records:

https://biocollect.ala.org.au/sightings/bioActivity/index/d07b03f0-c0e0-43ef-9003-df2614e66864

A missing feature on this page is an edit button. If I want to edit my record, its very hard to do!

The **user story** is:

As an ALA sighting submitter, I need to be able to easily edit my records (usually when the record is flagged in biocache), so that I can correct the record.

**Action:** Add a prominent "Edit" button on this page, visible to the record owner and anyone with ROLE_ADMIN (or equivalent), which then goes to the edit screen for that record.

**Comment by nickdos** [comment]
Please close the associated FreshDesk ticket, when this issue has been resolved and deployed to production.  https://support.ehelp.edu.au/helpdesk/tickets/16563.

**Comment by temi** [comment]
@nickdos this feature has been implemented. Can you please close the ticket? I do not have access to FreshDesk. Thanks!

**Comment by temi** [comment]
@nickdos I removed this change since release accidentally had some development stuff in it. I will keep you posted when I deploy it later.

**Comment by temi** [comment]
@nickdos This is now fixed and live on production site.

**Comment by nickdos** [comment]
Thanks Temi - perfect!
