### ISSUE TITLE
Survey Models > fix missing darwin core fields.

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#104]
Verify that the record conversion code in Ecodata covers all darwin core attributes.

**Comment by pbrenton** [comment]
Issues for consideration:
1) If a form does not contain any fields which map to essential DwC attributes such as individualCount, how will these be treated in creation of a record? Should assume a value of 1 in this circumstance.
2) Header attributes need to be mapped separately to form output attributes. Check the model to ensure this is done.
3)

**Comment by pbrenton** [comment]
Mapping of admin editable JSON in activity outputs completed, but now need to check and update for items 2) and 3) above - over to developers!!

**Comment by pbrenton** [comment]
associated with issue #103

**Comment by m-r-c** [comment]
Ecodata pull request: https://github.com/AtlasOfLivingAustralia/ecodata/pull/148

There were no biocollect changes for this task.

**Comment by sat01a** [comment]
Looks like single sightings model in github not sync with test server. 
Changes to dataModel completed? If so, can we update github?

**Comment by sat01a** [comment]
Updated ecodata dataModel > https://github.com/AtlasOfLivingAustralia/ecodata/commit/238ad874a5fde418f527d9628485d6ce51304582
