### ISSUE TITLE
New Ecodata Production Server

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1052]
Decommision BDRS ACT water watch and notify clients.
Export data from BDRS.
Use ACT scripts and migrate form 1 data
Use ACT scripts and migrate form 1 data
Use ACT scripts and migrate form 3 data
Testing & Review

**Comment by matilda2812** [comment]
@sat01a can I close this?

**Comment by sat01a** [comment]
Resolved
