### ISSUE TITLE
Production environment setup

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#106]
* AWS Server config
* New Production Ansible inventory
* Potential changes to ansible scripts for AWS config (not sure if this is required)
* Migrate form config & data from biocollect-test

The decision was made to use the same Ecodata instance that Merit uses.

**Comment by sat01a** [comment]
Spec:
RAM: 8 GB
CPU: 2 Cores (Category >> AWS General Purpose - Current Generation)
Storage: 200GB (Assuming we can dynamically allocate when needed.)

1. AWS instance created. 
2. DNS entry (biocollect.ala.org.au) pointing to new aws instance.
