### ISSUE TITLE
RARC - Vegetation Cover Calculation

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1101]

**Comment by sat01a** [comment]
Testing 1:
https://biocollect.ala.org.au/actwaterwatch/bioActivity/index/ec669c7b-b9f5-4e7d-aa95-4a8e6f524c3e
http://umwaterwatch.ala.org.au/bdrs-core/umww/bdrs/user/tracker.htm?surveyId=337&recordId=299820

Testing 2:
http://umwaterwatch.ala.org.au/bdrs-core/umww/bdrs/user/tracker.htm?surveyId=337&recordId=299414
https://biocollect.ala.org.au/actwaterwatch/bioActivity/index/b3feb9e4-3cd1-43b9-89a1-4d6c639379cb

Testing 3:
http://umwaterwatch.ala.org.au/bdrs-core/umww/bdrs/user/tracker.htm?surveyId=337&recordId=299415
https://biocollect.ala.org.au/actwaterwatch/bioActivity/index/cc9fe203-ddd4-415c-8213-7806ef796257

Testing 4:
http://umwaterwatch.ala.org.au/bdrs-core/umww/bdrs/user/tracker.htm?surveyId=337&recordId=299820#
https://biocollect.ala.org.au/actwaterwatch/bioActivity/index/204f244e-07c6-49df-812e-37d818747a3f

Testing 5:
http://umwaterwatch.ala.org.au/bdrs-core/umww/bdrs/user/tracker.htm?surveyId=337&recordId=299430
https://biocollect.ala.org.au/actwaterwatch/bioActivity/index/5830a7ff-8a1d-46fe-a858-e0202a076403

**Comment by pbrenton** [comment]
Hi Sathish,

Thanks for this. Great work. Just a couple of things to check:
Testing 2: Transect data for large tussock native grasses is missing in BioCollect. Has not affected calculated results in this case, but those values should have copied over.

Also, padding between component labels and component scores in read mode needs to be increased as there is not enough separation.

In general though it seems to be calculating correctly and I think it is good to go for full load on the basis of what I’ve seen.

Thanks again,

Peter

**Comment by sat01a** [comment]
* Padding issue resolved.
* Transect data for large tussock native grasses matched with BDRS
