### ISSUE TITLE
APIs for bioCollect

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#112]
Based on BDRS experience and bioCollect pre-release requests, it is clear that many clients want to be able to develop bespoke/custom mobile apps which can interact directly with their projects and surveys in bioCollect as well as allow for offline use of a mobile app. We therefore need to provide APIs to support all anticipated GET and POST requirements. These include:
GET user permissions
GET projects for specific user
GET projects by id
GET project
GET surveys/activities for a given project id, including respective survey constraints
POST user registration request
POST user login request

More requirements to come - PB

**Comment by djtfmartin** [comment]
Would these be APIs in ecodata rather biocollect? I assume so...

**Comment by pbrenton** [comment]
Yes, good point Dave, thanks for picking that up.

**Comment by sat01a** [comment]
>> /ecodata/permissions/getByProject/f33e85f3-d791-4402-a354-89e7a5c7c97a
>> /ecodata/permissions/getByOrganisation/f33e85f3-d791-4402-a354-89e7a5c7c97a
>> /ecodata/organisation/search
>> /ecodata/organisation/list
>> /ecodata/project/eSearch
>> /ecodata/project/all
>> /ecodata/projectActivity/list/f33e85f3-d791-4402-a354-89e7a5c7c97a
>> /ecodata/activity/all/6800653e-7d92-4517-bdff-b485c64d4580

**Comment by chrisala** [comment]
The change appears to have blocked access to the ecodata activity documentation page: http://ecodata-test.ala.org.au/documentation

**Comment by sat01a** [comment]
Unblocked /documentation/* Bug #427
