### ISSUE TITLE
View Site - works project

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/biocollect#1128]
View sites (sites tab) in works project now zooms out to multiple world view (default) rather than in to extent of all project sites (ie. Extent of outermost cords for all sites in the project) – looks like a default zoom level thing. https://biocollect-test.ala.org.au/works-test/project/index/265419c6-732b-439d-aed7-3946f9ce753d

**Comment by patkyn** [comment]
View sites(sites tab) will use the site setting Default zoom Area (Admin tab -> Sites) as default zoom area

**Comment by pbrenton** [comment]
Great, thanks Patricia. What do you expect timing of prod deploy to be?
