### ISSUE TITLE
BioCollect Grails3 upgrade issues

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1158]
1. If you go to the activities tab and click on one it's giving an error . - **FIXED**
https://biocollect-dev.ala.org.au/ehp-qld/project/index/c95d6c5c-d02d-4c12-917d-47822f085797 

2. Filter panel is also not working - selects OK, but no change in result set  - **CANNOT reproduce**

3. Editing records throws an error. Example: https://biocollect-dev.ala.org.au/ala/bioActivity/edit/b40763cc-6a01-4bd8-982e-e9bce984fa58?returnTo=%2Fala%2FbioActivity%2FallRecords .   **-Fixed**

4. Deleting record from DATA view tab is broken. - **NOT Grails3/ Bug in Biocollect-test as well** 

5. Creating "New Project" > Cannot select "Program name" (https://biocollect-dev.ala.org.au/project/create?citizenScience=true&hub=ala) - **May be related to configuration.**

6. Dropping a pin in the MAP shows 500 error. (Refer attachment > https://biocollect-dev.ala.org.au/ala/bioActivity/create/ebf3062e-44fd-4df5-a6f6-cb66d584ce85 **- Fixed**

7. Species list dropdown seems to be broken. (https://biocollect-dev.ala.org.au/ala/bioActivity/create/ebf3062e-44fd-4df5-a6f6-cb66d584ce85) . **-Fixed**

8.  Project Resources (https://biocollect-dev.ala.org.au/ala/project/index/561a015b-9c45-426e-9d42-b17f39c8165e)
 A. Existing. Name Attribution Type dropdon does not align with text box
 B. Background of download button is the same as the foreground when resource is selected.
![Screen Shot 2019-06-28 at 11 33 15 am](https://user-images.githubusercontent.com/8326394/60311421-7cd72a80-999a-11e9-8540-6020926a58a2.png)

9. Project Resources (https://biocollect-dev.ala.org.au/ala/project/index/561a015b-9c45-426e-9d42-b17f39c8165e)
  A. Scrollbars are shown regardless of image size (works fine in production)
  B. Existing. Image is not centered in the containing panel.
![Screen Shot 2019-06-28 at 11 35 01 am](https://user-images.githubusercontent.com/8326394/60311517-ebb48380-999a-11e9-8d77-94b1ceb07dc3.png)

10. Create project (https://biocollect-dev.ala.org.au/project/create?citizenScience=true&hub=ala)
When accepting terms of use the new page opens with the error:

```
An error occurred
Error 500: Internal Server Error
URI
/project/true
Class
java.lang.NoSuchMethodException
Message
au.org.ala.biocollect.merit.ProjectController.true()
Trace
    Line | Method
->> 1786 | getMethod         in java.lang.Class
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     33 | before            in au.org.ala.biocollect.AclFilterInterceptor
|     77 | preHandle . . . . in org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter
|    133 | applyPreHandle    in org.springframework.web.servlet.HandlerExecutionChain
|    962 | doDispatch . . .  in org.springframework.web.servlet.DispatcherServlet
|    901 | doService         in     ''
|    970 | processRequest .  in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet             in     ''
|    846 | service . . . . . in     ''
|     77 | doFilterInternal  in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|    123 | doFilter . . . .  in org.springframework.boot.web.support.ErrorPageFilter
|    164 | handleErrorStatus in     ''
|    132 | doFilter . . . .  in     ''
|     66 | access$000        in     ''
|    105 | doFilterInternal  in org.springframework.boot.web.support.ErrorPageFilter$1
|    123 | doFilter          in org.springframework.boot.web.support.ErrorPageFilter
|   1149 | runWorker . . . . in java.util.concurrent.ThreadPoolExecutor
|    624 | run               in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run . . . . . . . in java.lang.Thread
 

```

The url opened is: https://biocollect-dev.ala.org.au/project/true

11. Create Project (https://biocollect-dev.ala.org.au/project/create?citizenScience=true&hub=ala)
If you try to change the organisation (What is the name of the organisation running this project? )the search will be empty no matter what you type and you won't be able to create a project.

12. Create project - Website
Not related to the migration but probably we should encourage the use of HTTPS rather than http when adding urls.

13. Create project - Mobile apps
Not related to the migration but is blackberry still used?
iTunes should be changed by iOs

14. Create project - Add graphics to personalise your project pages
Attaching a project logo or graphic does nothing.

15. Create Project - No tab is selected
Most likely not related to migration.
**Steps**
After creating a project the page  "Congratulations! - You've set up your project, now let's create your surveys" is displayed.
After clicking Continue:
**Expected**
Admin tab should be selected
**Actual**
 No tab is selected, hence no content is displayed for the project until a tab is clicked
![Screen Shot 2019-07-01 at 2 11 03 pm](https://user-images.githubusercontent.com/8326394/60410127-17897080-9c0a-11e9-9e5a-ec4b523c60d4.png)

16. Project Admin -> Edit Blog -> New Entry
Image attachment does nothing just as in 14.

17. Project Admin -> Resources -> Attach a document
I add all metadata, click on + Attach file and there will be a Progress label with a pogressbar appearing but the Save button will never be activated effectively preventing me from attaching a file.
Not crucial but it would be great if the selected control blue border (and progress bar) be styled orange as per ALA colours.
![Screen Shot 2019-07-01 at 4 19 38 pm](https://user-images.githubusercontent.com/8326394/60414725-5f18f800-9c1c-11e9-8cf1-de01f44965c9.png)

18. Project Admin ->  Survey Settings
Clicking Next in Survey Info tab scrolls content to the bottom of the screen
Most likely not related to migration.

For a saved Survey I click next in the Survey Info tab.
The tab changes accordingly to Visibility tab however the screen is scrolled to the footer of the page.

![Screen Shot 2019-07-09 at 3 53 10 pm](https://user-images.githubusercontent.com/8326394/60862760-fce67580-a261-11e9-98bd-fc7369c9580a.png)

![Screen Shot 2019-07-09 at 3 52 42 pm](https://user-images.githubusercontent.com/8326394/60862772-040d8380-a262-11e9-8ffc-f485801415ac.png)

19. Missing meta tags in html header

```
<meta name="app.version" content=""/>
<meta name="app.build" content=""/>

```

20. Project Admin ->  Survey Settings -> Alert
It is not possible to select a species from the dropdown, it happens in biocollect-test too. The actual text in the textbox is saved though. (TBC that notifications are actually sent).

![Screen Shot 2019-07-10 at 5 06 05 pm](https://user-images.githubusercontent.com/8326394/60949593-dcd5b580-a338-11e9-9115-8a46934a3b95.png)

21. Project Admin ->  Survey Settings -> Species -> Configure/View 
Unable to create a new species list

![Screen Shot 2019-07-10 at 5 53 45 pm](https://user-images.githubusercontent.com/8326394/60951157-e1e83400-a33b-11e9-9c2a-730a9a7677a9.png)

22. Project Admin ->  Survey Settings -> Species -> Configure/View 
No lists found when trying to select/search an existing species list

![Screen Shot 2019-07-10 at 5 56 55 pm](https://user-images.githubusercontent.com/8326394/60951309-312e6480-a33c-11e9-9208-5b428dbf9eb8.png)

23.  Project Admin ->  Survey Settings -> Locations
Not related to Grails3 migration

'Allow additional survey sites' and 'ONLY Select from existing sites' should use radio buttons instead of checkboxes as the semantic is that of the former.

![Screen Shot 2019-07-10 at 6 01 17 pm](https://user-images.githubusercontent.com/8326394/60951651-ef51ee00-a33c-11e9-8db8-e2023086b26c.png)

23.  Project Admin ->  Survey Settings -> Publish

Clicking Publish shows the message "Successfully published, reloading page now" however after that the project Surveys tab remains empty.
Going back to Project Admin ->  Survey Settings the survey has status Unpublished and the Species settings have been lost, it defaults again to All species for every Field.

24. Admin -> Audit Load Project audit records
Using the search filters does nothing, all the entries are still shown regardless of the search entered

![Screen Shot 2019-07-15 at 10 10 30 am](https://user-images.githubusercontent.com/8326394/61191095-888c5600-a6e9-11e9-89cf-233799cb1342.png)

25. Admin -> Static pages

back to Static pages link is incorrectly linking to: 
http://localhost:8087/biocollect/ala/admin/staticPages 

This happens for both View and Edit actions.

Saving a page preserves changes but it also redirects to localhost after clicking Save when editing.

26. Admin -> Tools
"Reload External Config" button does not provide any feedback when clicked to know that it was actually actioned

Same for "Re-index all" button.
Same for "Import SciStarter Projects" button.

27. Admin -> Tools

Sync collectory orgs only displays a popup with the message: "Unauthorized"

28. Admin -> Manage Hubs -> Edit ala hub -> Banner

Attach Banner image does not attach an image after a file has been selected.

29. Admin -> Manage Hubs -> Edit ala hub -> Banner

Attach Organisation logo is not saved even after file has been selected and preview shown on screen. 
Clicking on Save take the user back to Programs tab.

30. Home ->  Project -> Individual sighting
 https://biocollect-dev.ala.org.au/ala/bioActivity/index/723c52d2-9637-4cf8-8008-0e9cb331231f?version=

Images location are being sourced from localhost:8087

![Screen Shot 2019-07-15 at 2 14 58 pm](https://user-images.githubusercontent.com/8326394/61195464-82a76c80-a70b-11e9-9591-1770448c4cf1.png)

31. Home -> Organisations -> New Organisation
https://biocollect-dev.ala.org.au/ala/organisation/create
Organisation Logo and Feature graphic are not saved. 
They were correctly shown in the create page but they have gone when editing the organisation.

https://biocollect-dev.ala.org.au/ala/organisation/edit/82aa58a5-acf0-4a34-b87f-07f845c179e1

32. My Account -> My organisations
https://biocollect-dev.ala.org.au/ala/organisation/myOrganisations
Unable to search organisations
I entered terms for the organisation I created in the textbox and no results are found.

Test organisation is "20190715 1509 Javier Test Organisation" https://biocollect-dev.ala.org.au/ala/organisation/index/82aa58a5-acf0-4a34-b87f-07f845c179e1#organisationName%3D20190715%201509%20Javier%20Test%20Organisation%26skipDefaultFilters%3Dtrue%26max%3D20%26sort%3DdateCreatedSort 

I tried: "20190715", "Javier", "Test","Organisation" but nothing comes up

33.  Record a sighting
Error when attaching image
https://biocollect-dev.ala.org.au/ala/bioActivity/create/73276d6b-5456-4918-96fc-19bad956db9e

Adding Image produces Internal Server Error

![Screen Shot 2019-07-15 at 3 49 20 pm](https://user-images.githubusercontent.com/8326394/61198004-146aa600-a71b-11e9-911f-27e0da04e1e6.png)

34.  Record a sighting
Circle tool does not allow dnd to create a circle shape, it behaves like a point in the sense that only clicking in the map and dropping a point is possible.

![Screen Shot 2019-07-15 at 3 48 28 pm](https://user-images.githubusercontent.com/8326394/61198034-4aa82580-a71b-11e9-82d3-9689f963cc3b.png)

35. Create works project 
Project creation fails after accepting the page after project creation (workflow page for CS projects)

https://biocollect-dev.ala.org.au/works-test/project/index/e96d1e18-66b3-4814-9bd3-5dd7ddda7cbd

The error displayed is:

```
An error occurred
Error 500: Internal Server Error
URI
/works-test/project/index/e96d1e18-66b3-4814-9bd3-5dd7ddda7cbd
Class
java.lang.IllegalArgumentException
Message
No program exists with name null
Trace
    Line | Method
->>  333 | getProgramConfiguration in au.org.ala.biocollect.merit.MetadataService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    326 | isOptionalContent       in     ''
|    234 | worksProjectContent . . in au.org.ala.biocollect.merit.ProjectController
|    165 | projectContent          in     ''
|     93 | index . . . . . . . . . in     ''
|    223 | invoke                  in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke . . . . . . . .  in org.grails.core.DefaultGrailsControllerClass
|     90 | handle                  in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch . . . . . .  in org.springframework.web.servlet.DispatcherServlet
|    901 | doService               in     ''
|    970 | processRequest . . . .  in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet                   in     ''
|    846 | service . . . . . . . . in     ''
|     55 | doFilterInternal        in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|     77 | doFilterInternal . . .  in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|     81 | doFilter                in au.org.ala.cas.client.AlaHttpServletRequestWrapperFilter
|    196 | doFilter . . . . . . .  in au.org.ala.cas.client.UriFilter
|    236 | doFilter                in org.jasig.cas.client.validation.AbstractTicketValidationFilter
|    196 | doFilter . . . . . . .  in au.org.ala.cas.client.UriFilter
|    155 | doFilter                in org.jasig.cas.client.authentication.AuthenticationFilter
|    196 | doFilter . . . . . . .  in au.org.ala.cas.client.UriFilter
|     97 | doFilter                in org.jasig.cas.client.session.SingleSignOutFilter
|     67 | doFilterInternal . . .  in org.grails.web.filters.HiddenHttpMethodFilter
|    130 | doFilter                in org.springframework.boot.web.support.ErrorPageFilter
|     66 | access$000 . . . . . .  in     ''
|    105 | doFilterInternal        in org.springframework.boot.web.support.ErrorPageFilter$1
|    123 | doFilter . . . . . . .  in org.springframework.boot.web.support.ErrorPageFilter
|   1149 | runWorker               in java.util.concurrent.ThreadPoolExecutor
|    624 | run . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run                     in java.lang.Thread

```

![Screen Shot 2019-07-15 at 4 28 57 pm](https://user-images.githubusercontent.com/8326394/61198727-9ad4b700-a71e-11e9-993e-aa718a314a16.png)

Hub is configured appropriately and these is no indication when the project is being created that the program could be missing.

![Screen Shot 2019-07-15 at 4 29 25 pm](https://user-images.githubusercontent.com/8326394/61198732-a32cf200-a71e-11e9-81b8-f56d0e54cfec.png)

![Screen Shot 2019-07-15 at 4 29 35 pm](https://user-images.githubusercontent.com/8326394/61198737-a922d300-a71e-11e9-9964-1657e3e1470f.png)

![Screen Shot 2019-07-15 at 4 27 23 pm](https://user-images.githubusercontent.com/8326394/61198750-b475fe80-a71e-11e9-9320-f42cda863d7e.png)

**Comment by qifeng-bai** [comment]
3: 
 $('.imageList a[rel=gallery]').fancybox  REPORTS ERROR:
$(...).fancybox is not a function

4:
forms-manifest.unminified.js:39933 Uncaught TypeError: a.activityId is not a function
var url = fcConfig.activityDeleteUrl + "/" + activity.activityId(); 

5, because citizenScience=true

6, Again, JSON converter cannot deal with JsonNULL

7, Species list is sometimes not working, suspect it is related to configuration

**Comment by javier-molina** [comment]
@sat01a, @qifeng-bai I added points 8 to 15 noting things that I don't think are not related to the Grails3 upgrade yet I prefer to keep a record of them. 

I continue testing and will let you know when more relevant progress is made.

**Comment by javier-molina** [comment]
@pbrenton, @chrisala, @patkyn 
@sat01a fyi 

I have performed end to end testing to Biocollect grails 3 UI according to https://confluence.csiro.au/display/ALASD/Biocollect+Functional+UI+Testing 

I yet have to finish works projects specific functionality (and add test cases) but I will hold on to that after Item 35. above is addressed.

I will wait for your comments to see how we move this forward. I will move into other activities in the meantime.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-46
