### ISSUE TITLE
Record delete confirmation button in BioCollect survey does not work

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1163]
After clicking the delete button within a biocollect citizen science survey a popup appears asking for confirmation of the deletion. The delete button within the popup does not work. 

Selecting the checkbox next to a record and then clicking the delete button in the bulk actions options does work.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-2
