### ISSUE TITLE
Project finder - Projects per page not working

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1180]
Change projects per page selection, result set does not change

**Comment by patkyn** [comment]
Is this still an issue? It seems to be working fine now

**Comment by matilda2812** [comment]
This works as expected

**Comment by matilda2812** [comment]
Working as expected
![Screen Shot 2020-03-04 at 11 35 55 am](https://user-images.githubusercontent.com/25336120/75833178-552f4080-5e0c-11ea-8e4f-91f87fbe04eb.png)
![Screen Shot 2020-03-04 at 11 35 50 am](https://user-images.githubusercontent.com/25336120/75833182-56f90400-5e0c-11ea-8606-ee8618c2b7a8.png)
![Screen Shot 2020-03-04 at 11 35 44 am](https://user-images.githubusercontent.com/25336120/75833183-58c2c780-5e0c-11ea-9f16-03471812225f.png)
