### ISSUE TITLE
Project finder - sort by not working

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1181]
Change sort by selection, result set does not change

**Comment by patkyn** [comment]
It seems to be working fine now. 

![image](https://user-images.githubusercontent.com/1606595/67832655-74ecea00-fb36-11e9-8e9d-eb96bd24d062.png)

![image](https://user-images.githubusercontent.com/1606595/67832698-92ba4f00-fb36-11e9-9261-2ea46610dae0.png)

**Comment by matilda2812** [comment]
+1 to this working now
