### ISSUE TITLE
Project finder - Australia/Global toggle not working

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1183]
Toggle between Australia and Global, results don't change

**Comment by patkyn** [comment]
I can't reproduce the issue. The toggle filter Australia/Global is behaving as it should be. 

![image](https://user-images.githubusercontent.com/1606595/67832773-ce551900-fb36-11e9-915d-4e6cfeaf773d.png)

![image](https://user-images.githubusercontent.com/1606595/67832851-03fa0200-fb37-11e9-8dc4-405ce6257df5.png)
