### ISSUE TITLE
Project finder - Pagination is not working

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1184]
Select to move to another page of results, result do not change.

**Comment by patkyn** [comment]
This is working now. 

![image](https://user-images.githubusercontent.com/1606595/67832950-53d8c900-fb37-11e9-8323-a48b6966fc9d.png)

![image](https://user-images.githubusercontent.com/1606595/67832979-736ff180-fb37-11e9-8ee1-7e94ad17bd88.png)

![image](https://user-images.githubusercontent.com/1606595/67832999-82ef3a80-fb37-11e9-8d4c-5388d85f7a95.png)

**Comment by matilda2812** [comment]
+1 to this working now
