### ISSUE TITLE
HTTP 403 responses to image uploads due to lack of apikey

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocollect#1202]
There are a relatively large number of HTTP 403 responses to image uploads since the new image service was implemented on 5 September 2019.

The new image-service relies on apikeys for authentication, where the previous version used some other form of security (or none).

All update calls from biocollect/ecodata through to image-service should have apikeys attached to them to be successful.

The calls triggering the issue are mostly `/ws/uploadImage`, but some of them are `/ws/updateMetadata/null`.

https://github.com/AtlasOfLivingAustralia/biocollect/blob/dfe294b12e58b8e24ec1b271c7e643faab251653/grails-app/controllers/au/org/ala/biocollect/merit/ImageController.groovy#L106

**Comment by ansell** [comment]
This issue also occurs in ecodata at:

https://github.com/AtlasOfLivingAustralia/ecodata/blob/32b27f4321a32e3063b2643798f5c2552d159469/grails-app/services/au/org/ala/ecodata/RecordService.groovy#L597

**Comment by djtfmartin** [comment]
This was tested and working since the first release of the new image-service because the image-service support whitelisting of IP addresses and this was used to make the changes backwards compatible.

**Comment by djtfmartin** [comment]
Sorry if I seemed to close this in haste believing the premise bug is incorrect I believe. 
The image-service uses 2 forms of authentication:

1) IP whitelisting 
2) API keys

Biocollect and other apps should have been whitelisted for the production deployments.

**Comment by djtfmartin** [comment]
I have now added ecodata to the whitelisted IPs. This should resolve it.

**Comment by djtfmartin** [comment]
I believe this is fixed. Ive tested by updating my own images in production. Log outputs

```
150.229.0.22 - - [01/Oct/2019:21:45:28 +1000] "POST /ws/uploadImage HTTP/1.1" 200 98 "-" "Apache-HttpClient/4.2.1 (java 1.5)" "-" request_time=0.827 upstream_response_time=0.820 upstream_connect_time=0.000 upstream_header_time=0.820 upstream_cache_status=-
150.229.0.22 - - [01/Oct/2019:21:45:29 +1000] "POST /ws/uploadImage HTTP/1.1" 200 98 "-" "Apache-HttpClient/4.2.1 (java 1.5)" "-" request_time=0.828 upstream_response_time=0.820 upstream_connect_time=0.000 upstream_header_time=0.820 upstream_cache_status=-
``

Updated images 

https://images.ala.org.au/image/5a62b951-4d1e-4b2f-ae07-157c6e15af5a

**Comment by ansell** [comment]
@sat01a Have apikeys been implemented for these image uploads?
