### ISSUE TITLE
Project finder page - search bar not working properly

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1208]
Enter "Karawatha" into search bar (should only be one project), returns zero results, but indicates 201 of 1 project.
Same thing happens if entering another search after a successful search.

**Comment by patkyn** [comment]
This is an existing bug. After doing a successful search and scrolling to another page, if we do another search which returns only 1 result, pagination doesn't go to the first page. I can reproduce this in biocollect-test too.
