### ISSUE TITLE
Resources page - Created a new test resource, but would not display in player

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1211]
Created new test resource doc at https://biocollect-dev.ala.org.au/ala/project/index/85f89533-ed16-4398-aa79-5368909329ce.
Select test doc to view.
Does not display in the document player window.

**Comment by patkyn** [comment]
This is an existing behaviour. Clicking on the doc link triggers a download of the doc. Although the downloaded file should have the same extension.

![image](https://user-images.githubusercontent.com/1606595/68093798-872ba700-feed-11e9-8ba8-4a317f333029.png)

**Comment by temi** [comment]
It appears that `Access-Control-Allow-Origin` header is missing on ecodata-test and ecodata-dev for requests from biocollect-dev and biocollect-test.
