### ISSUE TITLE
Project finder - Faceted filtering (multiple facet selections) not working correctly

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1214]
Selecting multiple facets is returning unexpected results.

1. Select one facet (eg. "Agricultural & veterinary science"): returns 4 results as expected.
2. Select another facet (eg. "Biology" indicates only 1 additional project): returns a total of 32 projects, but expected a total of 5 projects.

Deselect "Agricultural & veterinary science": return 29 projects.

It appears that the join between facets is set at OR instead of AND.

**Comment by patkyn** [comment]
This issue is present in grails 2 code as well

**Comment by patkyn** [comment]
After some discussion about the confusing behaviour of facet filtering. it was agreed to just keep it simple by having just AND condition
