### ISSUE TITLE
Project finder - geographic filter for "near me" (current GPS location) is not working

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1215]
Select to filter by geographic "my location"
Map should centre on current GPS location and zoom to appropriate zoom level.

Nothing happening and spinner is in endless loop

**Comment by matilda2812** [comment]
This error only occurs if location services are disabled in the browser, otherwise it works as intended.

**Comment by patkyn** [comment]
It works for me too
