### ISSUE TITLE
Create new survey - Save permitted without all mandatory fields filled

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1219]
Create new survey
Enter survey name and description, then click off elsewhere on the page

Automatic save and create occurs, despite not having completed mandatory fields and validation immediately triggers on all other mandatory fields.
This behaviour is unexpected and, whilst not necessarily bad, it is not intuitive, nor is it consistent with save functions elsewhere.

Should apply mandatory requirements and save functions consistently across the site. Change this page to conform to others.

**Comment by matilda2812** [comment]
This is also an issue in grails2

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-13
