### ISSUE TITLE
Survey logo image is not being retained

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1221]
Saving the survey logo image appears to work, and it does display immediately. But, refreshing the page appears to lose the image association with the survey. ie. the image does not subsequently display on either the survey metadata config or survey list pages.

**Comment by patkyn** [comment]
This is resolved now with https://github.com/AtlasOfLivingAustralia/ecodata/commit/e1fe0d6d7bb41105f143b028ffb529c8de9d0611

**Comment by matilda2812** [comment]
Closing as fixed
