### ISSUE TITLE
Audit log - contributor details not correctly attributing to logged in used

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1222]
See log record https://biocollect-dev.ala.org.au/project/auditMessageDetails?projectId=64c4d0a3-e398-4250-8021-63af591dad68&hub=ala&id=5db7b82ba6770e0309a940a5&searchTerm=

I was logged in as myself, but edit is attributed to Anon

**Comment by matilda2812** [comment]
Closing as fixed
