### ISSUE TITLE
Works project type - Risks/threats and issues not displayed

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1224]
The Risks/threats and issues are being recorded in Admin page, but are not displayed on the view page.

**Comment by patkyn** [comment]
This is fixed after the Program models json files are copied into ecodata-dev /data/ecodata/models and ecodata service is restarted. 

The Risk and Threats checkbox must be ticked as displayed below
![image](https://user-images.githubusercontent.com/1606595/72234343-a5fe9600-3620-11ea-9fa0-d19821a9d2ec.png)

**Comment by matilda2812** [comment]
Closing as fixed
