### ISSUE TITLE
Using the "excludeAbsenceRecord" property in a form template breaks download

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#1226]
To reproduce:
1) Navigate to: https://biocollect.ala.org.au/actwaterwatch/project/index/50387daf-eecc-40dc-b1a3-622ee8fa2b85
2) Select the data tab
3) Filter by "Water bug sampling"
4) Press the download button.

Expect:
The download.

Actual:
NPE on line 247 of CSProjectXlsExporter due to an attempt to reference the first row, when all rows have been excluded due to the "excludeAbsenceRecord" setting and the fact none of the rows have an "individualCount" > 0

**Comment by chrisala** [comment]
Needs BA input - I would suggest when performing a download we don't want to exclude absence records as the information would be available to the user to do that themselves if desired.
Possibly it's required for an ALA import?

**Comment by sat01a** [comment]
Actually it turns out to be an existing issue with NPE check. Not related to the excludeAbsenceRecord property.
