### ISSUE TITLE
Going into / shows error

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/biocollect#1228]
Going into https://biocollect-dev.ala.org.au/ should automatically show a default hub projects.

There's was an issue where because / urlmapping was defined in ecodata-client-plugin and also biocollect, the  urlmapping from plugin took precedence. 

This has been resolved after upgrading to Grails 3.3.11 (grails/grails-core#11335)

**Comment by patkyn** [comment]
This was resolved in commit https://github.com/AtlasOfLivingAustralia/biocollect/commit/51543cd09ae5ebc0fce26adc38c8598f9e163d5a

**Comment by matilda2812** [comment]
Closing as fixed
