### ISSUE TITLE
View records button does not filter records by survey

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1230]
Expected behaviour when clicking on 'View records' in the surveys tab is to display a list of all records for the selected survey. 
Actual behaviour: redirects to Data tab with no filters applied

**Comment by matilda2812** [comment]
Same issue created in #972

**Comment by matilda2812** [comment]
If you view records from a survey in one project, and then click 'view records' in another project, the old filters are not cleared. This behaviour might confuse users. See screenshot, with the top filter being from a survey from another project
![Screen Shot 2020-09-08 at 10 40 47 am](https://user-images.githubusercontent.com/25336120/92422213-c71f8280-f1bf-11ea-9f60-917b5bdf8b74.png)

**Comment by sat01a** [comment]
Yes its a known behaviour. Filters are stored in local browser cache. Storing filter key for each project will not scale. In futre we have plans to completely refactor / move away from storing filter keys in browser cache.
