### ISSUE TITLE
Improvements to data resource id creation workflow

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1235]
1. Use BioCollect harvest API to determine the list of active drIds and remove other ones - Data team.

2. Remove default drId création in the project creation workflow. - BioCollect team

3. Include drId creation/deletion work in the harvest flag toggling workflow. - BioCollect team

4. In future if needed open up new API to list deleted drId  - BioCollect team

Action point 1 will handle the most of the current duplication issue. 2,3 & 4 needs to be prioritised in our future BioCollect/Ecodata release

I have created the ticket, please feel free to directly add/remove items in the ticket.

**Comment by temi** [comment]
I guess one more item to do on our database is to clean data resource id for projects with ALA harvest turned off. Not sure if the cleaning needs to be extended to MERIT projects.

**Comment by temi** [comment]
2 & 3 addressed in https://github.com/AtlasOfLivingAustralia/ecodata/issues/567.
4. As per discussion with Mahmoud, data team will remove records of data resources not listed by API but shows up on Collectory under Biocollect data provider.

**Comment by sat01a** [comment]
Collectory integration verified against the following project : https://biocollect-test.ala.org.au/ala/project/index/a9fefa03-a88d-4e08-88bd-9a8509d8f144

By default, no dataResourceId or dataProviderId will be added to the project.

Collectory integration workflow will be trigger when admin toggles Harvest flag under Project > Admin.
For BioCollect hub specific project dataProviderId will be constant -dp3903
Resource id will vary for every project
