### ISSUE TITLE
User profile page is giving errors

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#124]
Right now it is giving me an error when I click on my username - I am not sure if it's the default page from MERIT or not.

**Comment by sat01a** [comment]
User profile page works as expected.

**Comment by chrisala** [comment]
Try (in mongo): db.auditMessage.remove({}) then reload the profile page

**Comment by sat01a** [comment]
Tried the above scenario with admin and non admin accounts. Page opens without throwing an error.

![screen shot 2015-11-04 at 12 25 47 pm](https://cloud.githubusercontent.com/assets/4197871/10926977/06e88414-82f0-11e5-83ea-499e116888c6.png)
![screen shot 2015-11-04 at 12 30 24 pm](https://cloud.githubusercontent.com/assets/4197871/10926978/06eaed9e-82f0-11e5-80a9-d062f6ae71c9.png)

**Comment by sat01a** [comment]
Checked with Chris, all OK closing the issue.

**Comment by sat01a** [comment]
PR https://github.com/AtlasOfLivingAustralia/ecodata/pull/150

**Comment by temi** [comment]
done
