### ISSUE TITLE
Form table upload feature is broken

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1242]

**Comment by sat01a** [comment]
https://support.ehelp.edu.au/a/tickets/46279

**Comment by matilda2812** [comment]
There are multiple parts to this: 
1. The download template button does not work (within survey form)
2. Attempting to upload using the survey form template does not work
3. No helpful error message is provided as to why the upload fails

**Comment by matilda2812** [comment]
Raised again with me by a group as a blocker to using Biocollect

**Comment by magdziarek** [comment]
Same problem here, I get the error:

Cannot play media. No decoders for requested formats: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Comment by temi** [comment]
## steps to reproduce

1. Go to restoration [record in test](https://biocollect-test.ala.org.au/biocollect-all/bioActivity/edit/2f36b38e-754a-4bb1-a9d1-909b8c9a83d7?returnTo=%2Fbiocollect-all%2Fproject%2Findex%2F533d7e9a-5c0b-47d5-a3a2-5d463922b363)
2. download and upload excel sheet

**Comment by pbrenton** [comment]
Tested successful

**Comment by temi** [comment]
Communicated with Peggy.
