### ISSUE TITLE
Species field does not update when form name changed

### ISSUE THREAD

**Issue by matildastevenson** [AtlasOfLivingAustralia/biocollect#1250]
This issue is caused when the form template is changed in a survey configuration.
The species field configuration does not automatically update to the new survey name. 
This results in calls to the species list using the old form name and returning a 500 error. The error means that any species recorded are not linked to ALA species.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-46

**Comment by pbrenton** [comment]
Functional testing completed successfully 13/08/2021

**Comment by yasima-csiro** [comment]
Released with 5.2.1
