### ISSUE TITLE
Fix issues with Map

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1253]
- [x] Map on project about tab showing only on top left corner.
- [x] Zoom to default site not working. Project > Admin > Survey > Location.
- [x] Height of Map on all records, project finder, all sites etc. not sufficient.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-9
https://upsource.ala.org.au/ecodata-client-plugin/review/ECP-CR-25
https://github.com/AtlasOfLivingAustralia/ala-map-plugin/commit/857ef80bab8d598089e34425270db2cdd8c2d0f8

**Comment by sat01a** [comment]
Reviewed
