### ISSUE TITLE
Disable ability to add a user to a project with 'project participant' status

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1259]
The 'project participant' role is assigned to a user when they enter data into a survey where the 'Allow public users to enter data' option is true. 
It is also possible for an admin to add a user to a project as a project participant. However, this role does not allow users to enter data via the mobile app, unless the survey is open to public users. 
Other being unable to add data to the mobile app, there is no difference between the project participant and editor status. 
Therefore, we should remove the ability for an admin to add a user to a project as a project participant.

**Comment by sat01a** [comment]
Fixed.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-22

**Comment by matilda2812** [comment]
It is still possible to change an existing user to project participant status- I think this should also be disabled for consistency
![Screen Shot 2020-09-08 at 10 35 56 am](https://user-images.githubusercontent.com/25336120/92422082-1e712300-f1bf-11ea-9d1f-3f8998f95361.png)

**Comment by pbrenton** [comment]
I agree with @matilda2812 , please also remove ability to change the role of an existing member to "project participant".

**Comment by sat01a** [comment]
Just capturing for future reference - Its been agreed to have this option.  Having this option allows admin to change user from project participant to “editor” or “admin”. Specially for sightings users will be listed as "project participants". Removing this option comes with few edge cases.
