### ISSUE TITLE
Filter MERIT projects out from "My Projects" list

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#126]
While we are only supporting Citizen Science projects for the first release, it's probably easiest to only return citizen science projects here.

**Comment by pbrenton** [comment]
Note that we will need to reinstate MERIT projects into the "My projects" and "Organisation projects" listings when we are supporting works type projects, though there is no operational reason why we can't support this sooner.

MERIT projects will be treated like "external" projects in terms of navigational behaviour. Icon image for all MERIT projects should default to the attached.

![merit placeholder image](https://cloud.githubusercontent.com/assets/8119351/11578092/7d1a1ce0-9a76-11e5-9419-29debc7834fb.jpg)

**Comment by pbrenton** [comment]
Changed title of this ticket to now include MERIT projects in the "My projects" and "Organisation projects" lists using the above placeholder logo image.

Some work required to appropriately render MERIT project metadata in the BioCollect format for the project page.

**Comment by chrisala** [comment]
Duplicate of #388
