### ISSUE TITLE
Terms of Use has invalid link

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1264]
Should link to Biocollect terms of use
![Screen Shot 2020-03-04 at 10 38 11 am](https://user-images.githubusercontent.com/25336120/75830215-4e043480-5e04-11ea-944a-42711f6d7a85.png)

This is an issue for all hubs

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-13

**Comment by sat01a** [comment]
Missing config caused this issue, dev server updated with the correct config
