### ISSUE TITLE
Mobile apps grails 3 issues

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1268]
- BioCollect mobile apps pointing to grails3 returns 152 projects,
- BioCollect web apps pointing to grails3 returns 276 projects,
- Survey/Activity edit functionality is broken
- New Survey Activity functionality workflow needs change.
- App crashes when using simulator to upload Image

**Comment by temi** [comment]
Discrepancy in number is due to different filters used in API calls.
The parameters `fq=isExternal:F` and `isWorldWide=false` are causing the numbers to be different.

Image upload is working.
