### ISSUE TITLE
BioCollect indexing failures

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#1277]
After the reindexing last night, 105 failures were reported for the pasearch index.
Sampling indicates the bulk of the failures are due to the string "null" in the site centre coordinate.

"activity Index: pasearch Error: failed to parse [sites.extent.geometry.centre] "

**Comment by chrisala** [comment]
Type: activity Index: pasearch Error: failed to parse [sites.extent.geometry.centre] Document: { "legalCustodianOrganisationType": "", "daysStatus": "active", "organisationId": "8b8f0070-a02b-4e39-96d0-931fdd3fc5e3", "keywords": "bird,wetland", "projectType": "survey", "formVersion": 1, "sites": [{ "area": "0", "extent": { "geometry": { "fid": "", "datum": "", "areaKmSq": 0, "precision": "", "bbox": "", "lga": "Warringah (A)", "nrm": "Greater Sydney", "locality": "188 Harbord Rd, North Curl Curl NSW 2099, Australia", "coordinates": [ 151.27954959869385, -33.765847083387165 ], "centre": "null", "decimalLongitude": 151.27954959869385, "pid": "", "decimalLatitude": -33.765847083387165, "mvs": "Cleared, non-native vegetation, buildings", "type": "Point", "uncertainty": "", "name": "", "state": "New South Wales (including Coastal Waters)", "layerName": "", "mvg": "Cleared, non-native vegetation, buildings" }, "source": "Point" }, "notes": "", "projects": ["67a285a0-c9f4-465d-9cfd-f6ad31225fac"], "description": "", "externalId": "", "type": "monitoringPoint", "geoIndex": { "coordinates": [ 151.27954959869385, -33.765847083387165 ], "type": "Point" }, "lastUpdated": "2018-08-02T04:57:26Z", "dateCreated": "2018-08-02T04:57:26Z", "name": "Site 8: Harbord Road Gross Pollutant Trap ", "siteId": "9346210b-1ab1-48a1-b09e-633e21f7e617", "id": "5b628f36e4b02ca4306d42bb", "isSciStarter": false, "status": "active" }], "type": "Bird Survey - Curl Curl", "plannedEndDate": "2019-03-28T13:00:00Z", "facets": [], "lastUpdated": "2018-08-24T00:46:01Z", "uNRegions": ["Oceania"], "activityId": "48d4d551-dfa5-419b-ab70-2240e08fb9a1", "assessment": false, "promoteOnHomepage": "no", "surveyMonth": "July", "collectoryInstitutionId": "", "dataResourceId": "dr7200", "id": "58c9eef1e4b01f71e1892179", "termsOfUseAccepted": true, "scienceType": [ "Birds", "Biodiversity", "Ecology & Environment", "Nature & Outdoors" ], "isBushfire": false, "projectActivity": { "dataQualityAssuranceMethods": null, "endDate": null, "records": [ { "commonName": null, "multimedia": [], "individualCount": null, "name": "Eurasian Coot (Fulica atra)", "coordinates": [ -33.765847083387165, 151.27954959869385 ], "eventTime": "08:30 AM", "guid": "urn:lsid:biodiversity.org.au:afd.taxon:3fa8ae8c-23e1-4fe1-b3c5-312f6fb528ab", "occurrenceID": "c4cf4098-0a7e-47ed-8cca-935c5ae9e1a1", "eventDate": "2018-07-26T14:00:00.000Z" }, { "commonName": null, "multimedia": [], "individualCount": null, "name": "Dusky Moorhen (Unmatched taxon)", "coordinates": [ -33.765847083387165, 151.27954959869385 ], "eventTime": "08:30 AM", "guid": null, "occurrenceID": "1da78311-1b64-47ff-856f-8bbca557f251", "eventDate": "2018-07-26T14:00:00.000Z" }, { "commonName": null, "multimedia": [], "individualCount": null, "name": "Magpie-Lark (Grallina cyanoleuca)", "coordinates": [ -33.765847083387165, 151.27954959869385 ], "eventTime": "08:30 AM", "guid": "urn:lsid:biodiversity.org.au:afd.taxon:92b72968-495a-442e-a81a-d6f9fe0c5b19", "occurrenceID": "9a1ebe36-e639-424b-b6e9-9bbaab9781d2", "eventDate": "2018-07-26T14:00:00.000Z" }, { "commonName": null, "multimedia": [], "individualCount": null, "name": "Noisy Miner (Manorina (Myzantha) melanocephala)", "coordinates": [ -33.765847083387165, 151.27954959869385 ], "eventTime": "08:30 AM", "guid": "urn:lsid:biodiversity.org.au:afd.taxon:f09bb7b3-908b-4321-9fc9-74d3a7425950", "occurrenceID": "c92f81ff-b841-4520-b2f0-206c9b9eb750", "eventDate": "2018-07-26T14:00:00.000Z" }, { "commonName": null, "multimedia": [], "individualCount": null, "name": "Red Wattlebird (Anthochaera (Anthochaera) carunculata)", "coordinates": [ -33.765847083387165, 151.27954959869385 ], "eventTime": "08:30 AM", "guid": "urn:lsid:biodiversity.org.au:afd.taxon:0b192938-6d54-4e6c-9bb1-a413a8c60d4c", "occurrenceID": "733247fd-77b0-4f7a-9058-dbd427bd10d5", "eventDate": "2018-07-26T14:00:00.000Z" }, { "commonName": null, "multimedia": [], "individualCount": null, "name": "Pacific Black Duck (Anas (Anas) superciliosa)", "coordinates": [ -33.765847083387165, 151.27954959869385 ], "eventTime": "08:30 AM", "guid": "urn:lsid:biodiversity.org.au:afd.taxon:da8a156f-95e2-4fcb-a6e7-52721705a70c", "occurrenceID": "5a4f26b7-cc8c-4b6e-b635-ef2741402536", "eventDate": "2018-07-26T14:00:00.000Z" }, { "commonName": null, "multimedia": [], "individualCount": null, "name": "Grey Butcherbird (Cracticus torquatus)", "coordinates": [ -33.765847083387165, 151.27954959869385 ], "eventTime": "08:30 AM", "guid": "urn:lsid:biodiversity.org.au:afd.taxon:13f69717-8792-46a1-b9d6-23322d21b2d3", "occurrenceID": "11adc4ca-0270-4794-9a42-3eae66c5c08c", "eventDate": "2018-07-26T14:00:00.000Z" } ], "projectType": "survey", "lastUpdatedYear": "2018", "embargoed": false, "activityOwnerName": "Russell Beardmore", "projectActivityId": "4294e55c-3a32-431a-82d9-465fafd4fd94", "lastUpdatedMonth": "August", "organisationName": "NORTHERN BEACHES COUNCIL", "methodType": null, "isDataManagementPolicyDocumented": null, "spatialAccuracy": null, "name": "Greendale Creek and Curl Curl Lagoon Bird Survey", "nonTaxonomicAccuracy": null, "temporalAccuracy": null, "projectName": "Greendale Creek and Curl Curl Lagoon Bird Survey 2017 to 2019", "projectId": "67a285a0-c9f4-465d-9cfd-f6ad31225fac", "embargoUntil": null, "speciesIdentification": null }, "isExternal": false, "countries": ["Australia"], "tags": ["noCost"], "projectActivityId": "4294e55c-3a32-431a-82d9-465fafd4fd94", "projectStage": "", "task": "Surveying 8 sites for 20 minutes each", "plannedStartDate": "2017-03-23T13:00:00Z", "name": "Greendale Creek and Curl Curl Lagoon Bird Survey 2017 to 2019", "alaHarvest": true, "projectSiteId": "1c9d4a20-d835-4b13-aa90-5a9a9cd46faf", "projectId": "67a285a0-c9f4-465d-9cfd-f6ad31225fac", "gear": "Binoculars and Australian bird identification book ", "status": "active", "aim": "To determine if increasing riparian vegetation and aquatic habitat will increase the diversity of wetland bird species at Greendale Creek and Curl Curl Lagoon", "origin": "atlasoflivingaustralia", "description": "Northern Beaches Council will be working with the Curl Curl Lagoon Friends to undertake a bird survey at Greendale Creek and Curl Curl Lagoon. The bird survey will occur the last Friday of each month for two years. There are 8 sites and each site will be surveyed for 20 minutes each.", "className": "au.org.ala.ecodata.Activity", "associatedOrgs": [], "associatedProgram": "Citizen Science Projects", "dataProviderId": "dp5004", "regenerateProjectTimeline": false, "geo": [{ "loc": { "lon": 151.27956, "lat": -33.765846 }, "siteName": "Site 8: Harbord Road Gross Pollutant Trap ", "siteId": "9346210b-1ab1-48a1-b09e-633e21f7e617" }], "ecoScienceType": [], "managerEmail": "Jeanne Thuez", "isSuitableForChildren": false, "dateCreated": "2018-08-24T00:46:01Z", "isSciStarter": false, "orgGrantee": "", "isCitizenScience": true, "surveyYear": "2018", "funding": 0, "legalCustodianOrganisation": "Northern Beaches Council", "manager": "jeanne.thuez@northernbeaches.nsw.gov.au", "projectDatesChanged": false, "docType": "activity", "orgSponsor": "", "userId": "61408", "projectStatus": [ { "name": "Active", "id": "active" }, { "name": "Completed", "id": "completed" }, { "name": "Deleted", "id": "deleted" } ], "isMERIT": false, "organisationName": "Northern Beaches Council", "mainTheme": "", "progress": "planned", "siteId": "9346210b-1ab1-48a1-b09e-633e21f7e617" }

**Comment by chrisala** [comment]
Type: activity Index: pasearch Error: failed to parse [sites.extent.geometry.centre] Document: { "legalCustodianOrganisationType": "", "organisationId": "d1ba796f-2d3e-45a6-b2d5-6e00fb7520c9", "keywords": "environment\nbioblitz\nfauna\nflora\nsurvey\ndiscover\nYalgorup \nYalgorup National Park\nMandurah\npossum\nanimal\nplants\n", "projectType": "survey", "formVersion": 1, "sites": [{ "area": "285.6134034823835", "extent": { "geometry": { "datum": "", "fid": "", "areaKmSq": 285.6134034823835, "precision": "", "lga": "Mandurah (C)", "bbox": "", "nrm": "Peel-Harvey", "locality": "", "coordinates": [ 115.65662268083543, -32.74004840536834 ], "decimalLongitude": 115.65662268083543, "centre": "null", "decimalLatitude": -32.74004840536834, "pid": "", "mvs": "Eucalyptus woodlands with a shrubby understorey", "uncertainty": "", "type": "Circle", "name": "", "state": "Western Australia (including Coastal Waters)", "layerName": "", "radius": 9537.278576077231, "mvg": "Eucalypt Woodlands" }, "source": "drawn" }, "notes": "", "projects": ["6836edca-baf4-4372-81cf-3388abe06fcd"], "description": "species found at the Yalgorup bioblitz 2018", "externalId": "Yalgorup National Park Bioblitz 2018", "type": "surveyArea", "geoIndex": { "coordinates": [[ [ 115.70750802953224, -32.74058350329464 ], [ 115.70744660665397, -32.737882114764986 ], [ 115.70718461527493, -32.7351893152181 ], [ 115.70672310734909, -32.732515731116976 ], [ 115.70606392177949, -32.729871912152355 ], [ 115.70520967688476, -32.72726828963556 ], [ 115.70416375980133, -32.72471513537281 ], [ 115.70293031286687, -32.722222521182665 ], [ 115.70151421704357, -32.7198002792155 ], [ 115.69992107244914, -32.717457963230416 ], [ 115.69815717607655, -32.715204810981355 ], [ 115.6962294967925, -32.71304970785915 ], [ 115.69414564771606, -32.711001151931676 ], [ 115.69191385608823, -32.7090672205183 ], [ 115.68954293075242, -32.707255538428754 ], [ 115.68704222737541, -32.70557324798991 ], [ 115.68442161154556, -32.70402698097712 ], [ 115.68169141989438, -32.70262283255871 ], [ 115.6788624193934, -32.701366337354905 ], [ 115.6759457649855, -32.70026244770371 ], [ 115.67295295571658, -32.69931551421788 ], [ 115.66989578953753, -32.698529268708235 ], [ 115.6667863169524, -32.69790680953906 ], [ 115.6636367936922, -32.69745058947228 ], [ 115.6604596325979, -32.69716240604712 ], [ 115.65726735489797, -32.6970433945323 ], [ 115.65407254106891, -32.69709402347816 ], [ 115.65088778146877, -32.69731409288506 ], [ 115.64772562693317, -32.69770273499598 ], [ 115.64459853952516, -32.69825841770912 ], [ 115.64151884362853, -32.6989789505981 ], [ 115.63849867757307, -32.699861493515755 ], [ 115.63554994597916, -32.70090256774865 ], [ 115.63268427300521, -32.702098069678854 ], [ 115.6299129566791, -32.70344328690023 ], [ 115.62724692449103, -32.70493291672681 ], [ 115.62469669041927, -32.706561087021726 ], [ 115.62227231355702, -32.70832137926574 ], [ 115.61998335850107, -32.71020685377648 ], [ 115.61783885765732, -32.71221007697992 ], [ 115.61584727561147, -32.71432315062899 ], [ 115.61401647570459, -32.71653774285542 ], [ 115.61235368894626, -32.718845120934226 ], [ 115.6108654853884, -32.72123618563342 ], [ 115.60955774807456, -32.72370150701525 ], [ 115.6084356496687, -32.72623136154919 ], [ 115.60750363185896, -32.72881577039208 ], [ 115.6067653876196, -32.73144453868565 ], [ 115.60622384640541, -32.734107295717735 ], [ 115.60588116233929, -32.73679353578991 ], [ 115.6057387054452, -32.73949265963111 ], [ 115.60579705596368, -32.74219401619472 ], [ 115.60605600177792, -32.7448869446745 ], [ 115.60651453896426, -32.74756081657411 ], [ 115.60717087546989, -32.75020507766407 ], [ 115.6080224379075, -32.75280928966052 ], [ 115.60906588144468, -32.75536317146081 ], [ 115.6102971027529, -32.7578566397727 ], [ 115.61171125596954, -32.760279848975856 ], [ 115.61330277161291, -32.762623230057294 ], [ 115.61506537837961, -32.76487752846592 ], [ 115.61699212774093, -32.76703384073529 ], [ 115.61907542124324, -32.76908364972858 ], [ 115.6213070404074, -32.771018858364826 ], [ 115.62367817910999, -32.77283182169177 ], [ 115.62617947831939, -32.77451537717661 ], [ 115.62880106305066, -32.77606287309348 ], [ 115.63153258139225, -32.77746819489345 ], [ 115.63436324545003, -32.77872578945138 ], [ 115.63728187404581, -32.77983068709175 ], [ 115.64027693699956, -32.78077852130517 ], [ 115.6433366008185, -32.78156554607578 ], [ 115.64644877560923, -32.78218865074986 ], [ 115.6496011630253, -32.78264537238546 ], [ 115.6527813050562, -32.7829339055333 ], [ 115.65597663346225, -32.78305310940928 ], [ 115.65917451965535, -32.78300251242944 ], [ 115.66236232482439, -32.78278231408925 ], [ 115.66552745010314, -32.78239338417916 ], [ 115.66865738657812, -32.7818372593397 ], [ 115.67173976493397, -32.78111613696989 ], [ 115.67476240453686, -32.78023286651338 ], [ 115.67771336175707, -32.77919093815735 ], [ 115.68058097733675, -32.77799446898981 ], [ 115.68335392261194, -32.77664818667085 ], [ 115.68602124440307, -32.775157410683654 ], [ 115.688572408394, -32.77352803124081 ], [ 115.69099734082634, -32.771766485930485 ], [ 115.69328646834168, -32.76987973419673 ], [ 115.69543075581444, -32.76787522975612 ], [ 115.69742174202402, -32.76576089106159 ], [ 115.6992515730261, -32.76354506993192 ], [ 115.70091303309145, -32.761236518472636 ], [ 115.70239957309087, -32.75884435442058 ], [ 115.70370533621622, -32.75637802505095 ], [ 115.70482518093766, -32.753847269790796 ], [ 115.70575470110902, -32.751262081688225 ], [ 115.70649024314514, -32.7486326678909 ], [ 115.70702892020674, -32.74596940929091 ], [ 115.70736862334007, -32.743282819496706 ], [ 115.70750802953224, -32.74058350329464 ] ]], "type": "Polygon" }, "lastUpdated": "2018-10-18T00:59:23Z", "dateCreated": "2018-10-18T00:59:23Z", "name": "Lake Clifton Thrombolites and Mandurah Wildlife Rescue", "siteId": "c37052e1-16f7-474a-bc4f-1b18c2b5933f", "id": "5bc7daebe4b0416753b2e00b", "isSciStarter": false, "status": "active" }], "type": "Multiple Sightings", "plannedEndDate": "2018-10-20T16:00:00Z", "facets": [], "lastUpdated": "2018-10-21T04:22:16Z", "uNRegions": ["Oceania"], "activityId": "dc7f31db-c1f8-4506-9d23-9ea4cd31f93c", "assessment": false, "promoteOnHomepage": "no", "dataResourceId": "dr8623", "id": "5b680104e4b02ca4306d95b8", "termsOfUseAccepted": true, "scienceType": [ "Animals", "Biology", "Birds", "Ecology", "Insects & Pollinators", "Symbyotic Interactions", "Biodiversity", "Ecology & Environment", "Indigenous knowledge", "Nature & Outdoors", "Geology & soils", "Indigenous science", "Physical science", "Technology", "Long-Term Species Monitoring", "Fire Ecology", "Geomorphology", "Marine & Terrestrial", "Water" ], "isBushfire": false, "projectActivity": { "dataQualityAssuranceMethods": [ "dataownercurated", "subjectexpertverification", "recordannotation" ], "endDate": "2018-10-24T16:00:00Z", "records": [], "projectType": "survey", "lastUpdatedYear": "2018", "embargoed": false, "activityOwnerName": "Tarnee Rutherford", "projectActivityId": "854006fb-1c51-498a-90de-82da987ac693", "lastUpdatedMonth": "October", "organisationName": "CITY OF MANDURAH", "methodType": "opportunistic", "isDataManagementPolicyDocumented": false, "spatialAccuracy": "high", "name": "Fauna, Birds, Invertebrate and Frog Survey", "surveyImage": true, "nonTaxonomicAccuracy": "high", "temporalAccuracy": "high", "projectName": "Yalgorup Bioblitz 2018", "projectId": "6836edca-baf4-4372-81cf-3388abe06fcd", "embargoUntil": null, "speciesIdentification": "high" }, "isExternal": false, "countries": ["Australia"], "tags": [ "noCost", "isSuitableForChildren", "hasTeachingMaterials" ], "difficulty": "Medium", "projectActivityId": "854006fb-1c51-498a-90de-82da987ac693", "projectStage": "", "task": "The fauna survey led by Joe Tonga will involve exploring Yalgorup bushland along designated tracks, observing and identifying native wildlife species, setting up motion activated technology, looking into nest boxes and more. This is your chance to observe, identify and record native fauna species as you encounter them. Please note this activity requires major physical activity and is the longest survey session running from 10am-5pm with a lunch break. If you register for this activity, you will need to stay the full time.\nThe invertebrate survey run by scientist Michael Curran will involve exploring wetlands and rocky outcrops within Yalgorup. You will have the chance to observe, identify and record our spineless friends. Some invertebrates you may see include snails, slugs and scorpions. Please note this activity requires moderate physical activity.\nThe frog and amphibian survey run by the Frog Doctor Johnny Prefumo involves looking through wetlands, and riparian vegetation within Yalgorup. You will be able to hear, find and observe native frog species. Be sure to download the frog ID app before the survey, to listen to different frog calls. Please bring a headlamp or torch . Please note this activity requires moderate physical activity.\nThe various night stalks involve exploring Yalgorup through the night, looking for nocturnal species. Some critters you may encounter include the critically endangered Western Ringtail Possum, Brush tailed Phascogales and Tawny Frogmouths just to name a few. Please bring a headlamp or torch. Please note this activity requires moderate physical activity.\nThe Shorebird and Wetland bird survey led by Birdlife experts involves looking through scopes and binoculars to identify and record unique bird species. This is your chance to learn about migratory shorebirds, and wetland bird species and pick up on their distinctive markings that tell them apart. Please bring binoculars. Please note this activity requires minor physical activity.\nThe Bushland bird survey led by Birdlife experts involve exploring the Yalgorup bushland searching for bushland birds that call the national park home. This is your chance to photograph unique birds, and record your sightings. Please bring binoculars. Please note this activity requires minor physical activity.\n\nThe ranger walk and talks involve going on a tour throughout Yalgorup National Park with Yalgorup Rangers from the Parks and Wildlife Division. The Yalgorup Rangers will give you an insight into managing the national park, the thrombolites, some of the native animals and plants, and is a great introduction to start off your day at the Bioblitz. Please note this activity requires minor physical activity.\nThe smoking ceremony will be held at the open space along Quail Road in Bouvard, and will be a celebratory event to bless the Bioblitz starting in Yalgorup National Park. Local elder, Harry Nannup will lead the smoking ceremony, and everyone is invited to attend. The smoking ceremony will be followed with a Possum Night stalk. Please bring a torch if you want to attend the possum night stalk. \n", "plannedStartDate": "2018-10-18T16:00:00Z", "name": "Yalgorup Bioblitz 2018", "alaHarvest": false, "projectSiteId": "13e431cf-ae95-425d-81c5-e621d4c27443", "projectId": "6836edca-baf4-4372-81cf-3388abe06fcd", "gear": "Be dressed in appropriate clothing to complete the field work and activities. This includes: Long pants, long sleeved shirt , hat, boots or sneakers, sunglasses, sunscreen , mosquito repellent. \nBring a back pack with water, snacks and lunch, any other field supplies you might need for your activity such as camera, binoculars, torches or headlamps and notepads and pens.\n", "status": "active", "aim": "To increase community ownership of Yalgorup National Park and provide environmental volunteers opportunities for upskilling\nBringing together professional and amateur ecologists and those interested in learning more about their natural environment, and what lives in their backyard", "origin": "atlasoflivingaustralia", "description": "The City of Mandurah invites you to a day full of discoveries in Yalgorup National Park. Bring your family, friends and neighbours along to this community event to help find out what animals and plants call Yalgorup National Park home. The Yalgorup Bioblitz is an education event aimed at bringing together professional and amateur ecologists and those interested in learning more about their natural environment. It is a great way to raise community awareness about Yalgorup as well as increase community understanding and awareness of what is living in your own backyard.\n\nThere will be surveys and activities you can get involved with at the Yalgorup Bioblitz. Flora and fauna specialists from the local area will lend their expertise to help you discover and identify species throughout the day.\n\nParticipants will have the opportunity to identify woodland birds and shorebirds, go on an evening nightstalk to see our nocturnal animals, learn about Yalgorup and how Parks and Wildlife Rangers manage the park on a ranger walk and talks, learn from Kingsley Dixon on how to conduct a flora survey, look into habitat and nesting boxes, see the endangered ringtail possum and more.\nHelp us discover what lives in Yalgorup National Park and celebrate its uniqueness\n\nThe Site\nYalgorup National Park is located 105 Km’s south of Perth and in the southernmost part of Mandurah, beginning just over the Dawesville Channel. Yalgorup is known for its extended lake system, beautiful tuart and peppermint woodlands and for the microscopic societies that form thrombolites. Yalgorup National park is home to many unique species of plants and animals, including the critically endangered Ringtail Possum\n\nWhat you need to do\nDownload the Biocollect app to record your sightings, prior to the Yalgorup Bioblitz\nRead through the activity program and register for the activities at the link below. Be sure to arrive on time for your activity\nBe dressed in appropriate clothing to complete the field work and activities. This includes: Long pants, long sleeved shirt , hat, boots or sneakers, sunglasses, sunscreen , mosquito repellent. \nBring a back pack with water, snacks and lunch, any other field supplies you might need for your activity such as camera, torches or headlamps and notepads and pens.\n\nRegister here: https://mandurah.formstack.com/forms/yalgorup_bioblitz_registration \n", "className": "au.org.ala.ecodata.Activity", "associatedOrgs": [], "associatedProgram": "None", "dataProviderId": "dp3903", "regenerateProjectTimeline": false, "geo": [{ "loc": { "lon": 115.656624, "lat": -32.740047 }, "siteName": "Lake Clifton Thrombolites and Mandurah Wildlife Rescue", "siteId": "c37052e1-16f7-474a-bc4f-1b18c2b5933f" }], "ecoScienceType": [], "managerEmail": "Tarnee Rutherford", "isSuitableForChildren": true, "dateCreated": "2018-10-21T04:22:16Z", "isSciStarter": false, "thumbnailUrl": "https://ecodata.ala.org.au/uploads/2018-10/thumb_IMG20181020122055.jpg", "orgGrantee": "", "isCitizenScience": true, "funding": 0, "legalCustodianOrganisation": "City of Mandurah", "manager": "tarnee.rutherford@mandurah.wa.gov.au", "surveyDate": [], "docType": "activity", "orgSponsor": "", "userId": "57661", "isMERIT": false, "organisationName": "City of Mandurah", "getInvolved": "Help us discover what lives in Yalgorup National Park and celebrate its uniqueness\nRegister online: https://mandurah.formstack.com/forms/yalgorup_bioblitz_registration \nRead through the activity program and register for the activities. \nBe sure to arrive on time for your activity and wear the correct Personal Protection clothing and footwear. \nPlease download the free Biocollect app\n", "industries": [], "mainTheme": "", "progress": "planned", "siteId": "c37052e1-16f7-474a-bc4f-1b18c2b5933f", "urlWeb": "https://mandurah.formstack.com/forms/yalgorup_bioblitz_registration" }

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-21
