### ISSUE TITLE
Add static content pages to the project finder tool

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#128]
Need to add a couple of static content pages to the project finder tool:
* "What is this?" - Page to explain all about the "why" of the project finder
* "Getting started" - Page to explain how to use the tool

May be best to implement this as button-based links out to wordpress pages where the content can be better authored/managed.

Maybe combine with issue #

**Comment by pbrenton** [comment]
Allow content editing via "Admin > Static pages"

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-38
