### ISSUE TITLE
Add 'add another record' button on activity view page 

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1280]
Currently no one-click way of adding another record once a record has been submitted. It is possible to put a link in the form but this doesn't work if a form is used for multiple surveys. A button would improve usability for users. 

This issue has been raised by NT Wildwatch and NSW Waterwatch.

**Comment by sat01a** [comment]
Fixed.

**Comment by sat01a** [comment]
Fixed

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-22
