### ISSUE TITLE
Unhelpful error message when trying to add a user not registered with the ALA

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1282]
![Screen Shot 2020-06-18 at 1 56 42 pm](https://user-images.githubusercontent.com/25336120/84976577-95bc8b00-b16b-11ea-83c5-8759e8fd4f4e.png)
Error dialog box when trying to add a user as a member to a project when they haven't registered with the ALA. Would be good to have something like "This user has not registered with the ALA yet. You will need to ask them to create an account before you can register them."

**Comment by sat01a** [comment]
Refer - #1287 - Fixed
