### ISSUE TITLE
OzAtlas - Selecting a Saved Location no longer updates map

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocollect#1284]
Reported in helpdesk ticket 82615.

User has multiple locations saved, however selecting them does not automatically update the visual map to that location. This requires the user to manually set a map location each time, which is causing multiple new duplicate locations being added to the list of saved locations.

Screenshot submitted by the user attached.

![Screenshot_2020-06-29 Create OzAtlas Sightings Bio Collect](https://user-images.githubusercontent.com/57081387/86209051-12605800-bbb5-11ea-8124-beb62e87aa55.png)

**Comment by temi** [comment]
@timhicks-ala this should be fix on prod now.
