### ISSUE TITLE
Don't send emails with for "New survey method: null"

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#1285]
The biocollect support email gets quite a few emails suggesting "null" be added to the survey method list.

**Comment by pbrenton** [comment]
I don’t support this as it doesn’t make any sense and encourages people to bypass the QA built into the rules. It would be better for us to do a better job of explaining why this is important.

Sent from my iPhone

On 9 Jul 2020, at 2:15 pm, chrisala <notifications@github.com> wrote:

﻿

The biocollect support email gets quite a few emails suggesting "null" be added to the survey method list.

**Comment by temi** [comment]
## steps to test
1. Go to [Stream watch project on test](https://biocollect-test.ala.org.au/acsa/project/index/fb40be45-c856-4218-b33d-af35df439e08)
2. Update method sampling method used. Do you get an email with sampling method?
3. Go to visibility tab and update embargo option. Do you get an email with null?
4. Try the same on production website to know the difference.

**Comment by pbrenton** [comment]
Not sure whether this was being switched off or not, but I did receive email for new survey notification.
