### ISSUE TITLE
Adding species to survey alerts does not work

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1286]
Start typing in a species in the 'Species name' field and options appear but click on one of the options and nothing happens. The user doesn't get any feedback about an error but the error `Uncaught TypeError: d.scientificName is not a function` is displayed.

**Comment by sat01a** [comment]
Fixed

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-26
