### ISSUE TITLE
Adding unregistered members to the project throws html tag error page

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1287]

**Comment by sat01a** [comment]
Fixed

**Comment by matilda2812** [comment]
This issue was also raised in #1282

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-22

**Comment by sat01a** [comment]
> This issue was also raised in #1282

Closed the duplicate issue

**Comment by matilda2812** [comment]
Current popup text is unclear, it should be changed to: "This user does not have an active Atlas of Living Australia account. Please ask the user to register with the ALA before adding them as a project member"

**Comment by sat01a** [comment]
Updated the popup text
