### ISSUE TITLE
Activity comments not working 

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/biocollect#1289]
User gets an error as shown when they try to add a comment. 
![Screen Shot 2020-07-21 at 3 56 37 pm](https://user-images.githubusercontent.com/25336120/88018313-d7759280-cb6a-11ea-8899-7b0b0695565d.png)
There is also an error trying to retrieve comments. 
![Screen Shot 2020-07-21 at 3 59 12 pm](https://user-images.githubusercontent.com/25336120/88018477-24f1ff80-cb6b-11ea-929a-ab64b3d223f3.png)
User also reports not being able to see the comments section on records other than their own, even though they are a moderator.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-22
