### ISSUE TITLE
Draft and attach Terms of Use to link on project metadata page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#129]
A placeholder link to a ToU agreement already exists on the project metadata template, but the ToU is still to be drafted and added.

**Comment by pbrenton** [comment]
Associated with #13

**Comment by m-r-c** [comment]
#13 is done - once the Terms of Use page is published, we will need to update https://github.com/AtlasOfLivingAustralia/ala-install/blob/9ef0fe1c09da172ae27101a4f978c099cc8a84a0/ansible/roles/biocollect/templates/biocollect-config.properties#L64 to point to it

**Comment by pbrenton** [comment]
The URL for the BioCollect ToU page is http://www.ala.org.au/terms-of-use-biocollect/ and can now be linked, though I am only about 1/2 way through the content editing.

**Comment by m-r-c** [comment]
The config file has been updated.
