### ISSUE TITLE
Security: Use apikey for image uploads

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocollect#1290]
The insecure "IP Whitelist" method was implemented on image-service for limited backwards compatibility while the various systems update. Unfortunately there was no comment when closing issue #1202 and no response to my query to @sat01a about the current situation so I am opening this to track implementing the use of apikeys by biocollect so that we can remove the insecure "IP Whitelist" from image-service.

**Comment by sat01a** [comment]
@ansell, sorry didn't see your note on #1202. I was cleaning the long list of old tickets from apps project board/ repo board. Missed this one. We will the include the fix in 5.1 release.

**Comment by sat01a** [comment]
Tested it against image-test server with auth-test apiKey. 
Example reference: https://images-test.ala.org.au/store/b/e/2/7/7ff93374-6f77-4ffb-8e1d-68ebfb1b72eb/thumbnail
@chrisala @ansell

**Comment by sat01a** [comment]
https://upsource.ala.org.au/ecodata/review/ECDT-CR-31?filePath=/grails-app/services/au/org/ala/ecodata/RecordService.groovy

**Comment by ansell** [comment]
The changes look good to me. They use the default `apiKey` header from ala-ws-security-plugin to support apiKey authentication to image-service:

https://github.com/AtlasOfLivingAustralia/ala-ws-security-plugin/blob/8dad75b6e24b08f0a54d00f7c2a0333425928cd8/grails-app/controllers/au/org/ala/ws/security/ApiKeyInterceptor.groovy#L17

**Comment by sat01a** [comment]
It will be included in the next ecodata release
