### ISSUE TITLE
Unable to create works projects with funding sources

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#1291]
To reproduce:
1. Create a works project, making sure to add funding sources.
2. Save the project

Expected:
Project is saved

Actual:
Two error dialogs are displayed, one with:
Failed to save your data: Error creating project - Could not find matching constructor for: au.org.ala.ecodata.Funding(au.org.ala.ecodata.Funding)
Failed calling web service. Server returned HTTP response code: 400 for URL: https://ecodata-test.ala.org.au/ws/project/ URL= https://ecodata-test.ala.org.au/ws/project/.

**Comment by sat01a** [comment]
Fixed
