### ISSUE TITLE
Page not found when viewing a organisation records

### ISSUE THREAD

**Issue by thakuad** [AtlasOfLivingAustralia/biocollect#1294]
**To reproduce:** 

1. click on this link ([click Here](https://biocollect.ala.org.au/nrmworks/organisation/index/03fdf2ca-3388-4df2-a1ff-1eb293a3c884#organisationName%3DBass%20Coast%20Landcare%20Network%20Inc%26skipDefaultFilters%3Dtrue%26max%3D20%26sort%3DdateCreatedSort))

2. click on view record.

**Expected:** 
able to view the records details. 

**Actual:** 
page not Found 
![Screen Shot 2020-08-11 at 1 17 08 pm](https://user-images.githubusercontent.com/61674524/89853537-01076400-dbd5-11ea-90ac-aa5d838f4311.png)

**Comment by sat01a** [comment]
Fixed

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-26

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-27
