### ISSUE TITLE
Downloading large amounts of data fails

### ISSUE THREAD

**Issue by matildastevenson** [AtlasOfLivingAustralia/biocollect#1295]
- Large numbers of records and/or records with high resolution images cause the download to fail, but the threshold is not clear to the user
- There is an asynchronous download threshold of 500 but this is ignored and even downloads larger than this are being done synchronously
- Suggest: **all** downloads request a user email address and are downloaded asynchronously

**Comment by sat01a** [comment]
Also, In Echina CSI project, some records has thumbnail and some has full image. 
I think, the data that comes via API from echidna has full image instead of thumbnail and full image, but the data that comes through BioCollect has both thumbnail and full image.

**Comment by yasima-csiro** [comment]
Tested small and large data downloads. Small data sets downloaded the data straightway.Large data sets were downloaded asynchronously.
