### ISSUE TITLE
Issues with manual coordinate entry

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1299]
* Cannot save activity when manual coordinates are added. At the moment, users need to first add a marker to the map before they can successfully add coordinates manually.
* When project area is a spatial object, users are prompted to add point even if point is within the object.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BCLLC-CR-28
https://upsource.ala.org.au/ecodata-client-plugin/review/ECP-CR-40

**Comment by sat01a** [comment]
Reviewed
