### ISSUE TITLE
Add terms of use to project metadata

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#13]
Add a modal based terms of use acceptance panel as a mandatory requirement for the initial save of project metadata.

Expected behaviour:
1. Insert a "Terms of Use (mandatory agreement)" link beside the project internal/external selector on the project metadata page
2. On-click link to open a modal containing the Terms of Use text and agreement check-box (mandatory). Should also display mandatory marker (always) and message if attempt to save ("Agree" button)
3. "Cancel" button to close modal without saving

**Comment by pbrenton** [comment]
Terms of Use text still to be drafted and approved, but feature can be developed without it.

**Comment by matthewandrews** [comment]
Just a side note: if you have modals, remember to test on small screen e.g. phone - depending on how the CSS positioning is done, it can make the site unusable if the modal is wholly/partly off-screen.

**Comment by djtfmartin** [comment]
I agree with Matt. I think in general if you can avoid using a modal its a good thing.

**Comment by m-r-c** [comment]
Biocollect PR https://github.com/AtlasOfLivingAustralia/biocollect/pull/200

I have also updated ala-install to add the new config property, but with a placeholder value until the real page is published.
