### ISSUE TITLE
"Get Started" button on project overview gives a 404 on BioCollect test project

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#131]
To reproduce:
1. Navigate to http://biocollect-dev.ala.org.au/project/index/eccadc59-2dc5-44df-8aac-da41bcf17ba4
2. Press the green "Get Started" button.

**Comment by m-r-c** [comment]
Cannot replicate. Following the link takes you to the Surveys tab. Going back to the About tab and clicking Get Started takes you to the Surveys tab again. Must have already been fixed.
