### ISSUE TITLE
Facet labels are not populated properly for numeric facets

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocollect#1332]
Facet labels are not populated properly for numeric facets. The labels are listed as "Unknown".

<img width="448" alt="image" src="https://user-images.githubusercontent.com/72474143/127240312-09f2f058-93ef-4ce7-bae9-5d397bab5af3.png">

**Comment by yasima-csiro** [comment]
Fixed with https://github.com/AtlasOfLivingAustralia/biocollect/commit/8fb9db72d8da7f4ee972d532e53382619f812a79

**Comment by pbrenton** [comment]
Functional testing successfully completed 16/08/2021

**Comment by yasima-csiro** [comment]
Released with 5.2.1
