### ISSUE TITLE
Hide Graphs tab if graphs are not configured.

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocollect#1333]
Hide Graphs tab if graphs are not configured.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/72474143/127240466-7a236a95-781d-4bfd-8d8f-0a5dee5982f2.png">

**Comment by pbrenton** [comment]
Functional testing successfully completed 16/08/2021

**Comment by pbrenton** [comment]
Functional testing completed successfully 16/08/2021

**Comment by yasima-csiro** [comment]
Released with 5.2.1
