### ISSUE TITLE
Remove "Record a sighting" title from the survey form

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocollect#1335]
Remove "Record a sighting" title from the survey form

<img width="929" alt="image" src="https://user-images.githubusercontent.com/72474143/128647220-eae78896-6e92-46fc-be11-d7c67ff1ff9c.png">

**Comment by yasima-csiro** [comment]
Requirement changed from removing "Record a sighting" to renaming to "Create a record".

**Comment by pbrenton** [comment]
Successfully tested in the test environment.

**Comment by yasima-csiro** [comment]
Released with 5.2.1
