### ISSUE TITLE
Download form template (.xlsx) function is not working

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocollect#1336]
Download form template (.xlsx) function is not working.

Following error is displayed.

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/72474143/128647294-233da92e-4096-4173-864e-6701fe839702.png">

**Comment by pbrenton** [comment]
Successfully tested in the test environment.

**Comment by yasima-csiro** [comment]
Deployed to Prod.
