### ISSUE TITLE
Upgrade ecodata client plugin to 3.1

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocollect#1337]
Upgrade ecodata client plugin to 3.1

**Comment by yasima-csiro** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/commit/38af51e3cf50094fcf1baa6a0ecaa5cfd04fdd10

**Comment by pbrenton** [comment]
Functional testing completed successfully 16/08/2021

**Comment by yasima-csiro** [comment]
Released with 5.2.1
