### ISSUE TITLE
New functionality to read custom Js files under /data/scripts directory

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocollect#1338]
Currently the custom Js files developed to support different functionalities of different hubs are stored in dropbox. 
These files need to be moved to /data/scripts folder for security reasons.
 
To achieve that, new functionality need to be implemented to read custom Js files under /data/scripts directory.

**Comment by pbrenton** [comment]
Functional testing completed successfully 16/08/2021

**Comment by yasima-csiro** [comment]
Released with 5.2.1
