### ISSUE TITLE
Update legacy images url

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/biocollect#1343]
images url from the listRecordsForDataResourceId with http://images.ala.org.au cannot be synced up in pipelines currently, hence they cannot be tied back to the occurrence records in biocahce. 

After some discussions with @djtfmartin, a preferred approach to address this issue is to update the image urls from biocollect such that legacy stuffs like http://images.ala.org.au urls should be https://images.ala.org.au for consistency sake.

**Comment by sbearcsiro** [comment]
HTTP Image URLs should now be updated.
