### ISSUE TITLE
BioCollect generating Images with text

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1352]
Steps to view list of images with text
1. Visit data tab for below porjects
2. image tab
3. select page size as 100

https://biocollect.ala.org.au/acsa/project/index/99915577-ada2-48ef-907e-193550ac66bb
https://biocollect.ala.org.au/acsa/project/index/ada19123-152b-482f-81ae-4391d7214040
https://biocollect.ala.org.au/acsa/project/index/4048a890-2c86-4175-80c7-3224db9bdcc0

**Comment by temi** [comment]
These images are getting transferred to ALA - https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr17831#tab_recordImages

**Comment by temi** [comment]
The cause of this issue is the plugin capturing paste command and interpreting the pasted content as image. 
Steps to reproduce. 
1. Copy a cell from spreadsheet
2. Paste it on a field.
3. Image section should have the copied text.

Otherwise,
1. Copy an image
2. Go to a survey which accepts image
3. Paste the image on the page
4. The image will appear on image section

**Comment by pbrenton** [comment]
Tested successfully
