### ISSUE TITLE
Acitivity map zooming to wrong location

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1361]
Expected:

1. Go to [this activity](https://biocollect-test.ala.org.au/coralwatch/bioActivity/index/247d5756-eb01-48d2-a391-2443be25517e?returnTo=%2Fcoralwatch%2FbioActivity%2Flist).
2. Edit the [site](https://biocollect-test.ala.org.au/coralwatch/site/index/decfa061-14fa-4ae4-895c-bd979e5cf68c)  the location of site by moving marker.
3. Come back to the activity and refresh the page. Map should zoom to the new marker location.

**Comment by pbrenton** [comment]
This worked for the coralwatch case provided, ie. select from existing site list, but I also tried https://biocollect-test.ala.org.au/acsa/bioActivity/index/e5c0d1a0-ce30-468c-bedc-3d2d5adc4cf8 and the site location change was not saved.
