### ISSUE TITLE
Image published to image server but not updated in record document

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1393]
Some records in record collection still point image to BioCollect even though image is published on Image server. An example is https://biocollect.ala.org.au/sightings/bioActivity/index/75dd66b7-f6b0-443e-8e72-353ebd2c87e4 . The issue with this particular case is imageId stored with `Document` instance but `Record` instance is not updated with it. Make sure imageId is copied and URL updated.

Linked to https://github.com/AtlasOfLivingAustralia/data-management/issues/732#issuecomment-1033187394

**Comment by temi** [comment]
Steps to check on biocollect-test

1. Go to [sightings](https://biocollect-test.ala.org.au/bioActivity/create/d57961a1-517d-42f2-8446-c373c0c59579?returnTo=%2Fsightings%2FbioActivity%2FprojectRecords%2Fb3d8e243-1137-4d26-9e15-c5a6f90815eb&hub=sightings)
2. Upload an image
3. View record generated using Mongo Shell `db.record.find({activityId: 'xxxxxxx'}).pretty()`
4. check multimedia property. is identifier pointing to image server?

**Comment by yasima-csiro** [comment]
Tested and passed.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/72474143/200198256-613e0b41-e131-429c-ad23-02d93351c90b.png">
