### ISSUE TITLE
Project level document enhancements

### ISSUE THREAD

**Issue by chamaliperera512** [AtlasOfLivingAustralia/biocollect#1402]
1) The existing interface needs to be changed as below to enable users to preview documents, view metadata of them and download documents.

![image](https://user-images.githubusercontent.com/28555025/155467004-a12eb2b6-1cbe-45c4-b65b-0c3d798fc712.png)

2) The ‘View Metadata’ option will display the document’s metadata according to a similar format to below. This will display dynamically in the existing viewing panel 

![image](https://user-images.githubusercontent.com/28555025/155467140-81095a10-c6c8-4871-a18f-35bc0dba0502.png)

The following fields will be included to the above format when viewing a document’s metadata:

Title 
Author 
Abstract 
Description 
Document type 
Citation 
Keywords 
DOI (if Document type is Journal article) 
Date uploaded 
Date last modified 

3) Change Admin view of Documents to include new document types

![image](https://user-images.githubusercontent.com/28555025/155484919-741b63a1-3d94-4f88-b0ee-b283267b514f.png)

**Comment by pbrenton** [comment]
Regarding design point 1 above, the buttons labeled as "Preview" and "View metadata" should be displayed as appropriate icons with these labels shown as on-hover tool tips.
