### ISSUE TITLE
Javascript error: "You cannot apply bindings multiple times to the same element."

### ISSUE THREAD

**Issue by cofiem** [AtlasOfLivingAustralia/biocollect#1409]
There is a javascript error on the biocollect project page for works type projects.

Example page: [NRM Works - Cheetham Creek Wetlands](https://biocollect.ala.org.au/nrmworks/project/index/aa7dc972-2f42-4f26-8d03-0ad62a5eb527)

The error is raised in [worksProjectTemplate.gsp](https://github.com/AtlasOfLivingAustralia/biocollect/blob/v5.2.6/grails-app/views/project/worksProjectTemplate.gsp#L197).

```
Uncaught Error: You cannot apply bindings multiple times to the same element.
    at C (common.unminified.js:1346:330)
    at l (common.unminified.js:1345:387)
    at Object.a.Rb (common.unminified.js:1351:413)
    at HTMLDocument.<anonymous> (aa7dc972-2f42-4f26-8d03-0ad62a5eb527:1479:16)
    at n (base.unminified.js:14297:11)
    at Object.fireWith [as resolveWith] (base.unminified.js:14427:7)
    at Function.ready (base.unminified.js:14647:3)
    at HTMLDocument.e (base.unminified.js:14682:3)
```

**Comment by cofiem** [comment]
This error might be caused by some of the javascript being rendered twice.

The layout views contain `<asset:deferredScripts/>`, but `worksProjectTemplate.gsp` also contains [`<asset:deferredScripts/>`](https://github.com/AtlasOfLivingAustralia/biocollect/blob/v5.2.6/grails-app/views/project/worksProjectTemplate.gsp#L407).

Perhaps `<asset:deferredScripts/>` should be removed from worksProjectTemplate.gsp?

**Comment by temi** [comment]
Thanks for reporting the bug. you are right. I have removed it in develop branch. it will be fixed in 6.0.

**Comment by cofiem** [comment]
@temi Thanks.
Should this also be fixed in `v5.x`?

**Comment by temi** [comment]
@cofiem We are planning to release 6.0 as soon as possible. Feel free to send a PR.
