### ISSUE TITLE
Add OIDC support into BioCollect

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1414]
Update BioCollect to support OIDC enabled CAS system.

BioCollect test URL - https://biocollect-test.ala.org.au/acsa
Test Software version - 6.3-API-SNAPSHOT

https://confluence.csiro.au/display/ALASD/Biocollect+Functional+UI+Testing

**Comment by temi** [comment]
https://github.com/AtlasOfLivingAustralia/ecodata-client-plugin/pull/137
https://github.com/AtlasOfLivingAustralia/biocollect/pull/1415

**Comment by TaniaGLaity** [comment]
Worked through testing doc as far as possible - happy to retest when able to login
[Biocollect Functional UI Testing.docx](https://github.com/AtlasOfLivingAustralia/biocollect/files/9357239/Biocollect.Functional.UI.Testing.docx)
