### ISSUE TITLE
Project Draft/ Publish status change

### ISSUE THREAD

**Issue by chamaliperera512** [AtlasOfLivingAustralia/biocollect#1419]
Setting Project Status in BioCollect Projects 
 
Background 
Currently in BioCollect Production environment, there are projects created by clients which have been created for testing purposes. This makes it difficult to identify legitimate projects. 
 
Proposed Solution 
In order to resolve the above issue, a project status field will be introduced, which will help stakeholders to identify and manage draft and published projects. 
Note: A database script will be run to mark the status of all existing projects as ‘Published’, any projects that need to be marked ‘Draft’ will have to be done manually. 
Hence, there will be two statuses for a project 
Draft 
Published 
Draft projects will be visible only to project members and ROLE ALA_ADMIN. Published projects will be publicly visible to all, as is currently the case. 
 
Project Creation page changes 
A ‘Save & Publish’ button will be made available at the bottom of the project creation page to publish a project. 
 
A text will be shown at the top right of project creation page to inform the user about Draft/ Publish statuses. Text to be provided by Peter. 
When a user tries to create a new project, under the Project metadata section, if the user selects ‘No’ to the below question, then the Save & Publish button will be made active. If yes save as Draft using Save changes button. 
A user can save as Draft if isExternal = false and by hitting Save changes button 
 
 
Edit Project page changes 
If ‘Yes’ was selected to the above question, the Publish button will be disabled unless at least one published survey exists. Ie. if the “isExternal” flag = true and the project contains at least one survey with published status = true, then the projectPublish button should be active. 
The projectPublish button should function as a toggle switch to allow “publishing” and “unpublish” of projects. 
 
Survey creation page changes  
If a user selected ‘Yes’ in the above step (with the intention of not wanting to publish the project until at least one survey is created), once they are in the survey creation page, they will have the ability to publish the project along with the survey. To facilitate the same, at the last step of survey creation, user will have the option to select whether to publish the project along with the survey as below.  
 
 
Should also include some explanatory text with this Boolean selector along the lines of:  
“Publishing the project will make it publicly visible.  
Before publishing, please ensure that the project information properly describes the project for intended audiences, that you have added appropriate logo and banner images and that the defined project area accurately reflects the spatial area in which the project is being undertaken.” 
This text should also be included on the project metadata template adjacent to the publish button. 
 
Hub search index changes

**Comment by temi** [comment]
released in 6.1
