### ISSUE TITLE
Document should be created even though they do not have file

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1432]
Certain documents with role like Journal Article cannot be upload since the do not have a file attachment. Should enable document creation for special cases like this.

**Comment by chamaliperera512** [comment]
This has been completed in feature/nespDocumentEnhancements branch

**Comment by chamaliperera512** [comment]
Completed in https://github.com/AtlasOfLivingAustralia/biocollect/pull/1444 PR

**Comment by temi** [comment]
passed
