### ISSUE TITLE
Show centroid lat/ long in extracted data sheet

### ISSUE THREAD

**Issue by chamaliperera512** [AtlasOfLivingAustralia/biocollect#1433]
This issue was originally reported by a client.

When polygons are used to define the location, the extracted data sheet does not show the centroid lat/long values.

Hence we need to add two new columns called 'Centroid Latitude' ad 'Centroid Longitude' while keeping the existing Latitude and Longitude columns.

-------------------------------------------------------------------
From: Kade Mills <[kade@vnpa.org.au](mailto:kade@vnpa.org.au)> 
Sent: Friday, 1 July 2022 12:00 PM
To: [support@ala.org.au](mailto:support@ala.org.au)
Cc: Brenton, Peter (NCMI, Black Mountain) <[Peter.Brenton@csiro.au](mailto:Peter.Brenton@csiro.au)>
Subject: Extracted data not showing Location
 
Hi,
 
I am the admin for the Victorian National Parks Association ReefWatch project on Biocollect.
I downloaded data from the project for the years 2021 &2022 (attached here)
The location data is not on the downloaded spreadsheet, yet it is on the online data page. Hopefully this is a quick fix on your end.
Cheers,
Kade
If you need clarification please give me a call on 0407 363 719
 
Kade Mills (he/him)
ReefWatch Coordinator
Mon, Wed, Thu and Fri
VICTORIAN NATIONAL PARKS ASSOCIATION
Level 3, 60 Leicester St, Carlton Vic 3053
T: 0407 363 719
[www.vnpa.org.au](http://www.vnpa.org.au/)
Join us on [Facebook](http://www.facebook.com/pages/Victorian-National-Parks-Association/121782438413) or [Twitter](https://twitter.com/vnpatweets)
 
The Victorian National Parks Association acknowledges the many First Peoples of the area now known as Victoria, honours their continuing connection to, and caring for, Country, and supports Traditional Owner joint-management of parks and public land for conservation of natural and cultural heritage.
 
Our office is located on traditional land of the Wurundjeri people of the Kulin Nation. We offer our respect to Elders past, present and future.

**Comment by chamaliperera512** [comment]
Completed in https://github.com/AtlasOfLivingAustralia/biocollect/pull/1444

**Comment by temi** [comment]
done
