### ISSUE TITLE
Usability feedback - Integrate biocollect search index with main ALA index

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#146]
Users tend to try searching for citizen science projects in the main ALA search feature, but it does not look-up the biocollect search index and expected results are not returned. This results in user confusion.

ALA's search should lookup all indexes, including associated/integrated apps such as biocollect.Some work may be required on the ALA search results page to display context/provenance of search results and perhaps provide a means of filtering by that too.

Specific apps should continue to include their own search features, but what is being searched should be made clear - ie. "search in biocollect", "search the whole Atlas", etc.

**Comment by pbrenton** [comment]
This needs to be done in conjunction with Nick  and Dave.

**Comment by temi** [comment]
further investigation needed when this issue is reached

**Comment by sat01a** [comment]
Completed as part of #397
