### ISSUE TITLE
Records created using the wrong name

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1467]
BioCollect record generation is not using the correct scientific name & common name. Some time it uses a combination of scientific and common name. Correct the record generation logic to used scientific name or common name not both.

Attached is a list of all of the raw species names in BioCollect that are excluded from the default view by the data quality profile for taxon issues. There are over  45K record impacted by this problem.
[data (34).csv](https://github.com/AtlasOfLivingAustralia/biocollect/files/9486666/data.34.csv)

**Comment by temi** [comment]
1. [GO TO](https://biocollect-staging.ala.org.au/bioActivity/projectRecords/8c3ae3b1-5342-40b4-9e72-e9820b7a9550?hub=acsa)
2. Filter results by scientific name `Short-beaked Echidna (Tachyglossus aculeatus)`
3. Filter by another facet to reduce records to around 10 records
4. Download records
5. Go to `DwC records` sheet
6. Is scientific name column have mixed name?

**Comment by yasima-csiro** [comment]
Could not test this. Download functionality didn't work properly.


<img width="537" alt="image" src="https://user-images.githubusercontent.com/72474143/200199173-cda1a2af-4ed1-4567-867b-70b45f790447.png">
<img width="1574" alt="image" src="https://user-images.githubusercontent.com/72474143/200199220-5f5a8c69-ee3a-4e97-ae52-6e0f17a9b011.png">

**Comment by temi** [comment]
reporting server was down. it is now fixed.

**Comment by yasima-csiro** [comment]
Thanks Temi.

Tested and passed.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/72474143/200697764-ef150d61-47b5-4990-9f76-eb6369120e9e.png">
