### ISSUE TITLE
Download XLSX column formatting should be based on data type

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1468]
Currently certain fields like date and number in CoralWatch Project are not formatted based on data type. Check email from Diana for more in depth analysis of the problem.

**Comment by temi** [comment]
1. Download coral watch project data
2. Check `Observation date`. Should be of format `8-May-21`.
3. Check `Average.` column. Should recognise as number i.e. no green coloured triangle on top left of cell .

**Comment by yasima-csiro** [comment]
Tested and passed.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/72474143/200218062-f0d0eecf-dd97-4dec-8287-744344d5e9f3.png">
