### ISSUE TITLE
Cannot view word, spread sheet on resources list page

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1474]
Previewing a word document from [imsa resource page](https://biocollect.ala.org.au/imsa/resource/list) does not work. But it works when viewed from the project. Most likely missing a URL.

**Comment by temi** [comment]
1. [Go to](https://biocollect-staging.ala.org.au/imsa/resource/list)
2. preview word
3. should not show an error

**Comment by yasima-csiro** [comment]
Tested and passed.

<img width="1736" alt="image" src="https://user-images.githubusercontent.com/72474143/200199659-44f726b5-714f-4abc-815b-0b492569e10b.png">
