### ISSUE TITLE
Cannot publish external projects

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1476]
Current code in Project controller
```
if ((values.projLifecycleStatus == 'published') && values.isExternal && !hasPublishedProjectActivities) {
                    render status: HttpStatus.SC_BAD_REQUEST, text: "At least one published survey should be there to publish a project."
                    return
                }
```

Actual 

should check for `isExternal == false`

**Comment by temi** [comment]
1. Create a project with 
2. Answer `No` for question `Do you want to record your project data on this site?`
3. Click `Save & publish`
4. Should publish project. Currently gives error `At least one published survey should be there to publish a project.`

**Comment by yasima-csiro** [comment]
Tested and passed.
