### ISSUE TITLE
Add dashboard charts to graph biocollect entities

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1478]

**Comment by temi** [comment]
1. [go to](https://biocollect-staging.ala.org.au/biocollect-all/report/chartList)
2. Can you see chart on projects, activities and records? can take some time for first load.

**Comment by temi** [comment]
All except project charts are okay. Will fix that soon.

**Comment by yasima-csiro** [comment]
Still cannot see projects charts after reindexing.

**Comment by temi** [comment]
It is appearing now. Cache was displaying an old result.

**Comment by yasima-csiro** [comment]
Thanks Temi.

Tested and passed.

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/72474143/200696313-0de61591-feef-4eb3-b428-87d970b61176.png">
