### ISSUE TITLE
Images missing from download

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1479]
https://support.ehelp.edu.au/a/tickets/158784

Actual:
Images have notfound extension.
Reporting server does not have images stored locally. Need to change logic to retrieve it from biocollect.

**Comment by yasima-csiro** [comment]
Could not test. Download functionality is not working properly.

**Comment by temi** [comment]
reporting server is working again

**Comment by yasima-csiro** [comment]
Thanks Temi.

I searched for Short-beaked Echidna in 2017 and it seems all the records have images. But I don't see all images in the download.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/72474143/200699749-f9481889-086a-459d-bb73-ac9dbe21c35f.png">
<img width="598" alt="image" src="https://user-images.githubusercontent.com/72474143/200699928-12f6744b-6edc-434e-8978-299a39448a89.png">

**Comment by temi** [comment]
@yasima-csiro All those images are coming from image server. unfortunately, not all of them have images on ecodata. this issues deals with getting images from ecodata.

**Comment by yasima-csiro** [comment]
Thanks Temi. In that case, it can be said the issue has fixed now.
