### ISSUE TITLE
BioCollect Home page - Usability feedback - Add a prominent button on the ALA CS landing page to create/register a project from there.

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#148]
Users need to be able to action key biocollect use cases such as "browse projects", create/register a project", "View my data", etc. directly from the wordpress CS landing page. Navigationg to the project finder, as the entry point to biocollect, is not intuitive enough.

**Comment by pbrenton** [comment]
URL to test page     http://www.ala.org.au/biocollect-test/?preview=true&preview_id=34512&preview_nonce=8555e8e6a6

URL to production page     http://www.ala.org.au/biocollect/?preview=true&preview_id=35428&preview_nonce=aa19a4c89d#tab1

**Comment by m-r-c** [comment]
Done.

This required changes to ansible inventories and ala-install.
