### ISSUE TITLE
Improve project page speed

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1480]
Project page is currently very slow. This is causing it and BioCollect system to have high bounce rate. Reduce the load time of the page.

**Comment by temi** [comment]
1. Go to https://biocollect-staging.ala.org.au/acsa/project/index/f813c99c-1a1d-4096-8eeb-cbc40e321101
2. project should take less than 10 seconds to load. Currently it takes around a minute.

**Comment by yasima-csiro** [comment]
Tested and passed.
