### ISSUE TITLE
Bug with project activity embargoed feature

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1482]
REindexing embargo's an activity even if ProjectActivity config is set to public. 
Steps to reproduce
1. Set "Embargo publishing all records until" to a future date and save.
2. Set "Records publicly visible on submission" and save.
3. Index an activity associated with PA
4. Activity appears as embargoed.

Issue

```
private Map prepareActivityForIndexing(Map activity, version = null) {
...
(activity.embargoed == true) || (pActivity?.visibility?.embargoUntil && pActivity?.visibility?.embargoUntil.after(new Date()))
```
The above code does not check embargo option.

**Comment by temi** [comment]
Use steps above

**Comment by yasima-csiro** [comment]
Tested and it seems the issue is fixed. Not sure reindexing was successful.
