### ISSUE TITLE
Dynamic Indexes are not being created

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1483]
Previously, dynamic indexes could be created on a data model. This is not working at the moment. The issue is mapping is created at startup and not updated after that.

**Comment by temi** [comment]
1. Go to coral watch [form template](https://ecodata-test.ala.org.au/admin/editActivityFormTemplates)
2. Add an indexName to a data type
3. Reindex all 
4. Go to Biocollect and clear metadata cache
5. Add created index to facet list of all records page
6. View all records page and see if facet appears

**Comment by yasima-csiro** [comment]
Added a new index and facet. But could not see the facet in the all records page.

https://biocollect-test.ala.org.au/coralwatch/bioActivity/allRecords?hub=coralwatch

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/72474143/200675475-5ac511ee-42d8-412d-b48f-8d847636be33.png">
<img width="761" alt="image" src="https://user-images.githubusercontent.com/72474143/200675542-14f3eb27-e8d0-4bec-aced-cd3af0e7e5c9.png">

**Comment by yasima-csiro** [comment]
Thanks Temi.

Tested and passed.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/72474143/200724700-887d6db0-6c7a-42ab-a3d6-47de5eb9224b.png">
