### ISSUE TITLE
API get bioactivity data throwing JSON convertion error

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1486]
using /ws/bioactivity/data/{id

```
"mapFeatures": {<!DOCTYPE html>
<html>
<head>
  <title>Error</title>
  <meta name="layout" content="bs4">
  <meta name="breadcrumb" content="Error"/>
  <link rel="stylesheet" href="/assets/errors-c6286931f24bfad411779451f7272efc.css" type="text/css">
</head>
 
<body>
<div id="wrapper" class="container-fluid">
  
      <ul class="errors">
          <li>An error has occurred</li>
      </ul>
  
</div>
</body>
</html>
```

**Comment by temi** [comment]
To test -> 

/ws/bioactivity/data/2c07e744-b099-4d03-a2bc-9e75c8952c4a

**Comment by yasima-csiro** [comment]
Tested and passed below.

GET https://biocollect-test.ala.org.au/ws/bioactivity/data/154c278b-27d1-4806-a96f-acf93bf00385
GET https://apis.test.ala.org.au/biocollect/ws/bioactivity/data/154c278b-27d1-4806-a96f-acf93bf00385

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/72474143/200197038-8af4a929-8c5a-4475-8601-2afe1dee73a4.png">
