### ISSUE TITLE
Add an API to create site

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1487]

**Comment by temi** [comment]
Create or edit a site
GET
/ws/bioactivity/site

```
{"pActivityId":"d57961a1-517d-42f2-8446-c373c0c59579","site":{"name":"Private site for survey: Individual sighting","visibility":"private","projects":["b3d8e243-1137-4d26-9e15-c5a6f90815eb"],"extent":{"geometry":{"centre":[144.755859375,-37.47921744485059],"type":"Point","areaKmSq":0,"coordinates":[144.755859375,-37.47921744485059]},"source":"Point"},"asyncUpdate":true}}
```

**Comment by yasima-csiro** [comment]
Tested and passed.

GET https://biocollect-test.ala.org.au/ws/bioactivity/site
GET https://apis.test.ala.org.au/biocollect/ws/bioactivity/site

<img width="935" alt="image" src="https://user-images.githubusercontent.com/72474143/200198869-649268fd-2458-4282-8882-d30b1d23f991.png">
