### ISSUE TITLE
Add API to query surveys or project activities

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1494]
1. should be able to query like `project area falls within NSW AND isCitizenScience=true AND isExternal=false AND activityRecord count>10 AND embargoed=false`.
2. Add a metadata field in project where you can assess whether a project has data.

**Comment by temi** [comment]
## steps to test
1. Go to [api gateway](https://docs.test.ala.org.au/openapi/index.html?urls.primaryName=surveys#/biocollect/projectsearch)
2. Try the project search
3. Add value to fq parameter - `containsActivity:true`
4. Run query
5. Get name of project and check on biocollect test that project has data.

**Comment by pbrenton** [comment]
I got an unauthorised response.

**Comment by temi** [comment]
Communicated with Rebekah.
