### ISSUE TITLE
Download file is large

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1499]
Download file in BC is too large due to full size image being added to it.

**Comment by temi** [comment]
## Steps to test
1. Go to [all records page on staging](https://biocollect-staging.ala.org.au/biocollect-all/bioActivity/allRecords)
2. Filter records to around 200 and make sure these records have images
3. Download these records. Make sure the download is an async download i.e. BC sends an email with link.
4. Make sure all images starts with thumb_*
5. You can do the same query on production. It is likely that images might not appear due to a bug fixed now.

**Comment by pbrenton** [comment]
Download file did not arrive in my inbox or junk mail
