### ISSUE TITLE
Project Finder - map search

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#15]
Add a spatial search capability to the Citizen Science Project Finder which behaves in the same way as the "explore your area" tool, returning a set of projects which have project extents which either intersect with or are wholely enclosed within the spatial scope of the specified search area. 

Specific capabilities to include:
* Allow address search as centroid
* Allow drag 'n' drop map marker as centroid
* Allow device location as centroid marker
* Allow radius selection (default = 100km)
* Allow search by gazetteer location. Ie. open streetmaps API based gazetteer lookup to retrieve polygon as filter scope - http://www.objectcult.com/maps/osm_demo.html

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-26

**Comment by m-r-c** [comment]
To test this, you will need to edit and save all of your project's - you do not need to change anything, just trigger a save so that the index is updated with the new data structure.
