### ISSUE TITLE
collectory id missing from project

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1509]
Investigate why collectory druid were not created for below projects. These resources were created in collectory. Also check how many such instances exists.
![image](https://user-images.githubusercontent.com/1152259/217392140-d6681e60-6d3d-4c2f-9b06-e648bf7f0df1.png)

**Comment by temi** [comment]
more projects
[MissingDataResourcesInProd.txt](https://github.com/AtlasOfLivingAustralia/biocollect/files/11503326/MissingDataResourcesInProd.txt)

**Comment by peggynewman** [comment]
Most of these have duplicate data resources in the [BioCollect data provider listing in the collectory (dp3903)](https://collections.ala.org.au/public/show/dp3903).
I think you'll find these missing data resources in this extract (there are 53 Biocollect data resources that deliver data to the ALA).
It would be great if we could clean up the duplicates and empties that don't need to be there. 

[biocollect-202304.csv](https://github.com/AtlasOfLivingAustralia/biocollect/files/11527023/biocollect-202304.csv)

**Comment by temi** [comment]
Test for duplicate entires
1. Go to data resource tab on Collectory for BioCollect - https://collections-test.ala.org.au/public/show/dp3903
2. Go to NESP project 1 on BioCollect - https://biocollect-test.ala.org.au/acsa/project/index/9c2fabff-6d37-47bb-aaba-c3bc11e2b7ca. This project does not exist on Collectory.
3.  Switch on the ALA harvest flag.
4. Refresh collectory page and check for project entry (NESP project 1).
5. Go back to BioCollect and turn off and turn on the harvest flag.
6. Repeat Step 4. There should only be one entry for the project.

**Comment by pbrenton** [comment]
Testing completed satisfactorily, no issues

**Comment by jack-brinkman** [comment]
Testing completed, issue seems to be resolved
