### ISSUE TITLE
Usability feedback - Add an icon to indicate all external links

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#155]
Links to external sites and queues to users that they are leaving biocollect to an external site are not obvious, but should be.

**Comment by m-r-c** [comment]
Something like this should work:

JS:
```
var currentDomain = document.location.protocol + '//' + document.location.hostname;
$('a[href^="http"]:not([href*="' + currentDomain + '"])').addClass('external-link');
```
Might need to change the condition to match anything that does not contain ala.org.au, and there could be some timing issues with knockout bindings (this script would have to execute last).

CSS:
```
.external-link:after {
    content: '\f08e';
    font-family: FontAwesome;
    padding-left: 5px;
    font-size: 10px;
    vertical-align: super;
}
```

**Comment by m-r-c** [comment]
The above JS is unnecessary: we can just use straight css and avoid all the knockout timing issues.

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-70

**Comment by pbrenton** [comment]
I think we need to work through the usage rules and whee it is applied before we push this to prod. It is currently appearing in far too many places, certainly more than was intended.

**Comment by m-r-c** [comment]
As discussed, I have changed the criteria to match links where the domain does not contain ala.org.au.
