### ISSUE TITLE
ACSA hub not routing correctly on production

### ISSUE THREAD

**Issue by jack-brinkman** [AtlasOfLivingAustralia/biocollect#1553]
Navigating to [/acsa](https://biocollect.ala.org.au/acsa) displays a `Page not found` error. The home page is still accessible at [/acsa/home/index](https://biocollect.ala.org.au/acsa/home/index), however.

This is not the case with staging ([/acsa](https://biocollect-staging.ala.org.au/acsa)).

**Comment by temi** [comment]
This was fixed by restarting the app. It is funny problem. Need further investigation.
