### ISSUE TITLE
Project map is not displaying on the "about" page when user not logged in

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#157]
2 issues, probably related:
1) When the user id not logged in the project exent map does not display at all
2) when user is logged in the map panel displays, but seems to zoom to some area which is not the mapped project extent. This is true for 2 projects have extent defined as a known shape. Other extent definitions not yet tested.

Project extend map should zoom to the defined extent and should always display whether logged in or not.

**Comment by m-r-c** [comment]
Should be fixed now
