### ISSUE TITLE
A single species survey with species as a mandatory field should auto-populate the species in the survey form

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#162]

**Comment by sat01a** [comment]
PR #224
PR #147

**Comment by m-r-c** [comment]
This doesn't work on the Single Sighting form. Because it is using the Sightings plugin, the logic for prepopulating it is different. 

Also, did you need to do something wrt to uploads?

**Comment by sat01a** [comment]
Updated the code to handle both single species and bulk upload scenarios.
PR https://github.com/AtlasOfLivingAustralia/biocollect/pull/245
