### ISSUE TITLE
Restoration NSW "pixelated" shape file

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1627]
Recent change to spatial portal has truncated lat/lng decimal precision. This is causing shape file download to be "pixelated". See example below.

**Comment by salomon-j** [comment]
The code fix is good to go, tested/compared staging and production shapefiles.

Before fix:(prod shapefile)
<img width="580" alt="Screenshot 2024-10-01 at 9 58 51 am" src="https://github.com/user-attachments/assets/abbce31f-3aed-4320-9470-7ac260c62fac">

After fix:(staging shapefile)
<img width="580" alt="Screenshot 2024-10-01 at 9 58 51 am" src="https://github.com/user-attachments/assets/64f5bc80-838c-472b-a721-6fdd2bb664f9">
