### ISSUE TITLE
API to fetch data is slow

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1644]
API `/ws/bioactivity/data/` is very slow and makes too many request. Check if this API can be simplified or create a new one such that security, response time and size of download are the top considerations.

**Comment by salomon-j** [comment]
this is now created in the API gateway:
https://docs.test.ala.org.au/openapi/index.html?urls.primaryName=surveys#/biocollect/simplifiedactivityoutputs_1

**Comment by salomon-j** [comment]
this is now created in the prod API gateway
https://docs.ala.org.au/openapi/index.html?urls.primaryName=surveys#/biocollect
