### ISSUE TITLE
Prevent userId update on Activity and Record

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#168]
Prevent ALA_DMIN or Project Admin overwriting userId field in Activity & Record

**Comment by m-r-c** [comment]
Should the userId ever be updated once the Record/Activity was created?

**Comment by sat01a** [comment]
No

**Comment by sat01a** [comment]
ecodata PR > https://github.com/AtlasOfLivingAustralia/ecodata/pull/145
