### ISSUE TITLE
Add more "regions" as an available options in "Known shapes" selection for site creation

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#169]
There are several use cases which are dependent upon being able to create region-based site extents which defined in layers other than those currently available in the limited known shape select feature when creating sites, the most immediate being the MDBA region, but there are many others too.

The list of available known shape selections should be the same as available facets in the regions app.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-63
