### ISSUE TITLE
Add/remove "communities of interest to projects

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#17]
Add a "Communities of interest" (0:many) selector to project access tab. This should automatically provide 'Editor' role in projects to members of 'communities of interest' which are linked to projects. However it should not expand the community as individual members of the project - ie. the community is a member of the project and it's members inherit "editor" level access to the project by virtue of their membership to the community.

Dependent on a "Communities" tool and associated APIs being developed (issue #30 )

Rules:
If a member of a project has a role in that project which affords higher permissions than "editor" and that person is also a member of a community of interest attached to project membership, then the higher role applies.

**Comment by matilda2812** [comment]
Closing as no longer relevant.
