### ISSUE TITLE
Project finder home page - Change header, search and filter block

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#179]
Usability feedback indicated significant issues with search, sort and filter behaviour, some of which have already been addressed in other tickets. This change makes the header section of the project finder home page:
* more consistent with the design model of the rest of the ALA, 
* more clearly differentiates the project search feature, 
* visually removes the competing ALA search in the header bar, 
* moves project display number and sortBy selectors to a more appropriate screen position, and 
* collapses minor filter criteria to a user selected expandable section.

Concept design attached. This has had some comments/suggestion for minor adjustment too.

![biocollect - project finder v2 0](https://cloud.githubusercontent.com/assets/8119351/10871868/d603ac06-8147-11e5-98df-bbb9033dba47.jpg)

**Comment by pbrenton** [comment]
associated issue #2

**Comment by temi** [comment]
all changes are in the branch https://github.com/AtlasOfLivingAustralia/biocollect/commits/projectFinder.
i could not make a pull request.

**Comment by m-r-c** [comment]
Looks great.

Some suggestions for the layout:
1. Move the buttons (all or perhaps everything except Home and Search) in the header to the right (leave the ALA logo on the left), so the blank space is between the logo and the buttons - I think this will balance the header out a bit.
1. Increase the length of the search field (maybe 500px?). The current css is only setting the min and max widths, not the actual width, so it's showing up as only 236px.
1. Toggle the caret on the Filter button when the panel is opened/closed. The green border when it's selected doesn't look good with the red button.
1. Increase the width of the middle column so the text doesn't wrap until just before the status indicator (at the moment there is a lot of white space between the project description and the status).
1. The logo box doesn't look quite right - maybe try just removing the 'well' class from the surrounding div.
1. Make the banner a bit shorter.

**Comment by pbrenton** [comment]
I agree with Mark's suggestions.

**Comment by temi** [comment]
done

**Comment by sat01a** [comment]
![menu](https://cloud.githubusercontent.com/assets/4197871/11080343/e0b5cb2c-8866-11e5-8de8-025f056e972e.png)
Please check whether above dropdown issue happens on your browser.

**Comment by temi** [comment]
the issue captured in #227
