### ISSUE TITLE
Project finder - Add selected search and filter criteria to URL

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#180]
Need to provide URL-based pre-filtered views of project finder projects to enable theme-based (eg. koala) aggregated views from theme-based pages, API-based delivery of results to external them-based resource pages, and the ability to send a pre-filtered query URL to enquiries over email.

**Comment by pbrenton** [comment]
Associated issue #1

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-15
