### ISSUE TITLE
Hide "Add record" button for "Ended" surveys

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#183]
Users should not be able to continue adding records to surveys which have "ended". Suggest to hide the "Add record" button if today's date > the the survey end date.

**Comment by m-r-c** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/pull/193

**Comment by sat01a** [comment]
For the above scenario, can we also redirect "Add Record" url (biocollect/bioActivity/create/240f3080-38cd-4441-8df4-0b92d41378c7)
to 
"View Record" (/biocollect/bioActivity/index/0ebc4d43-2ccb-41c5-9be5 8a4be19eda20) url ?

**Comment by m-r-c** [comment]
The add link on the surveys and records tabs shouldn't be visible.

**Comment by m-r-c** [comment]
Added error and redirect when trying to navigate to the create page for a closed survey.

PR: https://github.com/AtlasOfLivingAustralia/biocollect/pull/205
