### ISSUE TITLE
Add a search feature for species list search

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#185]
There is currently no search feature on the species list look-up for survey configuration. This makes finding and selecting from existing lists very hard and cumbersome

**Comment by m-r-c** [comment]
This is done, but it requires a fix to Species List to be deployed before it will work.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-12

**Comment by m-r-c** [comment]
The Species List change has been deployed to production.
