### ISSUE TITLE
'Privacy Declaration' needs descriptive text

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#187]
When adding/editing resources via the Admin tab, there is a checkbox labelled "Privacy Declaration" with no explanatory text.

**Comment by pbrenton** [comment]
This was a requirement of DoE to ensure that whoever was loading an image or video and wanting to make it public would have to declare that all 3rd parties in the video or image had given their consent for it to be in the public domain. It is only presented if the user checks the box to make the resource public.

I think this is still valid and important to cover us too.

**Comment by chrisala** [comment]
The contents of the declaration test is editable via the "Static pages" section in the Administration section.
The text for MERIT isn't appropriate for BioCollect so we'll need to draft something else.

**Comment by chrisala** [comment]
So there is something displayed, I've included some text - it needs review.
