### ISSUE TITLE
"Attach a document" dialog does not remove files when clicking Change or Remove buttons

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#188]
1. Admin tab
1. Resources
1. Attach a document
1. Select an image
1. Click Change file
1. Select a different image
-> There are now 2 images displayed.

Repeat, but select remove instead of change -> still have multiple files.

**Comment by chrisala** [comment]
PR https://github.com/AtlasOfLivingAustralia/biocollect/pull/217

**Comment by sat01a** [comment]
Does the "use as the main project image" applicable to biocollect?

**Comment by chrisala** [comment]
Good question - what is currently used to determine the image on the about tab?  The  original idea was to make that a carousel of all of the main images but I don't think that is the case any more.

**Comment by sat01a** [comment]
Looks like about tab uses mainImageUrl uploaded via Project creation page. For now we don't need "use as the main project image"  in the document upload section.

**Comment by sat01a** [comment]
I will create a seperate ticket and will close this ticket.
