### ISSUE TITLE
Add organisation configuration option - Allow project admins to optionally allow survey data to be embargoed indefinitely

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#189]
Projects raised by some organisations need to have more control over the duration of an embargo on their data at a survey-by-survey level (eg. indigenous groups need to be able to collect data in a common tool, but to control the sharing of the data)

Suggested solution: 
1) add ALA_ADMIN only config option on organisation pages to "optionally allow indefinite embargo on survey data"
2) add a checkbox to the survey config visibility tab to allow PROJECT_ADMINS to optionally embargo survey data indefinitely.

**Comment by temi** [comment]
The ALA_ADMIN option to enable the option on the surveys should be on the project admin section (rather than the organisation admin section)

**Comment by matilda2812** [comment]
@pbrenton is this still applicable given this can be done in surveys?

**Comment by pbrenton** [comment]
This issue addresses a config deficiency which, paradoxically, is preventing some parties from sharing their data with the ALA.

The ticket was included as a requirement to support very specific cases (eg. Indigenous cultural requirements) where certain data should remain embargoed indefinitely if there is a legitimate reason for doing so, but allows custodians to release manually. It essentially disables the auto-sunset on data embargoes. The default position should remain that embargoes should sunset and data be released, but there are some cases where this is not appropriate. 

This feature would allow ALA admins to enable "organisation admin" role to set a flag on individual project surveys/activities (eg. as an additional visibility option). Indefinite embargo would then be the default rather than sunsetted embargo. Permitted users can still release individual records manually as per current practice.

**Comment by temi** [comment]
Closing since this feature exists.
