### ISSUE TITLE
Add hub configuration option - Hub list, search, select & edit page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#190]
Create an ALA_ADMIN page to search and list BioCollect hubs and to access ad/edit functions for hub creation and configuration.

**Comment by temi** [comment]
add drop down list to the field where hub name is entered. And an add button to create a new hub.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-103
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-35

**Comment by chrisala** [comment]
Note that this change requires a data migration to work correctly. 
cd <ecodata project>/scripts/data_migration
mongo ecodata migrateHubSettings.js
