### ISSUE TITLE
Add hub configuration option - Add more facet selection options

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#192]
Facet options for selection need to dynamically update to match facets available in at least the ALA Regions tool.

This requirement is increasing as more organisations are seeking hubs. 

eg. MDBA needs a hub with a geographic constraint to the Murray-Darling Basin area. This has been added to the Regions facets, but is not yet available in BioCollect. 
PM&C and ILC are seeking hubs with spatial constraints around certain indigenous layers.
more requests are likely.

**Comment by temi** [comment]
add the murray darling basin boundary layer to the ecodata facet config.

**Comment by pbrenton** [comment]
Also see #852
