### ISSUE TITLE
Map sometimes not displaying correctly on project pages

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#194]
Sometimes the project extent is not displaying correctly on the project "About" page. This appears to be ab intermittent problem and I have noticed it on several projects.

Eg. http://biocollect-test.ala.org.au/project/index/10ec7361-30f9-4ce8-bf88-a57e49f9e7d6

![download 20](https://cloud.githubusercontent.com/assets/8119351/10899117/a6b99b66-8225-11e5-8b22-8ebabfa5a7bc.png)

**Comment by chrisala** [comment]
For WMS layers (e.g known shapes), the zoom to bounds call was being made before the call to the spatial portal / GeoServer was made to determine the site bounds.

PR: https://github.com/AtlasOfLivingAustralia/biocollect/pull/221
