### ISSUE TITLE
Associated organisations - can't add images or URL from project metadata page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#195]
Needs a button alongside associated organisations to open the organisation page to add image and url to the org page.

**Comment by m-r-c** [comment]
Add discussed with Peter, the user should not be able to modify another organisation.  

I have added some descriptive text to highlight the difference between this section and the similar organisation name section.

Biocollect PR: https://github.com/AtlasOfLivingAustralia/biocollect/pull/202
