### ISSUE TITLE
Associated organisations - presentation on about page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#196]
Ideally associated organisation  would display in their own section as a grid of icons (3 or 4 across and n down) with the org name displayed as alt-text on-hover and link to associated URL on-click.

The associated organisation section should be able to float between the left and right columns based on optimum fit.

**Comment by m-r-c** [comment]
Discussed with Peter: The user should not be able to modify the logo/url for another organisation, so a button is not required. We do, however, need to add some descriptive text to explain why this is different to the fields for the organisation running the project.

**Comment by m-r-c** [comment]
PR: https://github.com/AtlasOfLivingAustralia/biocollect/pull/207
