### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#208]
From testing done under #110:

In general, the site works, but looks horrible.

The only thing that was actually broken was the auto complete feature in the Users tab on the admin screen.

---

Testing with Chrome's mobile emulator, using Samsung Galaxy S4 device.

General:

1. Not enough (or no) padding around the edges of the screen
1. Validation tool tips appear off the side of the screen
1. Maps: if the map takes up the whole screen, then you can't move past it since all gestures manipulate the map

Home page:

1. Search field is not wide enough
1. Download button is full screen width
1. Project name & text, logo image, and status are in 3 columns and requires horizontal scrolling: they should be in 1 column on small screens (i.e. logo, then name, then text, then status one above the other).
1. Grey background in the footer cuts off at 'Atlas Features'
1. When expanding the "More" menu, the Administration button drops down a row
1. Home, About, Info, Contacts menu items are not visible when the header has been expanded.

Administration page:
Users tab

  1. The caret icon on the Project field is below the field - should be attached to the end of it
  1. The autocomplete feature is broken: causes a page reload, requires horizontal scrolling (if the popup appears), seems to break as soon as the 2nd character is typed)

Static Pages tab

  1. Table width is too wide, requires horizontal scrolling to see the buttons
  1. Edit text -> the rich text editor toolbar does not display correctly

New Project page:

1. Organisation name field is too narrow

Project View page:

1. Layout of the title, image, status indicator is not right
1. Resources tab layout is not right for mobile: the document viewer is a narrow column on the right, the download buttons are ~1/3 the width of the screen - need to test this with multiple media types, too (e.g. video causes the viewer panel to resize and partially overlap the table)
1. Surveys tab: the layout of the logo, title, status and button is not right
1. Admin tab:
  1. Survey config tab:
    1. Labels are displayed on the right hand side of the screen, input fields on the next line and left aligned.
    1. Next/previous need to scroll to the top of the tabbed panel
    1. Visibility tab: the days dropdown is too narrow - 3 digit numbers are not displayed
    1. Species tab: Autocomplete fields don't always work (spinner appears but the popup does not...sometimes)
    1. Locations tab: layout does not work for mobile - can't rely on side by side columns like this
  1. Resources tab: 
    1. layout isn't right - download button is full width, icon is too small, remove and edit buttons are in the wrong place.
    1. the Attach a Document dialog doesn't work properly: cannot select the Image settings checkbox because tapping anywhere near it triggers the file upload dialog.
  1. Members tab: when editing a row, the inline drop down increases the table width and requires horizontal scrolling

My Data page

1. Position of the items per page dropdown and the page controls isn't right

Survey forms

1. The table component causes horizontal scrolling

**Comment by pbrenton** [comment]
Need to break this into separate issues.

**Comment by temi** [comment]
Biocollect home filter button is not rendered in the page.

**Comment by javier-molina** [comment]
General:
1. Not enough (or no) padding around the edges of the screen

Not addressed. medium effort - low value 

2. Validation tool tips appear off the side of the screen 

jQuery.validationEngine only allows tooltips to display error messages. 
If moving the tooltip to the left, (regardless of vertical position) the tooltips will get in the way of other fields which makes screens messy. See image below

My advice is to leave this as is and address the issue  as part of a general UI redesign or Mobile specific design.

![image](https://cloud.githubusercontent.com/assets/8326394/13066177/9f3bc74e-d4b7-11e5-9765-c321ecd78ad4.png)


Home page:

1. Search field is not wide enough
Search and Filter buttons now flow to the bottom on a small screen

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-111
