### ISSUE TITLE
Non admin and owner of an activity cannot edit the activity page.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#211]

**Comment by sat01a** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/pull/212
https://github.com/AtlasOfLivingAustralia/ecodata/pull/146

**Comment by m-r-c** [comment]
Someone who is not the record owner can navigate to the edit page via a direct URL. They cannot submit, but they shouldn't be able to get to the page at all.

**Comment by m-r-c** [comment]
I have fixed this under #100.
