### ISSUE TITLE
Project finder displays "Project Status" label with no value for ongoing projects

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#215]
See ACT & Southern Tablelands Weedspotter project on the front page of http://biocollect-dev.ala.org.au
We should probably hide the label where there is no sensible value to display.

**Comment by temi** [comment]
all changes are in the branch https://github.com/AtlasOfLivingAustralia/biocollect/commits/projectFinder.
i could not make a pull request.
