### ISSUE TITLE
Add email notification to biocollect_support@ala.org.au for new project create

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#223]
We need an alert mechanism to notify us whenever a new project has been created in BioCollect and when project metadata has been edited. Ideally these would be differentiated in the email subject line to facilitate message sorting. Email body should include a link to the relevant project.

This is important to enable us to moderate new projects and monitor usage, appropriateness of projects, project types, etc. and determine where training and improvements may be needed.

Matt Andrews has now created the email address biocollect-support@ala.org.au.

**Comment by m-r-c** [comment]
Code review: https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-5

This change requires updates to ala-install (https://github.com/AtlasOfLivingAustralia/ala-install/commit/bbf56366f5d3d224826db7e4bc46292d44a05a39) and ansible-inventories (https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/3c6b195ebdca133a4b4f55da254f662762cad783)
