### ISSUE TITLE
Vertical height of icon images on survey list page are not scaling correctly

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#233]
The icon image for the red-backed fairy wren (Feathered creatures survey) is scaling  to the full width of the bounding box and keeping aspect ratio, therefore over-sizing the height dimension. This should be scaling the image to max-height or max-width within the bounding box, whilst maintaining the aspect ratio of the image.

**Comment by m-r-c** [comment]
Code review: https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-4

**Comment by temi** [comment]
code review: https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-6
