### ISSUE TITLE
Sites - auto-populate area if the site is a polygon

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#236]
Site area should not be editable and should auto-populate from the defined shape.

Note also that point sites are not currently supported and need to be. Point sites should be treated as a small (2m radius) circular polygon.

**Comment by temi** [comment]
moving point sites to a new issue - #443

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-109
