### ISSUE TITLE
Add tool tips to sites fields missing them

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#237]
Some fields in the sites object are missing tool tips and should have them.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-14

**Comment by temi** [comment]
Peter:

Heading Text     - Site create/edit <h2 size ?>
  A site should represent the smallest area which contains all of the data collected in a single activity or survey event.
  To create or edit a site, please complete at least all mandatory fields (shown with ‘*’).
 
Site name            - The name of the site at which a survey or activity is undertaken. This should be short and uniquely identifiable.
 
Type                      - A categorisation for the type of site being mapped.
 
Description         - A long description of the site. This may include distance and bearing relative to a fixed known location, size, shape, distinctive characteristics, etc.
 
Notes                    - Additional notes about the site such as setting/surroundings, aspect, special/notable features, boundary/corner markers, etc.
 
Change “Extent of site” to “Create a spatial representation of this site”
 
Define extent using        - Select the method you want to use to define the area of the site.
