### ISSUE TITLE
Comments section tweaks

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#241]
Comments section is difficult to see properly on some screens and would benefit from having a border and background color consistent with other output sections.

Also, comment content and comment metadata is displaying with 3 different font styles. Should have one font style consistent with other font on the page - ie. ariel.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-11

**Comment by temi** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/pull/271
