### ISSUE TITLE
Production release prerequisites

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#250]
#106 
Ensure MERIT separated from BioCollect

**Comment by sat01a** [comment]
Checked with Chris, MERIT is tentatively planned for early December release.

1. Biocollect will be sharing ecodata with MERIT, so until MERIT has been released biocollect can't go live. 
2. New feature added to auth to support user role retrieval - Not pushed to prod yet. (Temi is following up with Nick)(https://auth.ala.org.au/userdetails/userDetails/)
