### ISSUE TITLE
Comments causing multiple bindings error when viewing activity

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#265]
Console error: You cannot apply bindings multiple times to the same element.
Steps to reproduce:
1. Uncheck comments allowed field in settings.
2. Publish survey
3. Create a activity
4. View activity
5. Console error: You cannot apply bindings multiple times to the same element.

Example Test Activity:
http://biocollect-test.ala.org.au/bioActivity/index/bafa8ccf-55a5-427a-a8ef-4778137f921c?returnTo=%2Fproject%2Findex%2Feccadc59-2dc5-44df-8aac-da41bcf17ba4

**Comment by temi** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/pull/269

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-9
