### ISSUE TITLE
Data page - map views

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#27]
Build map viewing interface for spatial representation of the type of records selected (ie. survey or occurrence). Design to be consistent with the Biocache map tab, including all associated tools.

Note: Details on what to present and how to present it for each entity type (esp. survey/activity level data) requires further analysis and discussion.

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-5
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-31
