### ISSUE TITLE
'Sites' tab broken on Organisation page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#272]
The sites tab is not working on the organisation page.

~~Previously when this was working it showed sites as only a centroid coordinate marker (dot), but it should be showing the polygons of the spatial extents of all listed projects.~~

**Comment by m-r-c** [comment]
This will be fixed under #293

**Comment by m-r-c** [comment]
Splitting this into two tasks: fixing the site tab (this ticket) and showing the polygon for the sites ().

Showing the polygon for the sites is not currently supported by the Ecodata service used to retrieve the points, so it will be a separate task to #293
