### ISSUE TITLE
Single sighting edit not saving the updated species information.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#274]
Example: http://biocollect-test.ala.org.au/bioActivity/edit/c6c9180c-d464-4bc8-a159-556aaa278a1b?returnTo=%2Fproject%2Findex%2Feccadc59-2dc5-44df-8aac-da41bcf17ba4

Also, createRecordsForOutput fails to save the records
Step 1:  Add records to Fauna Survey 
Step 2:  Submit the records,
Step 3: Edit the records and add new species.
Step 4: Submit the records.
createRecordsForOutput throws an error. Failed to save the new records.

**Comment by m-r-c** [comment]
Fixed:
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-1
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-13
