### ISSUE TITLE
Data page - image gallery view

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#29]
Build an image gallery viewing interface for representation of images attached to "surveys/activities", "records" and "sites". Design to be consistent with the Biocache Record images tab, including all associated tools.

Need to show differentiation between image sets from the different entities.

**Comment by temi** [comment]
Conclusion of discussion with PB and MC
* remove photo points from image tab
* show only record photos

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-78
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-21
