### ISSUE TITLE
Add Indexing message and Overnight Cron job for indexing.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#295]
1. Display following message under survey settings info tab and Visibility tab.
"Changes made to info and visibility tab will be reflected in search results after 24 hours" or something along that line..
2. Show the above message only if we have activities/records.
3. Add a overnight cron job on both dev and test.

**Comment by sat01a** [comment]
Added cron job @http://ecodata-dev.ala.org.au:: /etc/cron.daily/esindexing

**Comment by m-r-c** [comment]
Is it worth doing this as a Grails Job rather than a standalone cron job? The advantage would be that the config is part of the application itself.

**Comment by sat01a** [comment]
We have a todo list item to move the embedded elastic search to a seperate instance. So I guess cron job will be better in that scenario.
BTW, updated ansible script to include cron job.

**Comment by m-r-c** [comment]
OK
