### ISSUE TITLE
Usability feedback - Add a flag to the project metadata for projects contributing data to the ALA

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#297]
Add a user set boolean flag as to whether the project is contributing data to the ALA or not. This should render on the project page and project finder as an icon/image ("Contributing data to the Atlas of Living Australia <ALA icon>")

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-69

**Comment by pbrenton** [comment]
Note that this should be ticked by default if the project is "internal"

**Comment by m-r-c** [comment]
I have defaulted the option to true for internal projects
