### ISSUE TITLE
Usability feedback - Add static text to Terms of Use section to explain behaviour

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#298]
When the user clicks on the ToU link it opens a new tab and changes focus to that tab. This causes confusion about how they got there, what to do next and how to get back to where they were.

Simple option: Place some static text above the ToU link on the project details page about expected behaviour, what to do next and how to return.

Better option: Place the acceptance checkbox (+ associated behaviour) at the bottom of the ToU page and automatically close the tab and return to project details on-check.

**Comment by pbrenton** [comment]
Please add the following static text to the ToU section of the project metadata edit page:

You must open the Terms of Use before you can accept them.
This site and all publicly visible material is licensed under a Creative Commons Attribution 3.0 Australia license. 
![image](https://cloud.githubusercontent.com/assets/8119351/12311421/073aeeaa-baab-11e5-8b1f-6f24fdbe21bc.png)

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-73
