### ISSUE TITLE
Record creation throws an exception.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#304]
Record creation throws an exception when an activity is saved via MERIT.

Example: https://fieldcapture-test.ala.org.au/activity/enterData/08fc16bf-db7f-4232-965d-58a238d944fe?returnTo=https://fieldcapture-test.ala.org.au/project/index/d105ad25-3447-4e70-896b-200a08ae3e71

It appears, record creation expects userId. MERIT may not be sending userId via output JSON. 

This will be a blocker for MERIT as well as iPad and Android tablet release.

Refer:
RecordService::updateRecord(){..
 if (!userDetails) {
                errors['updateError'] = "Unable to lookup user with ID: ${json.userId}. Check authorised systems in auth."
                return errors
            }

**Comment by chrisala** [comment]
The logged in user should be available in ecodata via the UserService, MERIT will be passing the user id as a http header.
Alternatively we could change MERIT to pass the user id when creating/saving activities.

**Comment by temi** [comment]
Is this a fieldcapture issue or biocollect?

**Comment by m-r-c** [comment]
I have changed the code to first check for an authenticated user via the UserService, and to fall back to the manual lookup if there isn't one.

https://upsource.ala.org.au/ecodata/review/ECODATA-CR-6
