### ISSUE TITLE
Apply SDS rules for record visibility in BioCollect

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#306]
Need to apply sensitive data service (SDS) rules for visibility (public view only) of species occurrence records generated from activities/surveys in BioCollect.

Basically each new record in BioCollect which contains a species name and a location coordinate needs to query the SDS for a public display precision coordinate for that record and to apply that coordinate to the public display of the record.

**Comment by chrisala** [comment]
Check sensitive species service when records are saved to retrieve sensitised coordinates.
Requires the ability to trigger a full check of all species when the lists change.

**Comment by sat01a** [comment]
sds-webapp2 which has the lookup api that supposed to return new coordinates for sensitive species.

Webservice url: http://sds.ala.org.au/SDS/lookup?scientificName=Caladenia%20actensis&latitude=&longitude=&date=

The service is unstable with NPE exception throwing even for unknown species 
Example exception:  [GrailsExceptionResolver] NullPointerException occurred when processing request: [GET] /SDS/lookup
Cannot invoke method getCommonName() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method getCommonName() on null object
        at au.org.ala.sds.SDSService.lookupSpecies(SDSService.groovy:202)
        at au.org.ala.sds.SDSController$_closure3.doCall(SDSController.groovy:63)


Its been decided to put hold on this ticket.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-53
