### ISSUE TITLE
map plugin interaction issue

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#309]
* on project finder page when selecting a region from know shape, the returned projects are zero. eg: select ACT and it shows zero projects. On test, it showed 51 projects
* the above problem with drawing shapes.
* organisation page - selecting known shape - program gets first list. but the next list is not populated. It looks like an ajax function is failing.
* organisation page, my project & project finder - clear filters does not seem to working properly when map is hidden
* survey form - selecting from suvey site list - did not work for circular geometry
* single sightings - select a location from drop down - latitude and longitude are not autofilled. Prevents user from submitting form as these fields are required.

**Comment by m-r-c** [comment]
1. You need to edit and save all your projects so the search index is updated with geospatial details (this was from the original spatial filter task)
2. As above.
3. Todo
4. Fixed.
5. Todo
6. Intended: the region selection is just to narrow down the map. The use still has to add a marker at the specific location they made the sighting.

**Comment by m-r-c** [comment]
Fixed under #293
