### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#31]
Allow data download (projects, activities/surveys, records) according to facet-based selections.

**Comment by pbrenton** [comment]
The download should be packages as a zip file containing:
1) Survey data (XLSX multi-tab)
2) Survey image folder containing any images associated with surveys/activities/records (rename images to "survey name + record id")
3) zipped SHP file for point/line/polygon data objects (include dat file with site metadata, site id and area)

**Comment by m-r-c** [comment]
The zip file will have the following structure:

* |- data.xls --> spreadsheet as per {@link CSProjectXlsExporter}
* |- images
* |--- [projectId] --> one directory for each projectId
* |--- |- [fileName] --> one file for each project-level image
* |--- |- [activityId] --> one directory for each activityId
* |--- |- |- [fileName] --> one file for each activity-level image
* |--- |- |- [outputId] --> one directory for each outputId
* |--- |- |--- |- [fileName] --> one file for each output-level image
* |- shapes
* |--- [projectId] --> one directory for each projectId
* |--- |- extent.zip --> shapefile for the project extent
* |--- |- sites.zip  --> shapefile containing all sites for the project

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-9

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-39
