### ISSUE TITLE
The page for selecting an existing site is broken

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#312]
1. Survey admin tab
1. Location tab
1. Choose existing sites

Problems:
1. The query adds ```isCitizenScience: true``` to the fq parameter, which returns 0 results. Removing this returns results. The index may need updating.
1. Paging is broken

This page should use the same pagination controls that are used on other pages (_pagination.gsp).

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-34
