### ISSUE TITLE
Icon images missing on project finder

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#313]
The icon images for projects in the project finder have disappeared - sometime between about 5pm and 10pm yesterday (7/12/15).

While reinstating, please also fix aspect ratio issue affecting several images.
I think the way that this is supposed to work is as follows:
1) set fixed size bounding box for image (150h x 200w)
2) If image width > height, then set width=200 and height=auto
3) If image height > width, then set height=150 and width=auto

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-32
