### ISSUE TITLE
Check the values displayed for species when the species facet is expanded when records are displayed

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#315]
Not all species appear to be in the list.

**Comment by temi** [comment]
this is difficult problem to solve since elastic search requires facet limit number. As our data grows this limit has to be increased.
In this implementation i have capped it at 1000.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-37
