### ISSUE TITLE
Data migration from test to prod

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#316]
Write script to copy existing BioCollect citizen science projects and their metadata from test to production. This will need to include creating new ids for them.

**Comment by m-r-c** [comment]
The data migration will need to include creating Outputs for existing Sighting Records and associating them with the single sighting project/activity.

**Comment by chrisala** [comment]
This review is for the migration of citizen science projects and their associated organisations.  I'll open a separate ticket for the migration of sightings data.

https://upsource.ala.org.au/ecodata/review/ECODATA-CR-13
