### ISSUE TITLE
Merge the sightings form and functionality into BioCollect

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#32]
Merge the sightings form and functionality into the BioCollect architecture to enable single sightings data capture.

Data captured in this form should populate the "record" entity, but meta-info about the record should also be copied to create a linked "survey/activity" record, though only for "single event records" - ie. multiple (>1) occurrence records which have the same observationDate, observerId and siteId should create one survey record instance. Ad-hoc single sightings would not create a survey record.

**Comment by m-r-c** [comment]
Basic functionality for Single and Multiple Sightings have been integrated, with corresponding changes to Ecodata to support storing Records from an Output.

**Comment by m-r-c** [comment]
Reopening - not working correctly in the surveys UI (was tested in the old activity UI).
