### ISSUE TITLE
Need a dataType for time

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#320]
There does not appear to be a data type for time by itself as a field on forms.

Need to be able to support this as some forms require a time field and others don't.

Would be good to have both direct keyboard input "hh:mm" as well as optional GUI time picker.

Need to consider appropriate options for:
* capture as local time, 
* storage as UTC and 
* display as local with time zone suffix and/or as UTC.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-52
