### ISSUE TITLE
Don't display map site selector if a survey does not have specific sites

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#321]
For surveys which are designed purely for ad-hoc point-based records it doesn't make sense to display the location selector with the geoMap.

Therefore I suggest that the site location selector be displayed only if there are 2 or more sites associated with a survey.

If only one site is associated with a survey, then the location selector should not be displayed, but the map should zoom to the extent of the associated site by default.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-47
