### ISSUE TITLE
Add photo feature (image dataType) is not currently supported

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#324]
HIGH PRIORITY
The in-form "Attach document" feature is not working.

There is currently no support to attach an image dataType (essential).

There is also currently no support to attach an audio dataType (highly desirable)

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-45
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-10

**Comment by m-r-c** [comment]
A JS is error thrown when adding an image, on this block:
```
if (result.files[0]) {
                result.files.forEach(function( f ){
                    // flag to indicate the image is in biocollect and needs to be save to ecodata as a document
                    var data = {
                        thumbnailUrl: f.thumbnail_url,
                        url: f.url,
                        contentType: f.contentType,
                        filename: f.name,
                        name: f.name,
                        filesize: f.size,
                        dateTaken: f.isoDate,
                        staged: true,
                        attribution: f.attribution
                    };

                    target.push(new ImageViewModel(data));
                });

                complete(true);
            }
            else {
                error(result.error);
            }
```
because ```result.files``` is not defined: files is an attribute of the ```data``` object. 
Changing the condition to ```data.files``` gets rid of the error, but then the image disappears after upload.

In both cases, no Document record is created when the form is submitted.

Tested in Chrome and Firefox.

**Comment by m-r-c** [comment]
Looks like the above problems were due to a conflict with the sightings plugin. The plugin is going to be removed and replaced with a standard form like the other surveys, so the problem should go away.
