### ISSUE TITLE
Navigation to records from survey list

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#327]
Two changes required:
1. Change link off of the survey name from "view records" to "add record", also retain green "add record button" as is.
2. Insert a new "View records" button (blue colour) blow the green "Add record" button and link to data page pre-filtered to display the relevant data for the relevant survey which the user is permitted to see (ie. apply filter and visibility rules). This should also fix another current issue where the data view is not being pre-filtered by the relevant survey.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-71
