### ISSUE TITLE
Default survey map display should auto-zoom to the project extent

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#329]
The default map display for surveys currently zooms to the Australian continent, but many projects and surveys within projects cover much smaller areas. The default map view for surveys should therefore be the defined project extent.

**Comment by temi** [comment]
if one site, zoom to site and draw
otherwise, zoom to project area but do not draw.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-6
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-67
