### ISSUE TITLE
Cancelling a point coordinate placement does not clear the lat/long coordinate fields

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#332]
Add a location marker to the map for a point observation.
Try to cancel/clear it.
The marker clears, but the latitude and longitude coordinate values remain. These should clear too.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-46

**Comment by temi** [comment]
This fix might have caused the markers to duplicate.  Replication steps - 

1. Single sightings > Map
2. click on a marker > drag to map
3. change the position of the marker.
4. now two markers appear on the map

**Comment by m-r-c** [comment]
Good catch. Fixed.
