### ISSUE TITLE
The "selectMany" mutli-checkbox dataType is not working properly

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#334]
See multi-checkbox fields in the following forms:
http://biocollect-test.ala.org.au/bioActivity/create/567b3bd7-b22d-4bc1-8d53-ccdb740b33a9
http://biocollect-test.ala.org.au/bioActivity/create/23ece4f6-d7c6-418c-9287-858f5517764b
http://biocollect-test.ala.org.au/bioActivity/create/4f496d87-f56a-4769-ba9a-41b61ff8d81f

On-select it is selecting all instead of just the one chosen option(s)
Bullet points should not be displaying at all.
Checkbox should = the height of the capitalised text beside it.
Should be more padding between the checkbox and the text beside it
All checkboxes should align vertically, as should the left justified text options listed beside them.

**Comment by chrisala** [comment]
The selecting all is due to the data type in the dataModel being declared as "text".  It should be "stringList" to support multiple selection.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-42
