### ISSUE TITLE
Project area map edit feature broken

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#336]
HIGH PRIORITY
Existing projects with project extent defined by a known shape have lost the display of the shape.
eg. http://biocollect-test.ala.org.au/project/index/edad0555-32a6-473e-8956-c70cf80329c4

Editing the project details to add the known shape back to the project is not working - ie. the known shape selector does not work at all.

**Comment by chrisala** [comment]
This appears to have been fixed.  It's likely due to the dev spatial portal outage.
