### ISSUE TITLE
Map not displaying correctly in view record for the sightings plugin

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#343]
In view activity/record details in the sightings form, the map is not displaying correctly (see image). Can't find a resource to load.
![fireshot screen capture 006 - view i single sighting i bio collect - biocollect-test_ala_org_au_bioactivity_index_ab1fa933-b564-4886-a3ba-1b2915da2](https://cloud.githubusercontent.com/assets/8119351/12081196/330ab1e2-b2c6-11e5-9368-2656a8e5a6a6.png)

**Comment by m-r-c** [comment]
Cannot replicate: the map image appears correctly for me in Chrome and Firefox. The  loading spinner is visible in the image above...could just have been a glitch with downloading the base tile layer.
