### ISSUE TITLE
Project metadata page - project spatial extent recording section still not quite right

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#344]
Recent changes made to the create spatial extent (project area) on the project metadata page have improved this feature, but it is still not quite right. Current status is per the attached image.
![fireshot screen capture 008 - create i project i field capture - biocollect-test_ala_org_au_project_create_citizenscience true](https://cloud.githubusercontent.com/assets/8119351/12081411/ec4e0938-b2cb-11e5-8d72-fc73661f6553.png)

The following adjustments are needed:
1) Section heading from "Site create/edit" should simply be the map heading - see point 4) below.
2) Change wording of instruction text from "A site should represent ..." to "The project areas should represent ..."
3) Remove display of the site name label and input box as this is auto-generated and superfluous in this context, and the term "site name" is out of context as a "project area". This is only being hidden from view on this page as it is not required in this context - displaying it is even a bit confusing.
4) Change wording above the map from "Create a spatial representation of this site" to "Create/edit the spatial representation of the project area"

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-48
