### ISSUE TITLE
Change the way tags are managed on the project metadata page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#345]
Tags are currently represented as individual boolean fields on the project metadata page. This is inefficient and limits the potential addition of new tags.

Type of science must remain as a separate select field, but others (difficulty, cost, teaching materials,DIY, and suitable for children) should be rolled into a single multi-checkbox tag field with the ability to add new terms as tagging options.

**Comment by temi** [comment]
After discussion with Peter, it was decided to have UI the same but to change the way it is represented in back end. this will enable  better faceting of projects and more consistency with facet logic.

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-66
