### ISSUE TITLE
Add a boolean field to the CS metadata page for ecological survey methods declaration

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#346]
Some citizen science projects have surveys which involve the use of established/published survey methodologies and these surveys should be known to TERN/AEKOS. Currently only projects defined by users as "Ecological survey" type projects will capture the appropriate metadata for sharing with TERN/AEKOS.

In order to share applicable surveys from relevant CS projects we need to be able to invoke the SHaRED/AEKOS metadata requirements from the CS context when it is applicable. pre-populating it with as much pre-existing known and derivable information from BioCollect as possible to minimise additional data entry imposition on users. 

This may be effectively achieved by inserting a new boolean field on the project metadata page with a label such as "Do any surveys in this project use an established or published data collection methodology?". Answering "yes" would invoke a second workflow step (eg. as a "next" button to a SHaRED compatible metadata page pre-populated with known and derivable BioCollect information) in the metadata collection.

**Comment by temi** [comment]
see also #392

**Comment by pbrenton** [comment]
This issues is effectively redundant with recent enhancements to the survey metadata page.
