### ISSUE TITLE
Remove the data licensing and sharing section from the project metadata page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#348]
*** Required before prod deploy

This section is a carry-over from an earlier version when the terms of use did not exist. I now conflicts with the statement in the terms of use in respect to data sharing and licensing and therefore in effect serves no useful purpose in the project metadata template.

At some point in the future, some of this section may be needed to augment the "access" tab in the survey configuration settings, but for now it should be removed completely.

**Comment by sat01a** [comment]
Do we need Project privacy?
![screen shot 2016-01-05 at 11 02 50 am](https://cloud.githubusercontent.com/assets/4197871/12104073/fd7881c2-b39b-11e5-9f92-832101aeadc0.png)

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-51
