### ISSUE TITLE
Survey configuration - Survey info - Discussion thread feature

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#35]
Fix - Comments allowed flag = true, append a discussion thread facility to the bottom of the activity/record view page. Comments allowed = false (default) don't display the discussion thread.

Need to also also add the discussion thread capability to the survey template when flag = true and allow individual records to capture, store and present the discussion thread.

**Comment by m-r-c** [comment]
Reviewed and tested. Looks good.
