### ISSUE TITLE
System allows multiple saves during the project metadata save process

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#353]
It is possible to save the project multiple times during the metadata save process, resulting in duplicate projects.
![warringah](https://cloud.githubusercontent.com/assets/8119351/12135726/6a0a2ffa-b493-11e5-87b1-c8e5bd478016.png)

The project metadata save process is also taking too long.

**Comment by m-r-c** [comment]
I haven't been able to reproduce this. The UI prevents double clicking the button, and a page refresh while the wait dialog is visible does not result in a new project.

Looking at the data, these two projects were created ~1.5 minutes apart. Could they have been manually created - e.g. refresh the screen while the wait dialog was up, then fill in and submit the form again? The system does not currently prevent two projects being created with the same name (which it probably should).
