### ISSUE TITLE
Data > Remove facets section when there is no search result data

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#354]

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-54

**Comment by pbrenton** [comment]
Should also include a message when a project has no data - ie. "No data has been recorded for this project yet"

**Comment by sat01a** [comment]
Done.

**Comment by sat01a** [comment]
done
