### ISSUE TITLE
Migrate data from sightings.ala.org.au to Biocollect

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#355]
The sightings app currently uses a different instance of ecodata to store sightings data.  This data needs to be migrated into ecodata and modified to make it work with Biocollect.

**Comment by pbrenton** [comment]
Additional actions required:
- [ ] Replicate all functionality in the current sightings app into the "single sighting" output form.
- [ ] Download data from sightings and transform to make it compatible with the activity/output structure.
- [ ] Create an "ALA sightings" project in BioCollect (citizenScience) and configure a survey with the new single sighting form.
- [ ] TEST
- [ ] Redirect sightings.ala.org.au to the new survey page in BioCollect. 
- [ ] Disable the current sightings app.
- [ ] Check, update and transform a final set of sightings data from previous extract as required.
- [ ] Load current sightings data and TEST. Need to also ensure that the user profile is correctly configured to link to view of user's submissions through sightings ("My records" in BioCollect?).

**Comment by sat01a** [comment]
Refer #680
