### ISSUE TITLE
Dev/staging - Project feature graphic not scaling properly

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#359]
The feature graphic appears not to be scaling according to the rules - ie. scale to width of bounding box,and max-height 400px (?), maintain aspect ratio.

see http://biocollect-dev.ala.org.au/project/index/2a186934-8692-4a17-ba79-eb69cdf70fb4 as example

**Comment by pbrenton** [comment]
I've re-activated this issue as testing on project http://biocollect-dev.ala.org.au/project/index/2a186934-8692-4a17-ba79-eb69cdf70fb4 in all 3 environments show the image as not scaling correctly. Approx 1/4 of the RHS of the image is not displayed and resolution of the image is very poor, though the original is good.

**Comment by m-r-c** [comment]
This is because the image is too small: it is only 384 x 288 (http://ecodata-test.ala.org.au/uploads/2016-01/SerrTussock_Clear_Range_-_masthead.JPG). The image has been stretched to the full screen width, and the top 400px of the stretched image is shown. The full width of the image is being shown

**Comment by m-r-c** [comment]
I have added a comment saying to use at least 700x450 for the feature graphic to the project and organisation pages.
