### ISSUE TITLE
Prevent creating a project with the same name as an existing project

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#361]
This could happen, especially with different organisations, but I think it would be preferable to not allow it. 

However, we should display a message to the user advising that there is already a project of the same name and suggest alternatives such as appending to the name the applicable year, place name, or some other unique characteristic of that project.

**Comment by m-r-c** [comment]
Some ideas:

1. The create process includes calling the Collectory: if this takes a while, it might be possible to move that into a background task to speed up the project creation. If we do this, then we will also need to:
  1. Send an email to biocollect-support if the call to Collectory fails; and
  1. Add logic when editing a project to include calling the Collectory if the initial call when creating the project failed
1. Add a comment saying the create process could take a couple minutes to the 'wait' message to encourage users to wait instead of refreshing and trying again if there is any delay.

**Comment by temi** [comment]
can only be done on biocollect as this can only be applied to biocollect project not MERIT.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-75
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-18
