### ISSUE TITLE
Auto-generate email to biocollect-support@ala.org.au mailbox when projects are created

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#370]
We need a mechanism for alerting ALA biocollect support staff whenever a new project is created in biocollect.

**Comment by m-r-c** [comment]
This exists already - we're probably just missing a config item on test.

**Comment by m-r-c** [comment]
The config on biocollect-test has been fixed. Emails are sent to biocollect-support@ala.org.au.
