### ISSUE TITLE
System allows you to save project metadata without a primary organisation, despite it being mandatory

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#371]
A client has somehow been able to save the project metadata without an organisation - see this project http://biocollect-test.ala.org.au/project/index/17f91ff4-616b-47db-bada-fe61742d62e3

I have not been able to replicate this and I don't think that we have done anything to fix it. Needs to be looked at as it has clearly been possible to do it.

**Comment by m-r-c** [comment]
There was no validation rule on this field. I have created a custom validator to ensure that an organisation has been selected (not just that some text is in the input field).

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-83
