### ISSUE TITLE
Data page Map tab not updating correctly when there are 0 search results

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#372]
On the Project Data tab, All Records page, or the My Data page:

1. Open the List tab
1. Search for something that returns 0 results
1. The list tab correctly shows 0 results and the map tab cannot be selected.
1. Reset the search
1. Open the Map tab
1. Search for something that returns 0 results

-> The map tab is still selected, and shows the previous results. Either the map should be cleared, or the UI should automatically switch to the List tab with the 'no results' message.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-65
