### ISSUE TITLE
ES index not updated when projects are deleted

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#384]
1. Delete a project
1. Go to the project finder page
1. The project is still listed.
1. Click the project link
1. The user can still navigate to the project

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-68
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-17
