### ISSUE TITLE
Broken header images on survey view page

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#387]
eg. http://biocollect-test.ala.org.au/bioActivity/index/9e8fbd6e-adeb-4f25-8b4a-27d616dc2ff9?returnTo=%2Fproject%2Findex%2Feccadc59-2dc5-44df-8aac-da41bcf17ba4

**Comment by m-r-c** [comment]
Fixed. The view page was using ```/images/filetypes``` as the image location, whereas the edit and create pages use ```/images```.
