### ISSUE TITLE
investigate record export

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#389]
* do not export records with no lat/lng
* do not export embargoed records
* make sure all the darwin core attributes are mapped
* coordinate with data team re: data resource ids

**Comment by m-r-c** [comment]
There is a jenkins job which runs at 11pm each night and pulls records from ecodata-sightings.ala.org.au/ws/record/csvProject.

The corresponding controller action is already excluding embargoed records.

The columns included in the csv are currently fixed at:

```
 "occurrenceID",
                        "scientificName",
                        "family",
                        "kingdom",
                        "decimalLatitude",
                        "decimalLongitude",
                        "eventDate",
                        "userId",
                        "recordedBy",
                        "usingReverseGeocodedLocality",
                        "individualCount",
                        "submissionMethod",
                        "georeferenceProtocol",
                        "identificationVerificationStatus",
                        "occurrenceRemarks",
                        "coordinateUncertaintyInMeters",
                        "geodeticDatum",
                        "imageLicence",
                        "locality",
                        "associatedMedia",
                        "modified",
                        "locationID"
```

This will need to be updated to include any DwC attributes that have been mapped. I think the easiest approach would be to start with all properties of the Record, then exclude specific properties that we do not want to send to Biocache (as opposed to only including the fields to send).

**Comment by m-r-c** [comment]
The tasks required for this ticket are:

1. Change the code to exclude records which do not have lat/lng coords.
1. Change the code to include all DwC attributes.

We will also need to do the following when the existing Sightings application is decommissioned:

1. Change the URL of the dr364 data resource to point to the same Ecodata instance as Biocollect.
1. Either:
  1.1. Change the URL of the dr364 data resource to remove the projectId, so that it exports all Records from Ecodata; or
  1.2. Add additional jobs to Records for other projects.

**Comment by m-r-c** [comment]
I have made the above changes, but I have created a new export endpoint rather than modifying the existing one to preserve backward compatibility for any other consumers of the old server. The new service ONLY exports Records (the old one also pulled data from Activities and Outputs).

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-22
