### ISSUE TITLE
Survey configuration - Species - Instructions

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#39]
Display static instructional information - different to tool tips/help text

Peter B. to provide text

**Comment by pbrenton** [comment]
Can we please implement this with instruction content editable via the Admin > static content edit facility?

In terms of interface placement and behaviour, the content should be specific to each selection and should display in a grey background panel just to the RHS of the selector. If "A selection or group of species" option is selected, dynamically adjust the horizontal size of the instruction display box to allow exposed selector buttons to retain current relative position.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-77
