### ISSUE TITLE
Interoperability with SciStarter

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#397]
Associated with issue #112 but more specific. This is higher priority than #112 as well and is needed in the February sprint.

General tasks include:
1) Normalise transferrable metadata between systems. I am currently doing this with the SciStarter team
2) Implement API key access to BioCollect web services
3) Create a script for on-request pre-filtered extract of project metadata. Fields to include are:
  TBA (PB)
4) Create a script to get project metadata from SciStarter at the below link
5) Create a script to unpack the SciStarter payload and check for duplicate items with projects already in BioCollect, then to create new BioCollect projects and update existing ones as appropriate.
6) may also involve some metadata tweaking in BioCollect - to be assessed.

SciStarter has given us the following link to their API page and below that is some recent correspondence.
http://scistarter.com/api.html

Thank you and this all is moving along in a very promising direction.
I have looped in our developer, Daniel Arbuckle. We do have a few APIs to share very basic information about projects but I think we'd want to expand the number of fields we share between our databases.
We can figure that out easily enough. 
Here's the (un-designed!!) API page:
http://scistarter.com/api.html

Onward!!!
Darlene 
Sent from my iPhone

**Comment by sat01a** [comment]
Comments from Chris:
The ALA index requires:

a title (the project name)
a description (the project description)
a callback URL (a URL linking to the project home page) a useful field to include would be an "all" field which won't be displayed but allows for matching on relevant terms not contained in the name or description. (e.g. geographic information, keywords, species targetted if there is a species list). We could use the elasicsearch "_all" field for this as a start.
We also talked about allowing the projects to be faceted by type, in which case we would also need to return a type field (e.g. Citizen Science, MERIT, Ecological Science, Works).

Another thought is that this requirement appears on the surface to be similar to the sci-starter integration so we could just use that? (the ALA index can ignore the extra fields that it doesn't need)

**Comment by pbrenton** [comment]
Note that the "Citizen Science Project Metadata API" should pre-filter projects by:
1. projectType = Citizen science     and
2. shareMetadata flag = true

Fields for inclusion in the payload are:
- projectId
- name 
- keywords 
- keywords 
- aim 
- task
- dateCreated 
- lastUpdated 
- status 
- managerEmail
- organisationName 
- description 
- getInvolved 
- urlWeb 
- urlImage
- logoCredit
- difficulty
- scienceType 
- isDIY
- hasParticipantCost
- equipment
- plannedStartDate
- plannedEndDate
- state
- locality
- coverage
- centre
- centre
- links
- startDate

**Comment by sat01a** [comment]
/ws/project/search
/ws/project/search?initiator=ala
/ws/project/search?initiator=scistarter
/ws/project/search?initiator=biocollect 

Note: 
a. Indexing needed.
b. Scope of the ticket has been changed, its been decided to open only project metadata for scistarter.
c. Included metadata for bie-index,(name,projectId,description,keywords,projectType,lastUpdated,dateCreated,urlWeb,urlImage,url  (excludes other fields including _all, we can open up other fields as required. Its been decided to excluded MERIT projects.))

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-102
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-34
