### ISSUE TITLE
Add image credit text input fields for project metadata logo and feature images

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#398]
Insert additional text input fields for logo and feature image credits on the project metadata edit page and an image credits ribbon at the bottom of the project page along the lines of:

Image credits: - Logo: xxxxxxxxxxxx; feature image: xxxxxxxxxxxxxxxxxx

This is required for SciStarter interoperability - issue #397

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-79
