### ISSUE TITLE
Add a field for data attribution to the survey configuration - survey details page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#399]
Metadata required for data resources in the ALA includes attribution details.

Please add a text field to the survey configuration - survey details page for this. 
Pre-populate with concatenation of organisation name + survey name, but allow user editing.

Label as: "Survey attribution"
Tool tip: "The attribution text to be quoted by people who use this dataset."

**Comment by sat01a** [comment]
@pbrenton do you also want to show the attribution statement in the project homepage? (may be under the About "Project section")

Survey attribution mandatory?

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-76

**Comment by pbrenton** [comment]
As discussed on phone:

No

Yes

Survey attribution statement is required in the data export and should be mandatory.
