### ISSUE TITLE
Elevate "sites" to equivalent level of "activity" and create site context views of the data

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#400]
Need to be able to view data and images in the context of sites.

1) Create index of site metadata + some project and survey metadata for search and facet based filtering of sites
2) Create list, map, images and chart views for site context (these to be specified in more detail)
3) Site image view to only display photopoint images of filtered sites
4) Enhance the existing Site view page from MERIT to improve presentation and include a photopoint gallery. Should be able to select a site and see the history of activities and surveys on that site, including linked navigation to activities/surveys and projects.

**Comment by temi** [comment]
* index site doc type
* facet headings - Project name, survey, created by, type of site, state or territory, local government area, NRM region
* searchable all of the above and locality, site - description, notes & POI name, description
* do not include chart view now

**Comment by temi** [comment]
Question to PB: do we show merit sites here?

**Comment by pbrenton** [comment]
Thanks Temi, 
I think yes. 


Sent from Samsung Mobile

-------- Original message --------

**Comment by temi** [comment]
created by facet cannot be added since site domain object does not have the created user's userId attached.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-96
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-32

**Comment by temi** [comment]
additional changes done-
- added well around facets, search and tabs
- added  checkbox for multi select facets
- added tab restoration
- facet reset button
