### ISSUE TITLE
Changing project permissions doesn't trigger a re-index

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#402]
The effect of this is that if you add (or remove) a user from a BioCollect project the affected user's "My Projects" page won't update until something else triggers the project to be reindexed.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-20

**Comment by sat01a** [comment]
Adding and updating a user to a project will trigger indexing.
(If the user is deleted then overnight indexing will remove the association.)
