### ISSUE TITLE
To improve page load scale down logo/banner image.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#404]
Issue: 
Project finder page, 
Organisation list page, 
Organisation home page and 
project home page showing high resolution logo.

http://biocollect-test.ala.org.au/project/index/5d1a6eb3-b78e-4e79-9c82-831e11d30c98

**Comment by chrisala** [comment]
There probably already exists a thumbnail version of the logo.  The ecodata Document service creates a 300px wide thumb of all uploaded images.  If we are using the image service it creates a wide selection of thumbs to choose from.

**Comment by pbrenton** [comment]
Also need to check scaling for project page view - appears to be rendering only top RHC in dev (see http://biocollect-dev.ala.org.au/project/index/2a186934-8692-4a17-ba79-eb69cdf70fb4)

**Comment by temi** [comment]
banner can be revisited later.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-94
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-30
