### ISSUE TITLE
Organisation pages should include projects where the organisation is both primary and non-primary

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#407]
If an organisation has a collectory id the organisation page should include projects where that organisation is either the primary organisation or an associated organisation.

**Comment by temi** [comment]
does not need collectory id as long as it has an entry in database.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-28
