### ISSUE TITLE
Remove site display after a record marker is placed on the map

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#408]
Remove the site display after a record marker is placed on the map. This would generally be desirable, but there is one use case for retaining a faint representation of the site/POI - ie. plots, transects and trap points for ecological surveys.

**Comment by m-r-c** [comment]
I have added a configurable option to the 'geoMap' data type to allow both a marker and a region to be displayed at the same time. By default this is false. So if you want the selected site to remain visible when adding a marker, change the *dataModel* JSON to the following:
```
"dataModel": [
    {
        "name": "whatever",
        "dataType": "geoMap",
        "options": {
            "allowMarkerAndRegion": true
        },
        "validate": "required"
    }
],
```

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-81
