### ISSUE TITLE
Reduce the width of polygon boundary lines and opacity on maps

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#409]
Current boundary line for polygons showing on maps is too thick.

The background colouring of the site rendering over the base map is currently too heavy/opaque.

**Comment by m-r-c** [comment]
Reduced the line width to 1px (down from 5), and the opacity to 0.1 (down from 0.5).

I have also changed the colour of shapes when your are drawing them to blue (was pink) to match the region when it is displayed after saving. WMS layers are still red.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-8
