### ISSUE TITLE
Survey configuration - Sites - Known shape

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#41]
Add to known shape selection, set project extent by gazetteer location. Ie. open streetmaps API based gazetteer lookup to retrieve polygon (http://www.objectcult.com/maps/osm_demo.html).

**Comment by m-r-c** [comment]
I have added a new option to the ALA Map plugin to allow geocoding searches for point locations and/or regions (previous just point locations). The Nominatim geocoder returns sites that can have either a point or a polygon, or both. In the cases where a point location is returned and you are using the 'region' based geocoding search, the point will be rendered as a 500m radius circle. This is configurable (it can be disabled, and the radius can be changed) - see the ALA Map doco for details.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-9
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-89
