### ISSUE TITLE
Minor usability suggestions for the survey locations tab

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#413]
When creating a new site for a survey via the locations tab it would be nice if....
1. it was automatically added on the left hand side (i.e. assigned to the survey immediately).
2. the map zoomed to the project area by default
3. the tab remembered any changes you made before pressing the new site button (e.g. I moved a site from project sites to survey sites, then pressed the new site button.  When I returned the site was back in the project sites section.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-90

**Comment by javier-molina** [comment]
@sat01a  this ticket is now complete.

The check for permissions was already performed at au.org.ala.biocollect.merit.SiteController#ajaxUpdate

I will create a pull request from my branch to dev and continue the conversation tomorrow.

**Comment by sat01a** [comment]
@javier-molina, I will chase upsource access for you. In the meanwhile I will add my review feedback in github.

**Comment by javier-molina** [comment]
@sat01a  the last comment re: redirecting on error has also been addressed, I just forgot to add the #413 in the comment.

This is ready again for review.

Let me know if there is anything else that needs to be done with this ticket.

Thanks
Javier

**Comment by javier-molina** [comment]
Code review here:
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-104

**Comment by javier-molina** [comment]
@sat01a https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-104 comments have been addressed.

The CR already has commit    f66c577
