### ISSUE TITLE
Back navigation from survey records view does not return to the correct page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#416]
1. From survey list tab, select to "view records" for a survey --> correctly navigates to data page, pre-filtered with selected survey
2. Click browser back button --> returns to data page instead of back to survey list page (unfiltered).

**Comment by pbrenton** [comment]
Also, it seems to be any time clicking on browser back arrow from an activity/survey page returns to record list page with all filters and pre-selections removed - ie. not remembering the pre-selections on return.

**Comment by sat01a** [comment]
1. All records, My data and Survey list data page will have a ability to restore facet value from local storage.
2. Organisation page will preselect facet based upon organisation.
