### ISSUE TITLE
Mapping - After having selected a site for a new activity it does not clear when de-selected

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#417]
1. goto a survey and add new record - eg. http://biocollect-test.ala.org.au/bioActivity/create/70fbccb9-ede7-49fe-aa1c-80882004e75c
2. Select a site - OK
3. Choose another site --> site display switches to new selection - OK
4. De-select all sites "Choose a site ..." in the drop-down --> does nothing. Last selected site is still selected
5. Add a point location marker to the map --> adds OK, but should also clear existing selected site area (doesn't clear), unless Mark's new config setting is true.

**Comment by m-r-c** [comment]
Fixed.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-88
