### ISSUE TITLE
Mongo out of connections

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#425]
MERIT was giving errors for a few minutes around 12:00 (noon) on 28-01-2016.
Investigation of the logs determined the cause to be that mongo had too many threads waiting for access.

From memory, (at least with an earlier version of the GORM mongo support) exception being thrown during indexing (which happens on a separate thread) was resulting in the mongo connection not being released.  It's possible that the errors creating projects in the collectory #424 are causing a similar issue - needs further investigation.

**Comment by matilda2812** [comment]
@chrisala ok to close this?
