### ISSUE TITLE
Allow BIE-index to consume biocollect projects via REST

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#426]
Follow up with Nick to get the required data format.

**Comment by chrisala** [comment]
The ALA index requires:
 * a title (the project name)
 * a description (the project description)
 * a callback URL (a URL linking to the project home page)
a useful field to include would be an "all" field which won't be displayed but allows for matching on relevant terms not contained in the name or description.  (e.g. geographic information, keywords, species targetted if there is a species list).  We could use the elasicsearch "_all" field for this as a start.

We also talked about allowing the projects to be faceted by type, in which case we would also need to return a type field (e.g. Citizen Science, MERIT, Ecological Science, Works).

Another thought is that this requirement appears on the surface to be similar to the sci-starter integration so we could just use that?  (the ALA index can ignore the extra fields that it doesn't need)

**Comment by sat01a** [comment]
Moved this ticket as part of #397
