### ISSUE TITLE
Must do to decommission sightings app

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#428]
- setting a site as favourite and ability to recall the favourite site
- biocollect will need to provide stable record id for ingestion into ALA. Currently biocollect deletes records on update hence creating new record id. (Completed part of #442 )
- EXIF image data extraction be used to pre-fill fields.

**Comment by m-r-c** [comment]
FYI: https://github.com/AtlasOfLivingAustralia/biocollect/issues/410

**Comment by sat01a** [comment]
Existing sightings functionality needs to be implemented in biocollect.
1. Recent SIghtings.
2. My Sightings.

Also, analysis needs to be done to see what all changes required to be done so that published iOS and Android app can run smoothly.

**Comment by sat01a** [comment]
Refer #680
