### ISSUE TITLE
Selecting a site on the geoMap does not re-zoom to the extent of the new selection

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#433]
In the geoMap, the default view zooms to the extent of the project area not displaying the project area (as expected). 
However, when a site is selected the map does not zoom to the extent of that site and display it, as it should.
Also ensure that selecting and alternate site will zoom to and display the new selection.
http://biocollect-test.ala.org.au/bioActivity/create/02c3fc11-d9c0-4bf5-9d60-9b65112e935f

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-109
