### ISSUE TITLE
Sites tab - Default zoom level wrong

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#438]
When navigating to a site from the sites tab, the default zoom level on the site landing page is not zooming properly to the extent of the site. See http://biocollect-test.ala.org.au/site/index/a03f90d3-127d-4f17-8250-ee80993fcfe5

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-109
