### ISSUE TITLE
When opening a project page from the project list page, always land on the "About" tab

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#447]
Currently the project page is opening on the last opened tab of any project. This is OK for general navigation, but would be disconcerting for someone opening the project initially and expecting to land on the "About" tab. Therefore I'd suggest we should always land on the "About" tab of a selected project when navigating from the project list page.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-114

**Comment by javier-molina** [comment]
This works if originally clicking the search option in the toolbar (project/citizenScience), however if clicking on the home link the referer url will be something like this (http://devt.ala.org.au:8087/biocollect/#isCitizenScience%3Dtrue%26max%3D20%26sort%3DnameSort ) and the issuel will still occur, see image below for details  

![image](https://cloud.githubusercontent.com/assets/8326394/13210148/524c86a8-d980-11e5-85eb-2af1d5a77e61.png)
