### ISSUE TITLE
Survey config - Alerts - Remove "(separated by comma") text from input box

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#452]
It doesn't make sense to have the "(separated by comma)" text in the input box when more entries are included with the "add" button.

**Comment by javier-molina** [comment]
I didn't check this was not scheduled for the current release.

Unassigning now.

**Comment by javier-molina** [comment]
Trivial but yet here is the review

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-115
