### ISSUE TITLE
Survey config - Publish tab - Add another line of user support text

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#457]
Add another line of text between the current line and the publish button:

"<b>Note:</b> If the survey is published and you wish to change anything on the "species", "Survey form" or "Locations" tabs, you must first "Unpublish" the survey. <font style="color:red; weight:strong;">All data already recorded for this survey will be lost if you do this.</font> To retain existing data, end-date the current survey and create a new one with the same details and changed configuration settings.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-116
