### ISSUE TITLE
Survey config - Add new fields to the "survey info" tab - method

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#458]
Add new fields to the survey info tab as follows:

name:    methodName
label:     Survey/sampling method used
help text:    Enter the name of the survey or sampling method used to collect data for this survey (eg. 2ha 20 min bird survey).
requirement=optional

name:    methodAbstract
label:     Description of survey/sampling method
help text:    Please describe the method used to collect data for this survey. In particular, note the duration of the sampling effort, the area covered (size and shape), the number of people in the sampling group and their collective expertise, and anything which may affect the representativeness of the data collected.
requirement=optional

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-117
