### ISSUE TITLE
Survey configuration - Visibility - Add time option

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#46]
Add 180 days to record withholding period options.

Also need to test and make sure that this constraint is bound to surveys and working correctly.

**Comment by temi** [comment]
adding constraint logic depends on completing issue  https://github.com/AtlasOfLivingAustralia/biocollect/issues/60.

**Comment by temi** [comment]
change from drop down to a text field with max of 180, min is 1 and default to 10.

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-39
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-112
