### ISSUE TITLE
Setting a site as favourite and ability to recall the favourite site

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#460]

**Comment by pbrenton** [comment]
Adam is also looking at incorporating this into the geoMap data type, together with a survey>locations config option to display/not display this feature in any given survey. Default should be to display.

**Comment by adam-collins** [comment]
This is done on https://github.com/AtlasOfLivingAustralia/biocollect/tree/removeSightings in the same way as fieldcapture.

**Comment by javier-molina** [comment]
I saw the settings in the survey. I was not aware of the introduction of a location entity as opposed a site but if this fulfills the requirement then I will remove the My Sites Entry to the user profile and cancel this issue.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-46

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-131

**Comment by javier-molina** [comment]
@adam-collins  this has been updated as per your comments.

Favourite sites can now be filtered in the Choose existing sites button while setting the location for a survey.

@pbrenton  fyi.
