### ISSUE TITLE
Scistarter project load.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#461]
To retrieve project data in JSON -> http://scistarter.com/api/project/project-id?key=API key  Search projects: http://scistarter.com/finder?format=json&q=search term

**Comment by pbrenton** [comment]
A few things that will need to account for in the import from SciStarter:

1. Many projects are likely to come without a project extent. Those which don't have an extent should default to an extent of the Australian continent + coastal waters.
2. Projects sourced from SciStarter should be tagged with and display a logo or indicator that they are sourced from SciStarter, with link to www.scistarter.com
3. Project

s which are sourced from SciStarter

**Comment by temi** [comment]
draft biocollect - scistarter field mapping
project name - title
project aim - goal
project description - description
start data - ?
organisation - ?
type of science being undertaken - ?
what is the difficulty level - ?
please describe the tasks involved in .. - ?
project extent - country / australia if no country
project logo - image
logo credit - image_credit

scistarter fields
task - ?
stakeholders - ?
topics - ?
tags - ?

**Comment by pbrenton** [comment]
Here are the field mappings:
![image](https://cloud.githubusercontent.com/assets/8119351/13598479/10edfd60-e572-11e5-9f29-5d50ab63d297.png)

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-129
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-45

**Comment by pbrenton** [comment]
Temi, below is the white-list of 72 SciStarter project ids (for display in the ALA BioCollect hub). All other ids in the current SciStarter extract should be treated as black-list projects (ie. don't display in the ALA BioCollect hub).

A couple of additional notes:
1) We need to automate the refresh process as much as possible, but I've found through this process that there is not currently enough information in the data feed from SciStarter to be able to do that. Best option at present will be as follows:
   a) Baseline the white and black lists with projects from the current extract as indicated.
   b) Set up an automated re-harvest on a daily/nightly basis.
   c) Compare project ids in the new extract with existing ids in both the white and black lists. Filter out all projects which match an existing listed id.
   d) If there are any new projects in the new data extract, send an email to biocollect-support@ala.org.au with a list of new projects (ids + names + url link to project) and boilerplate text requesting review of each project categorisation for addition to the white and black lists.
   e) 

2) There is a reasonable likelihood that, at some stage this year, we will need to create a BioCollect hub for the Australian Citizen Science Association and they will want a superset of projects listed in the ALA hub as well as additional projects form other science types (eg. astronomy, medical, social studies, etc), including additional projects relevant to Australia from SciStarter. Even with a manual review step to confirm relevance to Australia, we should ideally develop a moderation/review process and structure that would work for both hub requirements - maybe with an ALA_ADMIN page to manage inclusion/exclusion of all imported projects in each hub separately with categories of "displayed", not displayed" and "uncategorised".

1480,
1400,
1378,
1368,
1318,
1313,
1303,
1245,
1205,
1146,
997,
988,
987,
931,
920,
917,
874,
870,
869,
864,
854,
850,
849,
842,
828,
797,
795,
791,
764,
704,
689,
687,
681,
647,
645,
644,
643,
621,
615,
614,
600,
587,
582,
567,
564,
554,
472,
471,
446,
431,
423,
416,
413,
411,
403,
388,
371,
345,
338,
336,
334,
288,
280,
168,
136,
53,
44,
42,
33,
32,
27,
26,

**Comment by temi** [comment]
Peter and I decided for this release to import projects using a whitelist. And expand this feature in subsequent sprint.
