### ISSUE TITLE
Server side validation for project creation/update .

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#465]

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/tree/biocollect-465
https://github.com/AtlasOfLivingAustralia/ecodata/tree/biocollect-465

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-120

**Comment by adam-collins** [comment]
moved validation from ecodata to biocollect
https://github.com/AtlasOfLivingAustralia/biocollect/tree/biocollect-465
