### ISSUE TITLE
Server side validation for survey creation/update.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#466]

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ecodata/tree/biocollect-466

**Comment by adam-collins** [comment]
moved validation from ecodata to biocollect
https://github.com/AtlasOfLivingAustralia/biocollect/tree/biocollect-466

**Comment by temi** [comment]
Hi @adam-collins can you create an upsource code review for your commit.

**Comment by adam-collins** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-123

**Comment by javier-molina** [comment]
@adam-collins 
Same as with organisation.

Check for projectActivityId must be using using groovy truth rather than just null

![image](https://cloud.githubusercontent.com/assets/8326394/13910749/ed8008e2-ef7a-11e5-96ff-b8b6234629a0.png)
