### ISSUE TITLE
Geographic filter layer selection is broken in production

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#473]
The geographic filter, known shape layer selection is broken in the production environment, but is OK in test.

**Comment by sat01a** [comment]
Added missing regions.json file @/data/biocollect/config/regions.json

**Comment by javier-molina** [comment]
Other than the file residing in the dev/test prod boxes is it available in a github repo?

**Comment by m-r-c** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/tree/master/ansible/roles/biocollect/files

Might want to check the ansible scripts, because it should have been copied across when the script ran.
