### ISSUE TITLE
Make 'News' and 'Resources' tabs public

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#474]
Remove the member only access constraint on the 'News' and 'Resources' project tabs. Visibility/access constraint should of course still apply to member only (non-public) documents/resources.

**Comment by adam-collins** [comment]
It looks like this is already done on test.

There does appear to be a bug for some older resources that prevents change to the public setting.

**Comment by adam-collins** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-48
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-134

This is not merged to dev.
