### ISSUE TITLE
Project data not displaying on map tab

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#475]
This project has 3 records, but they are not displaying on the map tab.
Client has requested this be fixed ASAP as they are in the middle of an event.

**Comment by pbrenton** [comment]
http://biocollect.ala.org.au/project/index/52e8fee1-880c-49b7-adae-f8039750b25e

**Comment by javier-molina** [comment]
Record.json in ecodata is a total mess, existing records in production will have to be manually fixed.

This is the rough guide:

Find affected records: 

`db.getCollection('record').find({'decimalLatitude':{$exists:false}, 'json':{$exists:true}})
`
Manually populate decimalLatitude and decimalLongitude out of json locationLatitude and locationLongitude

Reindex elastic search.

`<TBC ecodata prod url>/admin/reIndexAll`

Test records are displaying correctly.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-42

**Comment by javier-molina** [comment]
multi record/species could break due to #480

**Comment by temi** [comment]
@javier-molina see my comment in upsource about single sightings not working when site is selected.

**Comment by javier-molina** [comment]
@temi  if no further comments for this, I will let Sathish continue with the review of #480 that among other things covers this ticket.

**Comment by temi** [comment]
@javier-molina I have nothing to add since #475 changes are in #480
