### ISSUE TITLE
Data download is broken in Prod

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#476]
Data download from all download points in Prod is throwing an error. eg http://biocollect.ala.org.au/project/index/52e8fee1-880c-49b7-adae-f8039750b25e
and
http://biocollect.ala.org.au/bioActivity/allRecords

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-119

**Comment by temi** [comment]
this seems to be an apache problem.  It works on test server which is running 2.2 but not on prod or dev server which are running 2.4. it is likely that the proxy on biocollect is not passing all the header on the request.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-130

**Comment by pbrenton** [comment]
Download request from prod is sending an email with link to test and which is a broken link.

**Comment by javier-molina** [comment]
Temi if the link contains a url like this below probably has to do with a
misconfiguration I spotted recently for ecodata
http://biocollect-test.ala.org.au/download/


This was the old entry

# URL to use to download asynchronously produced files
async.download.url.prefix=http://biocollect-test.ala.org.au/download/


I have updated it but we were waiting for a bounce in ecodata for the
change to come into effect.

If it is something different then forget about what I just wrote.

Cheers
Javier

**Comment by temi** [comment]
Thanks, @javier-molina. It appears to be a config issue.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-142
