### ISSUE TITLE
Status line on survey list page not displaying correctly

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#478]
The status line under the survey description on the survey list page is not displaying correctly - inconsistent with the timeline day counter is is causing confusion for users. In this example it should display as "Active, In progress"
![image](https://cloud.githubusercontent.com/assets/8119351/13416355/f425a78a-dfb5-11e5-9e5c-b8cd73763ae7.png)

Test appears to be behaving correctly.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/tree/biocollect-478

**Comment by adam-collins** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-125

**Comment by javier-molina** [comment]
@adam-collins  if you haven't done so could you please create a pull request from branch 478 to dev?

That should complete this ticket

Thanks
