### ISSUE TITLE
Survey configuration - Alerts and Actions

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#48]
Develop this feature with functionality equivalent to the "threshold management" feature in the BDRS.

Design discussion would be worthwhile though.

**Comment by temi** [comment]
condition:
species found
species in area 
action -> email nominated addresses
embargo further analysis required or new ticket will be raised.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-36
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-106
Note: Its been decided to implement only species alerts (Location based alert will be moved out to a new ticket as a low priority)
