### ISSUE TITLE
New Site has invalid centre an invalid features

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#485]
**Steps to reproduce**

- Create a new site with a circle
- Save it

Note: It could affect other shapes too.

**Expected**

centre and location metadata are consistent with the site circle

**Actual**
centre and metadata are not related with the original circle at all

See image below  for details:
![image](https://cloud.githubusercontent.com/assets/8326394/13690480/da460c5c-e784-11e5-9cad-e50f829f016a.png)

**Note for devs.**

Looks like the pid provided by biocollect has nothing to do with the original location misleading ecodata while calculating the centre and location metadata.

The pid is used in au.org.ala.ecodata.SiteService#geometryForPid and is needed in particular for a circle shape.

![image](https://cloud.githubusercontent.com/assets/8326394/13690481/e2b9dada-e784-11e5-81c6-38ffce28e99b.png)

**Comment by javier-molina** [comment]
@pbrenton, @sathishala  FYI. I spotted a new bug while continuing work on #480 

Let me know if any questions.

**Comment by pbrenton** [comment]
Thanks Jarvier, good pick-up and really well explained!
This will likely cause a problem with the indexed search too as I think that the derived location values are indexed for searching. What is your estimate to fix the problem?

**Comment by javier-molina** [comment]
All things considered probably a couple of days, although the fix should be
quick usually the test and review cycle will take longer.

**Comment by adam-collins** [comment]
This is an configuration issue. spatial.baseUrl must be the same in ecodata and biocollect.

ecodata config:
spatial.baseUrl=http://spatial.ala.org.au
spatial.intersectUrl=http://spatial.ala.org.au/ws/intersect
spatial.intersectBatchUrl=http://spatial.ala.org.au/ws/intersect/batch

biocollect config:
spatial.baseURL=http://spatial.ala.org.au

Test by creating a site with a drawn circle.

**Comment by temi** [comment]
@adam-collins can you ensure the biocollect and ecodata ala-install scripts does this correctly.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/commit/246165593a969a0c6360872880a91e0effbceff5
