### ISSUE TITLE
Support for List valued site facets

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#494]
Ecodata is being changed to support multiple values for site geographic facets (e.g. state, local government area, etc).
Biocollect needs to be able to support this when rendering these values.

**Comment by pbrenton** [comment]
Thanks Chris, these are certainly things that are desirable in BioCollect too.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-133

For the moment, I've changed the view to handle list valued facets correctly but the lookup still uses a point intersect.

**Comment by javier-molina** [comment]
Looks like the underlying html was changed, the unit tests for au.org.ala.biocollect.merit.FCTagLibSpec are failing

Here below an example.


|Running 2 unit tests... 5 of 5
--Output from the label attribute of the siteFacet tag should optionally override the facet name--
Failure:  |
the label attribute of the siteFacet tag should optionally override the facet name(au.org.ala.biocollect.merit.FCTagLibSpec)
 |
Condition not satisfied:

applyTemplate('<fc:siteFacet site="${site}" facet="state" max="2" label="State"/>', [site:site]) == "<span class='label label-success'>State</span> ACT, NSW"
|                                                                                         |      |
|                                                                                         |      false
|                                                                                         |      45 differences (18% similarity)
|                                                                                         |      <(dt------------------------------)>State</(dt>\n<dd)>(-)ACT, NSW(</dd>)
|                                                                                         |      <(span class='label label-success')>State</(span~---)>( )ACT, NSW(-----)
|                                                                                         [extent:[geometry:[state:[ACT, NSW, Unused, Unused]]]]
<dt>State</dt>
<dd>ACT, NSW</dd>

	at au.org.ala.biocollect.merit.FCTagLibSpec.the label attribute of the siteFacet tag should optionally override the facet name(FCTagLibSpec.groovy:46)

**Comment by chrisala** [comment]
Thanks, fixed.

**Comment by javier-molina** [comment]
![image](https://cloud.githubusercontent.com/assets/8326394/13977076/f79bc258-f119-11e5-8050-617559dbd9d9.png)

**Comment by javier-molina** [comment]
No more comments.

All good.
