### ISSUE TITLE
elastic search indexing issue with type geo_shape

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#499]
SciStarter projects like the one below has polygon which elasticsearch does not like. This throws an MapperParsingException. This issue was initially noted while doing #461 .
Some information on why this exception happens is given [here](https://github.com/elastic/elasticsearch/issues/14014)

@adam-collins  suggest doing one of the following

Some options after detecting geo parse failure
- index with geometry bounding box
- attempt to fix geometry. This is too difficult
- index without geometry, at least everything else is indexed

http://scistarter.com/project/25-CoCoRaHS%3A%20Rain%2C%20Hail%2C%20Snow%20Network
http://scistarter.com/api/project/25?key={{Enter Key Id Here}}

**Comment by smithsimonj** [comment]
I get this issue with the attached shape for [Antarctica](https://github.com/elastic/elasticsearch/files/195290/Antarctica.txt) in Elasticsearch 2.2.1. The error is:

    Provided shape has duplicate consecutive coordinates at: (180.0, -90.0, NaN)

My mapping bit looks like:

    "location": {"type": "geo_shape", "precision": "1600m"}

The shape I am trying to load is in the attached JSON record (specifically the "geometry" field from within it): [Antarctica.txt](https://github.com/elastic/elasticsearch/files/195290/Antarctica.txt)

I agree with the analysis in the referenced ticket that this is a function of the shape being simplified before being indexed - the 'duplicate consecutive coordinates' being referred to in the error quite simply don't appear even once in the original data.

**Comment by temi** [comment]
1884, 1883

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-52
