### ISSUE TITLE
Multiple Sightings model produces an additional empty record

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocollect#502]
An additional empty record is created for each empty additional records table section.

ecodata creates the additional record for Multiple Species because outputSpeciesId always present causing this test to always succeed https://github.com/AtlasOfLivingAustralia/ecodata/blob/a5a9d5ded978a7410697f3af0e82c9a390c719ca/src/groovy/au/org/ala/ecodata/converter/RecordConverter.groovy#L101

A possible solution:
- Make Multiple Species species2 field mandatory.
- For use in Multiple Species, add a parameter to the viewModel type "table" to prevent the automatic addition of a new empty row when creating a new bioActivity.

**Comment by javier-molina** [comment]
Multiple Sightings is a different animal and Sathish has mentioned previously that if not used in production (it was the case two weeks ago.) it would be more sensible to disable it while the endless list of bugs specific to it are fixed.

@pbrenton  any preference?

Personally for the solution of this ticket I prefer option one, ie, making species2 mandatatory.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-47 

Please see comment in review pointing to the effective lines changed.
