### ISSUE TITLE
Multi Sights Form - Don't display any rows in the table by default

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#503]
Follow up from #502 

When creating a new survey/record from multisightings form, the table should not include any rows by default, user has to manually add rows if he needs them

**Comment by javier-molina** [comment]
Chris suggest to use a defaultRows for the json definition with an empty array. This needs to be tested.

an example of defaultRows can be found in bioCondition surveys:

"dataModel": [
        {
            "defaultRows": [
                {"groundCoverType": "% Native Perennial ('decreaser') grass cover*"},
                {"groundCoverType": "% Native other grass cover (if relevant)*"},
                {"groundCoverType": "% Native forbs and other species (non-grass)"},
                {"groundCoverType": "% Native shrubs (< 1m height)"},
                {"groundCoverType": "% Non-native grass"},
                {"groundCoverType": "% Non-native forbs and shrubs"},
                {"groundCoverType": "% Litter*"},
                {"groundCoverType": "% Rock"},
                {"groundCoverType": "% Bare ground"},
                {"groundCoverType": "% Cryptograms"}
            ],
            "dataType": "list",

The idea is to use  "defautRows":[]

**Comment by pbrenton** [comment]
Actually another related requirement is to be able to specify a number of rows by default - see HCAS project, disturbances impacting condition table (https://biocollect-test.ala.org.au/bioActivity/create/b1c6fa32-961d-4405-8c83-68110509fcba?hub=hcat). They want to be able to change this from fixed rows to variable rows, but displaying 3 rows as default.

**Comment by matilda2812** [comment]
Closed because this is now possible.
