### ISSUE TITLE
Can't edit project metadata - terms of use condition blocking save

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#504]
With the production release on 24/3/16 it appears that the terms of use save condition on the project metadata page is not remembering the "true" setting and is hence blocking saving of edits to page content. re-setting the TOR agreement is not required on subsequent edits and it is therefore not displayed for subsequent edits.

This is high priority

**Comment by adam-collins** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-49

**Comment by adam-collins** [comment]
Production data is updated.
