### ISSUE TITLE
Species search/autocomplete is not filtering by or displaying common names

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#506]
The search and autocomplete in species fields is only working on the scientific name column in the species table and is only displaying scientific name strings, regardless of the sequence in which names were loaded into a list. It must be searching on scientific, common and vernacular names from the lists table.

Display of names should also allow option to display as either:

- _Scientific name_ (common name); or
- Common name (_Scientific name_)

This issue is high priority as it is affecting existing clients now.

**Comment by sat01a** [comment]
@temi can you pls add upsource review url

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-141
