### ISSUE TITLE
Selecting "other organisations" is not working in the project metadata page 

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#510]
On the project metadata page after searching for an org name, selecting an organisation name from the "Your organisations" part of the org select list does work, but not from the "Other organisations" section of the list.

It seems to work fine when just scrolling through the list and selecting one.

**Comment by javier-molina** [comment]
@pbrenton 

Could you ring me when you have a chance?

I can't see the issue here other than the red error meesage once you select an organisation.

Probably I missing an scenario.

![image](https://cloud.githubusercontent.com/assets/8326394/14973949/3283f66e-1132-11e6-8be1-9baa43817f67.png)


Thanks

**Comment by pbrenton** [comment]
@javier-molina, it does indeed seem to be working OK in test now, but I have noticed that sometimes new projects have been successfully registered in production without an organisation, which should not happen. I can't see any examples of this in prod at the moment though.

I'll keep an eye on it and reactivate the issue if need be.

**Comment by javier-molina** [comment]
@pbrenton  I didn't see your comment earlier.

There are a couple of instances where a project doesn't have an organisation as per design:

1. Merit projects 
2. SciStarter projects

For Merit projects indeed the link below will redirect me to MERIT so probably you are not referring to this case
http://biocollect.ala.org.au/project/index/09825c50-25ae-4756-8fe1-b7cb63fef5e1 


This below is a SciStarter project, not sure if you experienced the issue with these but my understanding is that SciStarter projects are refreshed automatically every few days.
http://biocollect.ala.org.au/project/index/df432bf8-b25d-4ed1-8716-d85f22cef895 

If these examples don't provide you any scenario for the issue you originally raised I agree that we should close it and revisit it should you spotted in the future.

**Comment by javier-molina** [comment]
Closing for now. Will reopen if reoccurs
