### ISSUE TITLE
Error saving admin edited content in 'News & events' and 'Project stories'

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#512]
Client reported issue with saving changes and new content in 'News & events' and 'Project stories' admin features - see
![image](https://cloud.githubusercontent.com/assets/8119351/14877128/ee1600c6-0d5d-11e6-8f3f-48db161909a7.png)

**Comment by javier-molina** [comment]
Works for me in my local env with the same data

`<p><em>*Denmark Environment Centre Inc*</em><br/>2016 Talk Series<br/><em>Talks on the environment, meet other locals, learn how you can be involved</em><br/>Denmark Environment Centre 35 Strickland St</p><p>10am to 12pm followed by a cuppa<br/>Friday 29th March<br/>Judy Morris &amp; Karin Baker from Albany Regional Herbarium Present:<br/><strong>Preparing Plant Specimens for ID</strong><br/>RSVP essential denviron@denviron.org.au</p><p>Supported by FRRR (Foundation for Rural and Regional Renewal)</p>`


ecodata.log in prod does not show any relevant activity for this project around the last time it was updated: (2016-04-28T06:24:04.445Z) 

There is no biocollect log for the day above.

The news entry reported is already active for project Working Wonders on Weeds.

Given all of the above I think it was just a temporary problem and this issue can now be closed.
