### ISSUE TITLE
BioCollect Production Release 2.5

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#531]
Place holder to record things needs to be taken care of during production release (for both BioCollect and ecodata):
1. SciStarter projects need to be reimported again.
2. Ecodata tomcat configuration needs to be updated @javier-molina to fill in.

**Comment by javier-molina** [comment]
This is the https version of ecodata-config.properties that needs to be deployed to production.

`#CAS Config
casProperties=casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilter,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath
serverName=https://ecodata.ala.org.au
contextPath=
casServerName=https://auth.ala.org.au
uriFilterPattern=/admin/.*
uriExclusionFilterPattern=/images.*,/css.*,/js.*,/less.*
authenticateOnlyIfLoggedInFilterPattern=
casServerLoginUrl=https://auth.ala.org.au/cas/login
gateway=true
casServerUrlPrefix=https://auth.ala.org.au/cas
security.cas.logoutUrl=https://auth.ala.org.au/cas/logout
userDetails.url = https://auth.ala.org.au/userdetails/userDetails/
app.uploads.url=https://ecodata.ala.org.au/uploads/
grails.serverURL=https://ecodata.ala.org.au
app.external.model.dir=/data/ecodata/models/
app.api.whiteList=150.229.66.35,127.0.0.1,152.83.196.56,52.63.208.142,52.63.44.128
# Spatial portal config
spatial.baseUrl=https://spatial.ala.org.au
spatial.wms.url=https://spatial.ala.org.au/geoserver/ALA/wms?
spatial.wms.cache.url=https://spatial.ala.org.au/geoserver/gwc/service/wms?
spatial.layersUrl=https://spatial.ala.org.au/layers-service
spatial.geoserverUrl=https://spatial.ala.org.au/geoserver
spatial.intersectUrl=https://spatial.ala.org.au/ws/intersect/
spatial.intersectBatchUrl=https://spatial.ala.org.au/ws/intersect/batch

# Image Server config
ala.image.service.url=https://images.ala.org.au/
#userDetails.url=http://authproxy.ala.org.au:8080/UserDetailsProxy/
security.apikey.serviceUrl=https://auth.ala.org.au/apikey/ws/check?apikey=

# Collectory config
collectory.baseURL=http://collections.ala.org.au/

# Email config
grails.mail.host=act-ironport-int.csiro.au
grails.mail.port=25
ecodata.support.email.address = biocollect-support@ala.org.au
ecodata.system.email.replyTo = ALATest<no-reply>@ala.org.au>
ecodata.system.email.sender = biocollect-support@ala.org.au

# URL to use to download asynchronously produced files
async.download.url.prefix=https://biocollect.ala.org.au/download/

# Biocollect Project Url for species alert
biocollect.project.url=https://biocollect.ala.org.au/project/index/
biocollect.activity.url=https://biocollect.ala.org.au/bioActivity/index/

temp.dir=/data/ecodata/temp

# Period for cleaning up temporary files, in days
temp.file.cleanup.days=1

spatial.baseUrl=https://spatial.ala.org.au
spatial.intersectUrl=https://spatial.ala.org.au/ws/intersect
spatial.intersectBatchUrl=https://spatial.ala.org.au/ws/intersect/batch

scistarter.apiKey=486f9275de50afa3eecce3eea69c9709e7b2f48c5ed1cf769ee6116f00aa0e7b9637ac669fbaa76060f26425ba9d505bddc9ff355cd4d2547a53fa2bbec0a46e
scistarter.baseUrl=https://scistarter.com
scistarter.forceHttpsUrls=true
scistarter.projectUrl=/api/project
scistarter.finderUrl=/finder`

**Comment by javier-molina** [comment]
ecodata-config.properties.1.13 file in ecodata production config location has the updated configuration for when biocollect 2.5 goes live.

**Comment by javier-molina** [comment]
After release, scistarter projects need to be reindexed, the while is is here below

`1569,1480,1400,1378,1368,1318,1313,1303,1245,1205,1146,997,988,987,931,920,917,874,870,869,864,854,850,849,842,828,797,795,791,764,704,689,687,681,647,645,644,643,621,615,614,600,587,582,567,564,554,472,471,446,431,423,416,413,411,403,388,371,345,338,336,334,288,280,168,136,53,44,42,33,32,27,26`
