### ISSUE TITLE
Add bulk data loading for flat forms

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#537]
For all surveys which use a flat data form (ie. no nested tables or multiSelect fields), on the survey list page, display "Load data" button (project admin only) below the "View records" button for each survey. Button colour = yellow like selected tag colour.

Required functionality:
- [ ] Open a sandbox-like page (upload page) which will allow user to copy/paste a spreadsheet into the interface. Need to consider whether open in modal (like AEKOS submission - preferred) or separate page would be best.
- [ ] Upload page should also provide a link to download a spreadsheet template for the selected survey. Download template must include field validations, data types and constraints. 
- [ ] Ability to upload data either via copy/paste into the interface or by navigate/select the appropriate spreadsheet file from storage.
- [ ] Parse the spreadsheet dataset into columns and rows
- [ ] Auto-match column heading to fields from the survey schema. (Use the survey/activity/output data model as the reference schema for field mapping)
- [ ] Allow user to map unmatched field headings to any remaining unmatched schema field names by selection from drop-down selector in column header (based on schema field name labels or schema field database names). Reduce remaining available options to unmatched fields only (ie. as a field is selected it is removed from available options for remaining field mapping. If a previously mapped field mapping is changed, the previously mapped field should be available for re-selection and mapping to another column.)
- [ ] Auto-validate data in cells and highlight all errors. 
- [ ] Display "Upload to server" button, but only activate if all data validates and column headings map to schema. Permit unmapped columns only if all schema fields are mapped, but display a message that data in unmapped columns will not be loaded.
- [ ] Activate "Upload to server" button only if all field mapping and validation conditions are fulfilled. If not fulfilled, show tool-tip on the upload button that "Field mapping and/or data validation has not been completed" or "Unmatched fields cannot be uploaded into this survey".  

If forms attached to survey have nested tables or multiSelect fields, do not display "Load data" button.
For all surveys which use a flat data form (ie. no nested tables or multiSelect fields), on the survey list page, display "Load data" button (project admin only) below the "View records" button for each survey. Button colour = yellow like selected tag colour.

Additional Notes:
1) Need to discuss approaches to handling nested tables and multi-select fields in forms as well as forms constructed from multiple outputs. Consider DwC archive format, but how to implement?

**Comment by temi** [comment]
requested by user - https://support.ehelp.edu.au/a/tickets/162821

**Comment by temi** [comment]
https://support.ehelp.edu.au/helpdesk/tickets/167014

**Comment by temi** [comment]
Check email of editor of Tempe Birdos

**Comment by pbrenton** [comment]
Tested satisfactory
