### ISSUE TITLE
Surveys not displaying correctly when not logged in

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#540]
When not logged in, surveys on the survey list page are not displaying correctly
![fireshot screen capture 016 - working wonders on weeds - community of denmark w_a_ i project i field capture - biocollect_ala_org_au_project_index_f0caedd0-70fd-4388-adb8-8d26935fa6](https://cloud.githubusercontent.com/assets/8119351/16376631/a280a82a-3ca4-11e6-9636-14305ae06973.png)

**Comment by chrisala** [comment]
This same error occurs for me whether or not I am logged in.

**Comment by chrisala** [comment]
The issue appears to be present when associated orgs for a project do not have a logo property.  This will be the case for orgs without logos that we created before the latest release.  We need to run a data migration or update the code to handle it better.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-150
