### ISSUE TITLE
Home Page design 1 - Facet

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#541]

**Comment by javier-molina** [comment]
@pbrenton  This is how the filters in the home page are looking so far.

I got rid of the controls that hide/show the filter sections, they are not consistent with the new layout.

Are we planning to change the colors? 

Filter by geographic region is something that won't display nice with the new layout as the real estate for displaying maps is limited. What I have in mind is to display a pop up with the map on it for this particular filter. Please yell out if you think it should be something different.

Also please let me know how we go about the Ecological Science home page, as per vm my suggestion is to apply the same design rules to it as both pages share a lot of components behind the scenes and from a design perspective they will continue to be consistent.

![image](https://cloud.githubusercontent.com/assets/8326394/16549176/6979e8d0-41df-11e6-8786-94c1fd831115.png)

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-148

Animation of filter panel will be improved as part of #542

**Comment by pbrenton** [comment]
Hi Jarvier,Sorry I missrd this one in my inbow.Understood about the map. Your suggestion re the map seems best approach to me too. Just need to ensure it will also work properly on mobile too.Re. Colours in the filter section, yes l think we will need to change colours.I agree with you re the ecological science page too and was expecting it to behave/have the same layout.
ThanksPeter


Sent from my Samsung GALAXY S5

-------- Original message --------

**Comment by pbrenton** [comment]
[ ] Move "sort by" and "projects per page" from the facet panel to drop-down selectors located beside the list/tile view toggle above the result set.
[ ] Change "project status", "difficulty level" and "tags" to a more 'facet-like' appearance than 'tag-like' appearance.
[ ] Include organisations in the facet list. Show 10 by default with elipsis to show more in a modal - same behaviour as per the Biocache.
[ ] Title layout is currently not fully responsive for display on small format devices. Eg. wrapping and proportional scaling not working properly on some page elements.

**Comment by javier-molina** [comment]
As per discussion with Peter, new facets will be a second priority and implemented during this sprint if time allows.

Title length will be increased but we still need to wrap it for large ones.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-157 

#542 feedback is addressed here too.
