### ISSUE TITLE
Home Page design 2 - Tile

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#542]
Some of the tiled layout examples for BioCollect home page (ticket: Home Page design 2 - Tile​):

http://preview.codecanyon.net/item/melonhtml5-metro-ui/full_screen_preview/2986068
https://s-media-cache-ak0.pinimg.com/236x/bd/01/a4/bd01a4cc9baff11aae77efa23002250f.jpg
https://s-media-cache-ak0.pinimg.com/736x/d4/26/da/d426da85359cfa4b82eb5a081b70c0fb.jpg
https://store-images.s-microsoft.com/image/apps.53000.9007199266472672.bec9ecb6-aa69-44f4-901a-5636c2c572e0.94fd05b8-b988-4e1c-be05-b6891fb0abe2?w=580&h=326&q=60&mode=letterbox&background=black

We also need to provide an option on top of the page, where user can choose their view preference.

**Comment by javier-molina** [comment]
> Hi Javier,
> 
> Some of the tiled layout examples for BioCollect home page (ticket: Home Page design 2 - Tile​):
> 
> http://preview.codecanyon.net/item/melonhtml5-metro-ui/full_screen_preview/2986068
> https://s-media-cache-ak0.pinimg.com/236x/bd/01/a4/bd01a4cc9baff11aae77efa23002250f.jpg
> https://s-media-cache-ak0.pinimg.com/736x/d4/26/da/d426da85359cfa4b82eb5a081b70c0fb.jpg
> https://store-images.s-microsoft.com/image/apps.53000.9007199266472672.bec9ecb6-aa69-44f4-901a-5636c2c572e0.94fd05b8-b988-4e1c-be05-b6891fb0abe2?w=580&h=326&q=60&mode=letterbox&background=black
> 
> We also need to provide an option on top of the page, where user can choose their view preference.
> 
> Cheers
> Sathish

**Comment by javier-molina** [comment]
@pbrenton this is a screenshot on how the tile view looks. Please feel free to comment if you'd like me to change anything.
 

![screen shot 2016-07-12 at 11 34 23 am](https://cloud.githubusercontent.com/assets/8326394/16752514/4a32d1d4-4825-11e6-8f21-53bdc12528c2.png)

**Comment by pbrenton** [comment]
Hi  Javier, Horizontal size looks ok, but can you please make the  image to 80% width of box andscale aspect ratio accordingly. Also make all  box background colors whit and for the box to have a border. Vertical height of images to be governed by aspect ratio, but all boxes sould be same size and align - use elipsis to clip long text.Can we please try this to see how it looks?
Thanks
Cheers Peter
Sent from my Samsung GALAXY S5

-------- Original message --------

**Comment by javier-molina** [comment]
Hi Peter

Here is the new version incorporating your feedback.

Please let me know if you'd like any further changes.

![screen shot 2016-07-14 at 10 28 53 am](https://cloud.githubusercontent.com/assets/8326394/16824547/00fd9f30-49b0-11e6-97aa-9450f49a9337.png)

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-153

**Comment by pbrenton** [comment]
- [ ] Font style is inconsistent with the list view - change to same as list view
- [ ] Project title should display in full, ie. not truncate
- [ ] Project title, logo image and elipsis should all link to the project "About" page
- [ ] Check responsive scalability for small format devices. Currently column stacking/wrapping thresholds not quite right and there is an issue with project title and description text wrapping as the tiles reduce in width.

**Comment by sat01a** [comment]
Hi @pbrenton, if project title is not truncated then height of the tile box will be inconsistent between projects.  May be we can increase the length of project title before truncating it?

**Comment by javier-molina** [comment]
Status: Add Status and Bold text, one line.

**Comment by javier-molina** [comment]
Changes are here 
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-157
