### ISSUE TITLE
Analyse and rework ecodata biocollect indexing to accomdate work project

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#543]

**Comment by sat01a** [comment]
Refer #680

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-215
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-76

**Comment by javier-molina** [comment]
Works records should display only in the All Records works hub
