### ISSUE TITLE
MERI Plan - Admin only. (Similar to MERIT)

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#547]

**Comment by javier-molina** [comment]
This is what needs to be implemented:

https://fieldcapture.ala.org.au/project/index/d8e26dbc-d033-41c8-bd22-865d9c136935 

![screen shot 2016-07-14 at 4 25 42 pm](https://cloud.githubusercontent.com/assets/8326394/16830028/b62a928a-49df-11e6-820f-4e9e662896a1.png)


![screen shot 2016-07-14 at 4 20 08 pm](https://cloud.githubusercontent.com/assets/8326394/16829945/3c2bb23e-49df-11e6-8341-9528cea32b03.png)

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-161
