### ISSUE TITLE
 Add a 'bar' to use of biocollect data collection features for non-biodiversity science types

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#565]
The Australian Citizen Science Association (ACSA) is engaging the ALA to develop a BioCollect project finder hub for ACSA to enable the discovery of all CS projects relevant to Australia and which Australians can participate in. This will involve the ability to register all kinds of CS projects including non-biodiversity and NRM related projects (eg. astronomy, social science, medical science, geology, etc.). 

Tasks for this ticket include:
Only allow (still optional) the value for the question "Do you want to use BioCollect to record your project data" to be set to "Yes" if any of the following science types are selected:
- Animals
- Insects & Pollinators
- Biodiversity
- NRM
- Ecology & Environment
- Birds
- Ecology
- Predator-Prey Interactions
- Symbyotic Interactions
- Biogeography
- Fire Ecology
- Long-Term Species Monitoring

ie. If one or more of these science types are selected, with or without any other science type category, the option of a "Yes" value for the above question is permitted. Otherwise only a "No" value is permitted for that question.

This rule must over-ride a setting of "Yes". If the question already has a setting of "Yes", display a warning message to the user with explanation 
"Use of this system for data collection is not available for non-biodiversity related projects."
Actions:

- Continue - change question value to "No" and return to page
- Cancel - close modal and return to page (no change)

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-179
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-61
