### ISSUE TITLE
Add new science types to the CS project metadata page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#566]
The Australian Citizen Science Association (ACSA) is engaging the ALA to develop a BioCollect project finder hub for ACSA to enable the discovery of all CS projects relevant to Australia and which Australians can participate in. This will involve the ability to register all kinds of CS projects including non-biodiversity and NRM related projects (eg. astronomy, social science, medical science, geology, etc.). 

Task:  Add new science types to the CS project metadata page as follows:

- Agricultural & veterinary science
- Astronomy
- Biogeography
- Chemical sciences
- Climate & meteorology
- Fire Ecology
- Genetics
- Geology & soils
- Geomorphology
- Information & computing sciences
- Long-Term Species Monitoring
- Medical & human health
- Physical science
- Social sciences
- Symbyotic Interactions
- Technology

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-60
