### ISSUE TITLE
Add toggle buttons to display all global projects or only those relevant to Australia

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#567]
The Australian Citizen Science Association (ACSA) is engaging the ALA to develop a BioCollect project finder hub for ACSA to enable the discovery of all CS projects relevant to Australia and which Australians can participate in. They also want to be able to toggle to a view of all projects globally, regardless of relevance to Australia.
Tasks:  
- [ ] Enable all SciStarter projects to be retrieved via web service and stored in BioCollect. There is already the ability to this, but these are filtered by id into a white-list of projects relevant to Australia. The white-list is still relevant to the Australian-only view, but we also need to be able to view all global projects (de-duplicating those projects which are already in BioCollect).
- [ ] Add icon-like toggle buttons adjacent to the toggle grid/list view buttons and in the same appearance, maybe with a map of Australia on the Aus filtered view and a globe on the full global view. Alt-text to be "Show projects relevant to Australia" and "Show all global projects" respectively.
- [ ] Set the default view to Australian-only projects.
- [ ] Apply search, filter and display rules to enable the result set for each view to display dynamically according to the current rule settings.

**Comment by pbrenton** [comment]
SciStarter have added 3 new fields to their data model since we last downloaded and these can be used in conjunction with their id field to do the Austalian/global context views that we want to do. They will also allow us to move to scheduled machine-machine based updates.

The fields that we need to add are:
"**origin**"   -  auto-populate (non-editable) with "atlasoflivingaustralia" for all projects created in BioCollect, ie. not loaded from another source.
"**country**"   -  autopolulate with "Australia" for all BioCollect projects where the project extent is within the extent of the "Australia and coastal waters" spatial layer.
**UN_regions**   -  This is probably a bit redundant now, but 

Their "id" value should be populated into our "externalId" field and used as a filter on every update from SciStarter. ie. Updates from SciStarter should be scheduled on a weekly basis. We pull from their web service a full extract of projects and compare the project ids in the extract from SciStarter with the ids in our externalId field, rejecting any that match projects that we already have in BioCollect. Then create new projects for any new project ids.

All new fields will need to be indexed and included as facets in the filter panel. [Also note other additional facets to be added - see issue #]

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-175
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-59

**Comment by javier-molina** [comment]
@temi countries and regions lists are not populated when first creating a project, if you edit a project then the lists are populated. I can see this behaviour even in test.

Steps to reproduce:

1. Create a new project
2. Scroll to 'This project is run in the following countries' and 'This project is located in the following UN regions'

Expected:
Both lists are populated

Actual:
Lists are empty

**Comment by temi** [comment]
@javier-molina good catch. I have pushed a fix.
