### ISSUE TITLE
Add map view of projects to the project finder

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#575]
Include the map view of projects which is currently on the "Map" tab of the organisation page to the project finders for citizen science, ecoscience and works project types. Resize the map area to be visually balanced with an appropriate aspect ratio.

Represent as an icon above the result set like for list and tile views with a silouette map of the world on the grey button.

All 3 project types should provide all 3 view options consistently across them. 

Projects displayed on the map should respond to the search and filter selections as per other views.

Default behaviour to show project extents on hover over marker, but also include a toggle switch to show all project extents together (markers included).

Clicking on a marker should display a modal containing all of the metadata elements (including links) currently displayed for projects in the tile/grid view of projects.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-227
