### ISSUE TITLE
Modify works project type home page 

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#576]
The works project type needs to have design and behaviour consistency with other project types. The following changes are required:
- [x] Display the works project type banner image
- [x] Modify the facet side-panel to "pull-out" behaviour as per new citizen science page
- [x] Remove the word "facet" from facet headings in the display
- [x] Modify the existing list view to a layout similar to that in CS and ecoscience project type list views
- [x] Add a tile view similar to the tile view in the CS and ecoscience project type tile views
- [x] Change the "map" and "projects" view tabs to icon toggle buttons as per the CS and ecoscience project type buttons
- [x] Move the "Dashboard" and "Download" tab functions to a new "Data" menu page (to be defined in another issue)

**Comment by javier-molina** [comment]
Works facets should be part of the overall facet configuration of the Hub and should be part of a single index for the projects.

Current Works projects home page includes a map view, this view needs to be retrofitted to the hub configuration, hence be also available to CS and Ecoscience projects.

**Comment by pbrenton** [comment]
Jarvier's comment of Mar 21 moved to new issue #852
