### ISSUE TITLE
Personal dashboard link in menu is broken

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#577]
Select "Dashboard" from user's personal profile in BioCollect menu.
Returns the following error
![fireshot capture 1 - an error has occurred - https___biocollect-test ala org au_user_index](https://cloud.githubusercontent.com/assets/8119351/17081344/9702197c-5197-11e6-86da-489581959700.png)

**Comment by pbrenton** [comment]
I'd suggest that we hide the personal dashboard menu item for now as having it is a relatively low priority at the moment.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-203
