### ISSUE TITLE
Security - Project membership

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#58]
* Add a new user level of 'member'
* For non-citizen science projects, add an option to the project config screen to make the project 'public' (not visible and always defaults to true for Citizen Science projects)
  * When true, allows public users to add records to the project (after logging in); when false, general users cannot add records
  * When a user adds a record to a public project, they will be automatically registered with that project with the Member role
* Extend the My Projects list to include the Member role

**Comment by chrisala** [comment]
My mistake on this one - the config option to make the project 'public' should actually be applied against each individual survey (ProjectActivity).
The option to add data using a non-public surveys should only be displayed to project editors or admins.  
Question: Should the data (activities and records) produced from a non-public survey be visible to users who are not editors or admins?
