### ISSUE TITLE
Sightings form ignoring mandatory photo field

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#581]
To reproduce: 
1. Create a record on test https://biocollect-test.ala.org.au/bioActivity/create/57afbe22-5895-48d8-b4ab-e32aae149608
2. Fill out other fields, but don't attach a photo.
3. Save.

Expected behaviour:  a validation error for the missing mandatory field
Actual behaviour: the record is saved without a photo.

**Comment by sat01a** [comment]
As per the discussion with Peter. Closing this one and creating a new ticket to implement server side validation for all form fields. This will help us validating web service  request that comes via Mobile and third party clients.
