### ISSUE TITLE
Add "Most recent" to the sort by options of all project finders

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#584]
Add a sort by option to display the result set in reverse-chronological order (most recent first). This should be the default sort order.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-159
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-55
https://github.com/AtlasOfLivingAustralia/ecodata/pull/279
