### ISSUE TITLE
Add background colour to the facet panel and also behind the result set tiles

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#586]
Add background colours to all project finders as follows:

**- Facet panel -** light grey shaded similar to unselected sort-by and pagination buttons. Also add text above the facet panel "Filter by"
**Result set container in tile view (ie. the white space behind individual tiles and their borders) -** Solid pale grey per the darker colour used for the shaded facet panel.

**Comment by javier-molina** [comment]
Please review together #583, #585 and #586
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-158

https://github.com/AtlasOfLivingAustralia/biocollect/pull/589
