### ISSUE TITLE
Redesign - Project about tab - similar to ecoscience

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#594]

**Comment by javier-molina** [comment]
Change this
![screen shot 2016-08-03 at 4 42 08 pm](https://cloud.githubusercontent.com/assets/8326394/17356286/e21f7850-5999-11e6-941a-8fe519e7642f.png)

To look more like this:

![screen shot 2016-08-03 at 4 41 29 pm](https://cloud.githubusercontent.com/assets/8326394/17356295/ece62dd8-5999-11e6-89a5-ff716d243e00.png)


Rename project funding tab to Program Information for both ecoscience and works.

More feedback from Peter will be needed as the firt cut is ready.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-165

Inadvertently committed directly to dev.

**Comment by javier-molina** [comment]
From Peter:
> Can we remove the "No cost" being displayed on the works About page. It is also a problem on the ecoscience About page and should not be mandatory in CS either.

**Comment by javier-molina** [comment]
Investigation about Tags resulted in  #633

**Comment by javier-molina** [comment]
Optional fields in project creation to be followed up in #634
