### ISSUE TITLE
Blog functionality consistent with other project types

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#595]
- News & Events, and project Stories from merit to be enabled in works projects.
- Move content to its own tab.
- Retrofit CS and ecoscience with this functionality. 
- Provide a mean to migrate or display legacy content.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-58

**Comment by javier-molina** [comment]
News & Events, and project Stories from merit to be enabled in works projects.
Move content to its own tab.

Retrofit CS and ecoscience with this functionality. 
Provide a mean to migrate or display legacy content.


> > [4:06 PM] Javier Molina: Works projects implement its own News and Project stories as blogs
> [4:07 PM] Javier Molina: Do you want just the same functionality appear in its own tab
> [4:07 PM] Javier Molina: or do you want instead the Citizen Science News and events and Project stories for works projects?
> [4:08 PM] Javier Molina: going this path we would still need to display legacy blog entries for old projects.
> [4:10 PM] Javier Molina: it is worth mentioning that CS News and events and Project Stories functionality is more limited, ie, essentially just text, as opposed the Works Blog functionality that allows to set date,  and image.
> [4:10 PM] Javier Molina: I hope that is clear.
> [4:11 PM] Peter Brenton: Works project currently has separate News & Events + Project stories sections. Intention is to replace the existing News & events + Stories sections/tabs in all 3 projects types to reflect the model implemented in MERIT. This will require consideration of treatment of existing content in those section currently in BioCollect too.
> [4:12 PM] Peter Brenton: At least the works project type currently has the ADMIN place for editing content, but not the display tab. Edit function also not working anyway.
> [4:14 PM] Javier Molina: No worries
> [4:14 PM] Peter Brenton: CS and ecoscience project types currently have the News & Events + Project stories sections functioning properly in ADMIN and combined view tab. As mentioned, intent is to replace these with MERIT blog functionality in all 3 project types so that all are consistent.
> [4:14 PM] Javier Molina: ok
> [4:15 PM] Javier Molina: I have the functionality working on Works projects
> [4:15 PM] Peter Brenton: Is that in test now?
> [4:15 PM] Javier Molina: I just need to put the actual content in  a separate tab
> [4:15 PM] Javier Molina: I will deploy that to test tomorrow, I need to wait after the prod release tonight
> [4:16 PM] Peter Brenton: Yep, ok
> [4:16 PM] Peter Brenton: Does that include the on-page edit for appropriate permission.
> [4:16 PM] Javier Molina: We can start with that and then I can continue working on what's needed to display legacy CS and ecoscience content
> [4:17 PM] Javier Molina: there is a separate admin section to edit content
> [4:19 PM] Peter Brenton: BTW, I'm thinking that it would still be better to keep in a separate tab and not on the About page as that would likely make the About page too big. Either that or place on the About page in a section of fixed height with display section and article scroll/select beside it. May be difficult to display properly on mobile though.
> [4:19 PM] Javier Molina: Agreed
> [4:19 PM] Javier Molina: I am working on creating a separate tab for it
> [4:20 PM] Javier Molina: the redesign of the about tab already covers that, which you will also see in tomorrows build
> [4:21 PM] Peter Brenton: Could create a separate tab for now and then depricate the current news tab when we carry the content from existing projects over to blogs
> [4:21 PM] Javier Molina: ie, the news and events has gone from the about tab but still needs its own tab
> [4:21 PM] Javier Molina: Thanks for the clarification, we will continue the conversation tomorrow unless something else arises.
> [4:21 PM] Peter Brenton: ok

**Comment by javier-molina** [comment]
Comments from Peter: 

> [1:17 PM] Peter Brenton: images attached to the blog are taking up full page width and are huge. Probably need to a max-height of about 500px an align the blog text beside and, if longer, expand below the image in 2 columns too. ie. show blog text as 2 column, with the image occupying the top part of one column - left or right, I'm not sure which would be better visually.
> [1:18 PM] Peter Brenton: Blog image seems to insert and possibly replace the banner image on the home page. Haven't test this thoroughly yet though

> [1:22 PM] Peter Brenton: New blog posts with images --> the new image replaces the previous banner image
> [1:25 PM] Peter Brenton: Just call the tab "Blog" rather than "Project Blog"

> Blog images appear to link directly to the project feature image. Adding blog images replaces the feature image. Removing the feature image also removes it from the blog entry. Replacing the feature image with another feature image in the project metadata page does what it normally does, ie. displays correctly on About page. The blog entry (edit mode) suggests that the image is still present when it has been removed via the project metadata page (feature image) - ie. image not present, but button displays as "- Remove image".

**Comment by javier-molina** [comment]
@pbrenton uploaded images have been resized to resemblethe layout of MERIT. Laying text into multiple columns could be tricky, please give it a go as it is now and let me know if anything needs to be adjusted.

Re: image replacing the feature image, I couldn't see that issue, just bear in mind that the feature image is displayed in the About tab while the images for the news and stories are in the Blog tab. 

Happy to join in a webex conference if it still happens to you and we need to discuss the steps to reproduce it.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-177

**Comment by javier-molina** [comment]
> Hi Javier, I'm still getting some inconsistent behaviour with the blog post image. I created this project (https://biocollect-test.ala.org.au/works/project/index/fc0639d1-f9e5-4a26-ba4a-98d0985b6b91) this morning and it seemed to work OK (ie. expected behaviour). However, in a project that I had created a few days ago (https://biocollect-test.ala.org.au/works/project/index/d794deb6-1031-4593-a861-9db783864d25), I previously had a different feature image on the home page to what is currently displaying. I added a new blog post to this project just a few minutes ago and the image from the new blog post has replaced the previous feature image. If you go the edit the project metadata for this project and delete the current feature image (the bee on flower), the previous one reappears.

**Comment by javier-molina** [comment]
Feature image overriding fixed.
