### ISSUE TITLE
Site creation permissions

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#596]
Add Sites subtab to Admin section

The new tab will have only one checkbox configuration named: "Allow editors to manage sites"

This setting will:

1. Enable edit controls for editors in Site tab (create new sites, edit existing ones)
1. Enable the in situ site creation of the map plugin when editing works activities (the actual surveys).

**Comment by pbrenton** [comment]
This task involves:
- [ ] Add "Sites" tab to the project level tab bar between "Work Schedule" and "Project Plan"
- [ ] Add a "Sites" configuration sub-tab under "Admin > Project settings" (beside "Project info" which needs to be converted into a sub-tab like format as per "Activity settings"). This will be the equivalent of the "Locations" configuration sub-tab in CS & ES surveys. Should probably also change the label on the survey one to "Sites" while at it, just to be consistent.

**Comment by javier-molina** [comment]
@pbrenton Can you confirm whether there is any specific work to do in the Admin/ Project settings info for this task or all the requirements are covered on #616  and related tasks?

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-241
