### ISSUE TITLE
Add support for configurable facets to projects

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#60]
### Basic implementation

* Implement a predefined list of facetable fields based on the current BDRS projects
* Allow project admins to pick from this list

### Ideal implementation:

* Allow the project admin to select from _any_ field from the data models of all of the surveys to create facets (where it makes sense to support faceting - i.e. drop downs etc)

**Comment by chrisala** [comment]
The BDRS has the following facets as defaults:
* User
* Survey
* Species Group (note this will require that species groups can be specified somehow)
* Year
* Month
* Location (site)
* Multimedia (filter by Records that have attached images)

It would also be handy to allow faceting by our various geographic tags such as LGA / NRM region, State, vegetation type etc.

To make some of these facets available, we may need to "enhance" the Records as they are put into the search index.  (see ElasticSearchService::prepareActivityForIndexing, ElasticSearchService::prepareProjectForHomePageIndex)

**Comment by m-r-c** [comment]
Duplicates #249
