### ISSUE TITLE
Allow each individual species field in a survey to have its own configuration.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#603]
This issue tracks code changes for **enabling per species field configuration in CS surveys**.

The original requirement for **Works projects** will be implemented and tracked on **#747** 

Retrofitting Bulk upload with this and species list will be addressed on #755

Below is the original requirements for both Works and CS species fields configuration.

-------------------------------------------------------------

To reproduce:
1) Create an activity for a works project has has a species field (e.g. Pest Management)
2) Toggle to implementation / data entry mode.
3) Enter species data into a species field.

Expected result: a dropdown containing species matching the entered text.
Actual result: nothing.

It appears to be because the species search currently relies on the project activity (survey) context to do species lookups but works projects don't use surveys.

**Comment by pbrenton** [comment]
This issue should be addressed by updating the way that the ADMIN>Species of interest page operates and having species fields in particular activities lookup the relevant constrained list as specified.
Actions include:
**ADMIN>Species of interest page** 
- [ ] Change tab name to "Activity settings" and move up to below the "Project settings" sub-tab
- [ ] Change the content on this page as follows"
- Remove the "List of species" input box
- Add a table with one row per activity which includes at least one usage of a species field. If an activity has >1 usage of a species field, then each usage should have a separate row (though still within the context of that activity). Table columns should be: "Activity name", "Species selector", "Species Name(s)/List(s)", "Display names as"
- Activity name - auto-populate, non-editable
- Species selector - as per step 4 in survey configuration page. 
- Species Name(s)/List(s) - as per step 4 in survey configuration page (wrap in cell)
- Display names as - radio button selector as per step 4 in survey configuration page

**Comment by javier-molina** [comment]
@pbrenton would you mind pointing me (or preparing) to surveys/activities where I can test the different scenarios that need to tested?

I think the most complex scenario will be a survey with more than one species field (not a table field).

Finally I want to double check that when we refer to activity name we refer to the survey definition and not to each particular activity instance. For example in the image below we have two site monitoring plan entries, (let's assume they have a species field). The requirement is to configure species for only the site monitoring plan survey rather than species configuration for each activity entry, is that correct?

Thanks

![screen shot 2017-01-09 at 11 49 08 am](https://cloud.githubusercontent.com/assets/8326394/21755110/14182038-d662-11e6-8ded-0809d5092d99.png)

**Comment by javier-molina** [comment]
Reponses from Peter:

A good test survey with more than one species in a single survey is the Reptile Nest Monitoring Project that has a field to capture the tree species as well as the bird species nesting on that tree.

From the comment above, the species configuration will be by survey type, option (a)

In addition, the configuration by each species field needs to be retrofitted to CS and Ecoscience project type as well.

**Implementation consideration** How are we going to manage existing surveys? 
Probably we will replicate the single configuration across each different species field?

**Comment by pbrenton** [comment]
Implementation consideration How are we going to manage existing surveys?
Probably we will replicate the single configuration across each different species field?
PB - Agreed, assuming that "each different species field" means column headings in the new table layout.

**Comment by pbrenton** [comment]
**Test results:**

1. List configuration search results select list disconnects from search box and scrolls with background page.
2. It is not clear how to move from the search config modal back to the species config tab. Only way is to click on X to close the page, but workflow is not clear.
3. Ideally names of selected list(s) (even truncated) or the individual species name (if only single) should display with the input settings selector.
4. Input Settings heading needs to have help text added.
5. Species field name is not displaying in the configuration table.
6. How does one configure for multiple species fields? Do they display by default if the selected survey form has more than one species field contained in the data model?

**Comment by pbrenton** [comment]
**2nd Test Results:**
- Requires to select a "default configuration", but only applying the validation on publishing. Validation should occur on Save or Next.
- I think that the create and then select default config model is confusing as you'd have to create a default config, then select it for a species usage, then create a separate list for the other species usage
- Can we replace the text string in the input settings box with either "<species name>" if a single species or "List: <list name 1>,<list name n>", truncated to length of current select box? This would be more intuitive to me.
- Configured lists are working OK in forms

**Comment by javier-molina** [comment]
Hi @pbrenton 

This is a summary of the changes addressing your comments:

- Species configuration dialog now scrolls nicely and Apply and Cancel button remain at the top of the screen so users now about them even when adding species lists.

- First list name or species name displayed in species tab if Speciest lists or single species selected. Tooltip where added with more details
- Now All headings in Species tab have help text
- As per our discussion, species field names are sourced from the form and displayed prepending the output section name.
- Default configuration concept removed. For legacy records the old configuration will be copied across all species fields. Form with no species field will display only an information message in the species configuration tab
- when trying to save invalid species settings an error message will be displayed in the species tab

**Comment by pbrenton** [comment]
Thanks @javier-molina, 
Looks good, but just one thing. Warning message appears on opening a project from the project finder itself. Should only display warning when on-click the species configuration tab.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-210
