### ISSUE TITLE
Works project type - Change labeling of various tabs

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#605]
Change the labeling of various tabs as follows for consistency with other hubs:
- [ ] "MERI Plan" tab to "Project Plan"
- [ ] "Activities" tab to "Work Schedule"
- [ ] "Documents" tab to "Resources"
- [ ] ADMIN>"Edit MERI Plan" sub-tab to ADMIN>"Edit Project Plan"
- [ ] ADMIN>"Project access" to ADMIN>"Project members"
- [ ] ADMIN>"Species of interest" to ADMIN>"Activity settings">"Species" (in red tab style). This is to allow for future activity level constraints which respects the overall design/styling paradigm. Also move this sub-tab up to belop the "Project settings" sub-tab.
- [ ] ADMIN>"Documents" to ADMIN>"Resources"

- [ ] Also include a "Sites" tab at the top level positioned between the "Work Schedule" and "Project Plan" tabs. This is the equivalent of the project "Sites" tab in MERIT.

**Comment by chrisala** [comment]
The sites tab requirement is covered by #616

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-169

**Comment by javier-molina** [comment]
A quick inspection reveals that some tabs inside the Admin section and some headings are still showing old values.

For instance in the Admin section the subtabs still show MERIT plan and Documents. A search for MERI in IDEA (case sensitive and full word) will reveal a few quick wins.

![screen shot 2016-08-11 at 5 36 50 pm](https://cloud.githubusercontent.com/assets/8326394/17581661/6356547e-5fea-11e6-98d4-b2b14048ed2c.png)

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-178
