### ISSUE TITLE
Activity type filtering by default program is not working

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#610]
In the test environment:
Program model - Basin Champions program
- Set available activities associated with the program to only those starting with "Basin champions" in the title

Hub settings
- Set default program to "Basin champions". Also selected "Basin champions" as the selected program option in the multi-select list above.
- Also cleared browser cache. Not sure if also needed to clear the ecodata cache.

In https://biocollect-test.ala.org.au/mdba/project/index/4d15b4df-c05b-41bd-ac5b-8a65c9e37d17, form selector in survey settings
- Check range of available survey options - should only be those activities which were associated with the Basin champions program in the program model.

**Comment by chrisala** [comment]
As discussed, the default program cannot be applied to existing projects.  It will be assigned to new projects only.
