### ISSUE TITLE
Works project type - Remove the site selector from header of activity edit pages

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#615]
BioCollect works projects will use the geomap data type plugin in activity forms and therefore will not require the site selector in the activity edit page header.

**NB:**
Selection of pre-defined sites will need to be done by the plugin site selector, referencing sites defined in the ADMIN>Project settings>Sites tab.

**Dependent on site related components of issues #608, #616 and #619)**

**Comment by chrisala** [comment]
Unless I am mistaken, this will also involve duplicating all of the works activities / outputs to include the site plugin in the definition.  And updating the hub to use those new activity types.

**Comment by pbrenton** [comment]
Hey Chris, 
No you're not mistaken. I have done this with some of the monitoring and assessment forms already, but will need to also apply to others too.

Also see ticket #597

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-231
