### ISSUE TITLE
Works project type - create/edit pre-defined sites

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#616]
Need to add the "Sites" tab which is currently in MERIT to project tabs.

For new sites created via the map plugin (see issue #619), these need to be added to the pre-defined sites list associated with the project and indexed appropriately.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-229
