### ISSUE TITLE
All project types - Allow the ad-hoc creation of sites/locations directly from activity forms via the geomap plugin

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#619]
Provide a configurable option to allow polygon-based sites (work projects)/locations (survey projects) to be created via the geomap plugin.
- Configuration settings to be on the sites/locations editing page
- Use the polygon create tools already in the geomap plugin
- Must be able to submit the shape to spatial portal and register, index, etc. and add to the existing list of pre-defined sites/locations associated with the project

**Comment by pbrenton** [comment]
Related task #472

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-230
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-84
