### ISSUE TITLE
CS project finder & metadata - Add new tag and science types

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#622]
- Add a participation tag to the CS project metadata page "Participate at home" and index to include in faceted filtering options on the project finder search page.

- Add new science types for "Indigenous science" and "Indigenous knowledge"

Only applies to the CS project type. Index for inclusion in facet lists.

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-68
