### ISSUE TITLE
Project finder - Default view settings not as expected

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#627]
The default view setting for the project finder should be:
- Facet/filter panel exposed
- Display all projects of project type
- Projects per page = 20
- Sort by = Most relevant
- View = Tile

Currently 
View = list
Sort by = Name

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-181
