### ISSUE TITLE
Works project type - Reinstate the "Partners" section to the project metadata template and About page display

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#631]
"Associated organisations" or "Partners" section has been removed from the project metadata template in the works project type, but needs to stay. Please reinstate - position and behaviour as per CS and ecoscience pages.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-172
