### ISSUE TITLE
Citizen Science hub - Program name displaying on project "About" page

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#632]
"Program name" seems to have snuck into the display on the project "About" page in the CS hub. This should be removed/hidden in the CS hub only. It is relevant for the ecoscience and works hubs.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/biocollect/revision/13a397b4b1ef985fabe48c5d49c3f9e6afae0dd3
