### ISSUE TITLE
Tag fields must be optional

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#634]
Currently fields that are displayed as tags in about page although not strictly mandatory, they default to false if not filled in which is misleading.

Implement values as true optionals so they remain empty (and hence the tag does not show) if not filled by a user.

Fields to make optional:

Difficulty level
cost to participants
Teaching materials
DIY
Suitable for children under 18

TBC: Peter to validate we are covering all fields that need to be true optionals

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-187
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-192
