### ISSUE TITLE
Project finder - Unexpected behaviour of new facet sections

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#636]
1. Science type facet section - reports listed items apparently randomly as items are selected. Items should remain in alphabetic order in the list.
2. Organisation facet section
   - does not allow multiple selections and removes unselected items from the list.
   - remove the word "facet" from the section title
3. All facet sections
   - indicate (#projects count) in brackets beside each item
   - Generally though, facet behaviour should be consistent for all 3 hubs and same as the MERIT/works approach.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-193
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-182
