### ISSUE TITLE
Tab visibility permissions

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#638]
The following tabs should be publicly visible for all project types and regardless of whether it is an internal or external project:
- About
- Blog
- Resources
  For external projects, also ensure that ADMIN edit facilities are available for the blog and resources features too.

The following tabs should only be visible to logged in project members:
**Citizen science and Eco science project types**
- About, Blog and Resources, plus
- Surveys
- Data
- Admin (Admin users only)

**Works project type**
- About, Blog and Resources, plus
- Work Schedule
- Sites
- Project Plan
- Dashboard
- Admin (Admin users only)

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-204

**Comment by pbrenton** [comment]
There is a bug in new tab display behaviour for SciStarter projects. These are displaying the "Project plan" tab when they shouldn't be.
