### ISSUE TITLE
Works project type - About page content display

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#639]
1. Move "Project originally registered in" label and value from the "About the project" section to the "Project information" section.
2. Suffix field labels with a colon and space of several characters for the following fields:
   - Project originally registered in
   - External Id
   - Grant Id
   - Funding (also add a $ sign as prefix to the value)
   - Contact email
3. Move the values for the following properties from below the labels to in-line (RHS):
   - Project originally registered in
   - External Id
   - Grant Id
   - Funding
   - Contact email
4. Add a space in the "ExternalId" label between "External" and "Id"
5. Move the partner association block (ie. "This project is run in association with") from the left column to the right column below the "Project information" section.

**Comment by charvolant** [comment]
Fix in https://github.com/AtlasOfLivingAustralia/biocollect/pull/725
