### ISSUE TITLE
Updata bootstrap version from version 2 to current

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#648]

**Comment by matthewandrews** [comment]
Hmm - really need to upgrade to Bootstrap 4 now - bs3 is unsupported and has security vulnerabilities (let alone bs2).

**Comment by matilda2812** [comment]
Closing given move to bs4

**Comment by cofiem** [comment]
@matilda2812 I'm interested in the move to bootstrap 4 - I gather from this issue being closed that the move is documented elsewhere, but I can't seem to find any other mention of bootststrap 4? Could you point me in the right direction? Thanks.

**Comment by matilda2812** [comment]
My bad- I assumed this was underway but I may be wrong.
