### ISSUE TITLE
Data types - Add a JSON property for default value

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#651]
Several user requests have come to light for the need to be able to set default values in forms. The simplest way to do this would be to add a JSON property (view model?) to specify the default value.

**Comment by charvolant** [comment]
Commit in branch biocollect-651 https://github.com/AtlasOfLivingAustralia/biocollect/commit/fdfda3a7362ed7411332388fb8055cd0b3f6992e

Code review request in https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-207

**Comment by charvolant** [comment]
How to:

Allows a defaultValue: field in a dataModel.json 

For example

```
{
  "dataType": "text",
  "name": "observedBy",
  "defaultValue": "Fred Nurke",
  "description": "The name of the person or party that undertook the survey event."
  }
```

There are two special cases. If a text field has a constraint list, the default value can be an index into the constraint list. Eg.

```
{
  "dataType": "text",
  "name": "intertidalZone",
  "description": "The intertidal zone sampled",
  "defaultValue": "0",
  "constraints": [
    "Low intertidal zone",
    "Mid intertidal zone"
  ]
 }
 ```

 For any defaultValue, the string `${now}` will be changed to an ISO-8601 date and time. Eg. "Hello now ${now}" will become "Hello now 2016-12-21T14:21:34+11:00" This is most useful when you're setting dates/times but it could be used in text.
