### ISSUE TITLE
Works project: Editing activity for a second time fails

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#653]
For a works project with existing activities when editing an activity for the second time, the fields will be different to what originally entered and you won't be able to save the activity due to validation errors

**Steps to reproduce**
1. For an existing works project go to Works Schedule tab
2. Add a new activity
1. Now edit the activity and save
2. Edit the activity one more time

**Expected**
It should be possible to edit the activity

**Actual**
Type of activity value has changed to Indegrnous Employment and Businesses
Planned start date and Planned end date values have disappeared and it is not possible to edit those fields.

![screen shot 2016-08-17 at 11 10 09 am](https://cloud.githubusercontent.com/assets/8326394/17721308/9cdc80c0-646c-11e6-8ae5-c6f29cae99c7.png)

In addition note that the 'Type of activity List' in step 2 and 3 above are different, these need to be the same.

**Comment by javier-molina** [comment]
The type of activity list is sourced from the Programs model.

See 'General Works Projects' program in test, the edit activity functionality is not using such list.
![Uploading Screen Shot 2016-08-17 at 11.10.09 AM.png…]()

**Comment by chrisala** [comment]
This bug is due to a script error related to the map display.   Implementing #615 should fix it.

**Comment by javier-molina** [comment]
Activity types list fixed.

Other issues seems to be addressed by other changes since the ticket was reported.

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-208

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-216
