### ISSUE TITLE
ACSA logo and link is only applicable for the CS hub

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#654]
Need to keep the ACSA logo and link as-is in the CS hub, but remove it from the other hubs

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-187

**Comment by javier-molina** [comment]
Looks like the review is not related to this ticket but the system works as expected so I am closing this ticket.
