### ISSUE TITLE
Facet issues

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#656]
**CS Hub**
Please render facet descriptions for tags as follows:
Currently displaying as 
![image](https://cloud.githubusercontent.com/assets/8119351/17758048/538eb870-652f-11e6-90a4-47dc2233a27d.png)
Should display as you showed me on your dev system.

Note that the geographic filter still applies to all.

**Facets for "My Projects"**
- Status
- Project type
- Science type
- Difficulty
- Tags
- Organisation {this is a combination of primary and associated organisations}

**Facets for "My Organisations"**
- Status
- Project type
- Science type
- Program name
- Organisation {this is a combination of primary and associated organisations}

**Facets in the Citizen Science hub project finder**
- Status
- Science type
- Countries
- Organisation 
- Tags
- Difficulty
- Source System (Origin)
- UN Regions

**Facets in the Ecoscience hub project finder**
- Status
- Science type
- Organisation 
- Program name 
- Site name

**Facets in the Works hub project finder**
- Status
- Science type
- Organisation 
- Program name 
- Site name

**Facet help text**
Please also add a help text "?" adjacent to facet category labels on all project listing pages in all hubs as follows:
- **Status** [Active projects are still running, whereas 'completed' projects have ended and are no longer 'active']
- **Difficulty** [A general level of difficulty for citizen science participation]
- **Tags** [Classifications for citizen science projects to assist decision making for participation]
- **Project type** [The project type reflects the hub in which projects were created, but will be either 'survey-based' (Citizen and Ecological science) or 'schedule-based' (Works and MERIT) formats for recording data.]
- **Science type** [Categories of science which survey-based projects are addressing.]
- **Origin** [The project catalogue system in which the project is registered.]
- **Countries** [Countries in which people can participate in the project.]
- **UN Regions** [The continental regions in which projects occur according to the United Nations regional classification scheme.]
- **Organisation** [Organisations either running projects or associated with projects (eg. as partners).]
- **Program name** [The administrative Program under which a project is being run.]
- **Site name** [A site at which data has been collected for one or projects.]

**Comment by temi** [comment]
Facets for works is not done. This will be moved to a new ticket. also, site name for ecoscience hub will be done later.

**Comment by temi** [comment]
Works project facets could is not done. I have created a new issue for it #669.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-187
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-65
