### ISSUE TITLE
Facet/filter section - "Clear all" not resetting the geographic filter

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#659]
"Clear all" resets all selected facets, but doesn't reset the geographic filter, which the "Rest" button does.

The "Clear all" should behave the same as the "Reset filters" button and the "Reset filters" button can then be removed from the bottom of the section.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-187
