### ISSUE TITLE
Ecoscience hub - Facets not displaying correctly

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#664]
Science types and Programme name classes are parsing into separate single word facets for word strings.
Sub-programme needs to be also included as a facet category.
![ecoscience facets](https://cloud.githubusercontent.com/assets/8119351/17854835/a008b412-68b8-11e6-8a40-ce1c501c5591.png)

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-185
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-63

**Comment by pbrenton** [comment]
Programs name facet is still parsing and displaying incorrectly

**Comment by temi** [comment]
also programme facet is added in the below review.
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-192
