### ISSUE TITLE
Can't delete a project end date after selecting one

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#666]
Create or edit a project including both a project start date and project end date (ie. project has a known duration). 
Circumstances change and you want to now make the project indefinite, therefore need to remove the project end date.
Edit the project metadata and try to remove the end date. This is difficult to do and on save throws an error.

Should have a "Clear" button appear beside the date selector when a date has been entered. 
Should allow end date to be null and not throw an error.

**Comment by qifeng-bai** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-263
