### ISSUE TITLE
Can't save edited project metadata

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#670]
Open and edit a SciStarter project.
Change country and UN Region
Save

Throws error (no actual message displayed)
Does not save change

**Comment by temi** [comment]
This error was because there was two projects with same name. After discussion with Peter, it was decided to remove the duplicate check on project name.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-192
