### ISSUE TITLE
ALA sightings requirements

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#680]
This is a list of features that I feel need to be maintained in the BioCollect version of the sightings app on the ALA site.

**Records list:**
- list of sightings must display the following fields: image thumbnail, scientific & common names, any tags, recordedBy, date, locality info
- there should be a set of links/filters for: recent sightings (default view, newest at top), "My sightings", links to both in biocache (can be in a small info/header section)
- (optional) I'd like to see filters for the most common tags (ordered by frequency of use) - e.g. a tag for "spiders (243)" that when clicked shows all the records tagged with "spiders". This should be bookmarkable for people who want to regularly check their favourite groups.
- (optional) Add a button "Alerts" which links off to the alerts app and creates email notifications when new records are added for a given "view" (see biocache or BIE which both have this)
- there should be a "report a sighting" (or equivalent text) button on **all pages**, in the same place on the page (top right corner in current version)

**Adding a sighting:**
- Add a header section (replace the ALA sightings bit at top) with links to recent, my sightings and occurrence explorer, as described above.
- replace all labels containing "survey" with "sighting"
- Change text `Record your individual sightings of iconic species in the project region.` to `Record a sighting`
- `drag and drop` of images must work
- populate date, time and geolocation from image exif data
- (optional) once a known species has been added, show a thumbnail photo next to the species name - people like this feature in the current version and it often prevents an incorrect ID when they see the thumbnail is the wrong thing
- `search for locality` is broken. Most users would expect to type a string into the box and press the `search for locality`, which doesn't work. The actual function is to take the lat/lng and lookup a locality match. The current sightings app automatically updates the locality whenever the lat/lng values change, and I recommend this functionality be implemented - thus removing the `search for locality` button completely. I note that even Peter made this mistake in the demo and he is a biocollect expert.
- add a `search address, location or coordinates` input field - the tiny icon on the map is not intuitive at all and I only found it after looking for over a minute, as I knew it was there somewhere...
- location string lookup is returning spanish locale results: 
  ![image](https://cloud.githubusercontent.com/assets/532845/17953571/c54b4c2a-6ab7-11e6-9b62-564fb1658a30.png)
- red "reset map" icon - why is it red? It doesn't seem to work (i.e. it doesn't reset map to the view it had when I first loaded the page and goes to some random place). I'd say just remove this as it's not needed?
- "use my location" and "drag marker" tools populate the lat/lng fields but add too many decimal places. The values should be restricted to about 5 decimal places (~1m at equator - max accuracy for modern GPS)
- sub-headings of "A. Sightings Information" and "B. Species Information" should be removed. The former is too vague (the whole form is sighting information) and the latter has field headings which  highlight the functionality already. Furthermore the other sections have no sub-headings so it is inconsistent (e.g. no location section)
- the map goes grey when the focus is lost but there is a lag... this adds no value in my mind and is simply confusing, so remove this eye-candy
- identification tags drop-down list is too long - trying to choose an option further down the alphabet is too hard. Current sightings app uses 2 drop-downs (group & sub-group) as it avoids this issue
- "Attach photo" button should be closer to the "sighting photo" label/heading. On my screen they are split too far apart which is confusing. I'd suggest the button is left-justified with the other input widgets in that section
- form submit needs a "please read the terms..." with link text above. See current app: 
  ![image](https://cloud.githubusercontent.com/assets/532845/17953601/012b7eae-6ab8-11e6-9a24-2229bb8ad1cd.png)
- Map icons "drag marker" and "use current location" are too similar and thus confusing. Mouse-over text would help but even that is probably not enough. I'd prefer explicitly labelled text as well as icons, similar to what the current sighting app has
- the obligatory fields "latitude" and "longitude" provide no hint or suggestion that they should filled out in any other way except by typing in a value. But we don't want people to type in values if we can absolutely help it. So it needs a hint/help telling them to search or use my location.
- left column fields all have help icons but there are none on the right column (location fields) -> add help icons to all fields
- "Attach a photo" is at bottom of the form but the current sightings app has this as the second item a user interacts with - this is so we can get the date, time and location data from the photo first and auto-populate those fields. It is really annoying to users if they manually fill out those fields only to have the photo override them at the end
- default value for "how many individuals did you see" is 0. This field is not obligatory and so we will get lots of 0 values in data. Either make it obligatory (not 0) or default to 1
- clicking the "use my location" should also populate the "accuracy" and "source of coordinates" fields
- upload a photo labels and help text all suggest you can only upload a single photo. Multiple photos should be possible and the labels and help text should reflect this with "upload one or more photos..."
- "cancel" button at bottom of form should have a "are you sure..." modal popup to allow user to back out of action. The placement right next to the submit will result in people accidently clicking it and it results in all inputted data being lost

**Comment by sat01a** [comment]
Thanks Nick for taking  time to write up the requirements.

I moved this ticket to the top the todo list. So that next time around we can pick this one and get the changes done.

Migration script, rematching species with new GUID and new hub settings with ALA banner are ready. 
1. Migration script: @ /scripts/misc/importSightingsDataToEcodata
2. Rematching species with new GUID : Option added @ biocollect>admin>tools>rematch species guid.
3. ALA sightings hub settings config @ dev and test environment.
4. Survey/Form name: 0z Atlas Sightings.
