### ISSUE TITLE
Add ellipsis to facet sections

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#682]
Facet sections currently display a maximum of the top 20 items (alpha-numeric order) with no way to display and select from the full list when there are more than 20 items.

Add an ellipsis to pop-up a modal that behaves same as ALA and MERIT for view and select from more than just the max default display set. Should include the "includes/excludes" options as per ALA faceting.

Default display number should be max of 15 items

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-75
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-213
