### ISSUE TITLE
Fix rendering of "+ photo" button within tables on forms

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#695]
When the image datatype is used in tables, the "+ photo" button wraps unnecessarily and positions at the far right and off of the table.
Need to display as "unwrapped" when column width allows, position center in cell. Allow wrap only when column width does not allow default.

**Comment by sat01a** [comment]
Use Seagrass bed monitoring for testing

**Comment by sat01a** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-198
