### ISSUE TITLE
Remove row delete option in tables with fixed rows

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#696]

**Comment by pbrenton** [comment]
https://biocollect.ala.org.au/bioActivity/create/95ae9f55-d4c1-4ebe-a662-02864641ce8a

https://biocollect.ala.org.au/bioActivity/create/762c65a2-c63a-4615-821b-0eb45d024c34

... and others too.

Basically we need to add something to the JSON view model functions and terms for the "table" type, along the lines of "allowRowDelete": "false", with "true" being the default/non-explicit property.

**Comment by charvolant** [comment]
Fix pushed to branch https://github.com/AtlasOfLivingAustralia/biocollect/tree/issue-696

**Comment by charvolant** [comment]
Code review in https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-200

**Comment by javier-molina** [comment]
Code looks fine, only minor comment. Once the test deploy is ready I will do end to end testing before closing the ticket.
