### ISSUE TITLE
Errors in data download file

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#697]
The following errors in the data download file have been reported by a client and need to be fixed ASAP:
- [ ] DwC record tab is not showing a eventDate, recordedBy, eventRemarks, or locationRemarks columns. Should check dwcAttribute is properly mapped in the data model first and then fix if appropriate.
- [ ] Data tab - startDates and possibly endDates are displaying as UTC and need to be converted to local date/time as users can't make this conversion themselves.
- [ ] Data tab - eventDate is displaying as a wierd string (eg. au.org.ala.ecodata.metadata.OutputDataPropertiesBuilder$Value@11561e39). Need to display as local date. of recording.
- [ ] Data tab - survey event location information (including lat/long) is not displaying with the event record.

**Comment by charvolant** [comment]
Ecodata service generates XLS. Copied to https://github.com/AtlasOfLivingAustralia/ecodata/issues/320

**Comment by charvolant** [comment]
See https://github.com/AtlasOfLivingAustralia/ecodata/pull/325
