### ISSUE TITLE
Fix Image duplicate issue

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#699]

**Comment by charvolant** [comment]
See, also https://github.com/AtlasOfLivingAustralia/biocache-store/issues/164

**Comment by javier-molina** [comment]
Thanks @charvolant that will be handy.

**Comment by javier-molina** [comment]
From the 21353 image records in test:

There are no duplicate Id, or documentId

There are around 50 records without an actual url, and around 90 records without imageId Given the small percentage of records with these issues I would regard them as old data, I hence will move to implement pagination for the Images tab.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-196

**Comment by charvolant** [comment]
Code review complete
