### ISSUE TITLE
Saved locations don't appear to be working

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#718]
To reproduce:
1) Add a sighting: https://biocollect-test.ala.org.au/bioActivity/create/d57961a1-517d-42f2-8446-c373c0c59579?returnTo=%2FbioActivity%2Flist
2) After entering location details, press "Save location" (Location saved popup is displayed)
3) Save the record.
4) Navigate to "username -> my favourite sites"

Expected:
The site is displayed.

Actual:
No sites are displayed.

**Comment by temi** [comment]
fixed this issue. make sure matched locality is filled. some forms has automatic locality match on marker movement.
