### ISSUE TITLE
Species Configuration Issues - Survey Species Tab

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#728]
# **Summary**
When you go the Species Configuration section in the Survey Species Tab, the search for existing listings does not return results and the creation of a new lists always retrieves species with undefined Ids.

# **Search for an existing list - Steps to reproduce**
Once in the Species Tab

1. From the drop down list select 'A selection or group of species

1. Click Choose from existing species lists
(By default all the results are displayed in a paginated list)

1.  Use the autocomplete text box to search for a species (for example kangaroo)
The autocomplete will suggest various options

1.  Click search

**Expected** 
Lists containing the search criteria are displayed

**Actual**
Found: 0  species lists is displayed all the time.

**Nice to have**
Implement standard pagination controls as in Organisations and All records pages 

See images below for details

![screen shot 2017-01-13 at 9 50 34 am](https://cloud.githubusercontent.com/assets/8326394/21912982/948bf5e6-d97d-11e6-817c-611955d52ce3.png)

![screen shot 2017-01-13 at 9 50 50 am](https://cloud.githubusercontent.com/assets/8326394/21912986/9a4502ca-d97d-11e6-8331-e4ec8a3aef07.png)

# **Add a new list - Steps to reproduce**
1. From the drop down list select 'A selection or group of species

1. Click 'Add new species lists'

1. Click 'Search and add species name'

1. In the 'Search species' textbox  type a species name and select a species. 
The species selected will be displayed above the text box in red text

1.  Drag the species to the 'Species name (Comma separated)' text area

**Expected** 
The ID of the species is added

**Actual**
The value _https://bie.ala.org.au/species/undefined_ is always added

**Additional requirements**
- Instead of  using a comma separated textbox and drag and dropping results, add search results directly to a list of elements that can be removed such as the list used when adding existing species lists.

- It should be possible to add unmatched taxons not in ALA 

See images below for details

![screen shot 2017-01-13 at 9 51 42 am](https://cloud.githubusercontent.com/assets/8326394/21914592/5f8037da-d988-11e6-8845-845f672b523d.png)

This is a blocker for #603

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-209

**Comment by sat01a** [comment]
-
