### ISSUE TITLE
Hub configuration - Ability to set display visibility and sequence as well as default collapse/expand state of facet sections

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#743]
Need the ability to configure the visibility, display sequence, and the default expand/collapse state of each facet section.

**Comment by temi** [comment]
Added configurable facet for CS project finder.
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-73
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-211
