### ISSUE TITLE
Add a date range selector field to the available facet options

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#744]
Need to also be able to filter projects by date range as follows:

From date
To date

Result set to include projects with **project start date** >= the "from date" and <= "start date"

See implementation in https://fieldcapture.ala.org.au/home/projectExplorer. This may not quite work the same as needed in the BioCollect context due to the fact that many projects are ongoing and don't have end dates, but most of the code and built in functionality should be re-usable.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-212
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-74
