### ISSUE TITLE
Issues with maps configuration

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#746]

**Comment by javier-molina** [comment]
@pbrenton 
Is this for all table forms such as multi-sightings in CS or is it specific to works projects?

I will do my own testing shortly

**Comment by javier-molina** [comment]
For Sites in forms

If Allow Additional Survey Sites config checkbox is disabled then the controls to create new sites from a survey form should be disabled.

If Allow Additional Survey Sites is checked, any new sites created will be associated to the survey and not to the project.

A user should select either a site or drop a pin in the map. In the latter the latitude and longitude fields will be populated.

Question: Should latituted and longitud fields be hidden if a Site has been selected?

**Comment by javier-molina** [comment]
Confirmed point 1 and 2 are working as expected

Implemented 3 and 4

**Comment by pbrenton** [comment]
I think we need tool tips on the lat/long and centroid lat/long labels to explain what each means.

1 - 4 test OK

Can't change location settings if published and has data. Requested this to be changed too - see #603

**Comment by javier-molina** [comment]
From Peter:

> 
> [10:16 AM] Peter Brenton: Centroid latitude/longitude - "The coordinates of the calculated geometric centre of the drawn site polygon. The coordinate reference system used is WGS84 decimal latitude/longitude (EPSG 4326)"
> [10:18 AM] Peter Brenton: Latitude/longitude - "The actual coordinates of the site marker position on the map representing a point location for the record. The coordinate reference system used is WGS84 decimal latitude/longitude (EPSG 4326)"
