### ISSUE TITLE
Activity record not populating lat/long coordinates

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#756]
see http://biocollect.ala.org.au/bioActivity/index/17134e0f-9704-4367-87ec-04f0357fb4e0?returnTo=%2FbioActivity%2FallRecords

**Comment by qifeng-bai** [comment]
@pbrenton EventPhoto defined in view model does not exist in data model.  If you can correct the data model, the Lat/Lon will be shown.  Please modify the model
