### ISSUE TITLE
"Project participant" project role is broken

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#767]
To reproduce:
1) Add a user to a project with role "editor" or "admin"
2) Confirm the user has access
3) Edit the user access level to "project participant"

Expected behaviour:
User has the new access level.

Actual behaviour:
The user no longer appears on the project list and cannot be re-added.  The role is still in the database but is not returned in the access list nor does the role appear to grant access to add records to the project.

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-85

**Comment by javier-molina** [comment]
@sat01a @sathishala  I remember you said that the participants were added automatically for 'Allow public users to enter data' surveys and the role was hidden from the admin as per design. Is this still the case? Otherwise this fix should be the way to go.
