### ISSUE TITLE
images getting uploaded to dev

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#781]
It has come to my attention that ecodata is uploading images to images-dev.ala.org.au. This is impacting biocollect sightings.  Changing the variable to prod images might cause the exisiting images to be 'not found'. I am not sure of the impact on Fieldcapture.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-78
