### ISSUE TITLE
Browser compatibility bug - IE11

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#791]
Species name lookup is not working on the sightings form in IE11.

Urgent fix required

**Comment by javier-molina** [comment]
http://stackoverflow.com/questions/42533264/getting-error-promise-is-undefined-in-ie11

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-219

**Comment by pbrenton** [comment]
Thanks Javier, seems to be all good in IE now.
