### ISSUE TITLE
Survey settings > locations: Add config option to restrict to selected sites only (ie. no marker option)

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#792]
Add boolean config option to "Allow drop-marker for point locations"

If = true, display drop-marker on geoMap as per current behaviour
If = false, remove drop-marker from geoMap display

**Comment by javier-molina** [comment]
> [11:14 AM] Chris Godwin: Interestingly, the map doesn't even seem to work
> [11:14 AM] Chris Godwin: If you save a location, then edit that record the location is gone
> [11:14 AM] Chris Godwin: (in test & prod)
> [11:14 AM] Chris Godwin: (I thought my change was at fault for a bit)
> [11:16 AM] Javier Molina: Any particular form Chris? I was working with Maps last sprint and I didn't find any issues saving and editing maps
> [11:16 AM] Temi Varghese: seems alright on sightings
> [11:16 AM] Chris Godwin: ah that is good news.
> [11:16 AM] Chris Godwin: In test: https://biocollect-test.ala.org.au/bioActivity/edit/47e43dde-805e-4fa0-a8a6-9cebbf184d8c?returnTo=%2...
> [11:17 AM] Chris Godwin: that's the ALA test / bat survey
> [11:17 AM] Chris Godwin: In prod:
> [11:17 AM] Chris Godwin: https://biocollect.ala.org.au/bioActivity/edit/004c88c5-70b1-47cc-9cb6-a9458458db96?returnTo=%2Fproj...
> [11:18 AM] Chris Godwin: Basin champions Iconic species surveys
> [11:18 AM] Chris Godwin: Hopefully it's just a misconfiguration of the form
> [11:18 AM] Chris Godwin: The project breadcrumb is missing on the edit form for those two examples also
> [11:19 AM] Javier Molina: Ok will check those later
> [12:10 PM] Chris Godwin: It looks like the reason the site isn't loading for those projects is there is a site selected and a setting that says site or marker but not both
> [12:11 PM] Chris Godwin: as to how that is configured or why it let me add a marker in the first place I am not sure
> [1:08 PM] Javier Molina: The marker or site was added recently
> [1:09 PM] Javier Molina: I need to check records like the ones you pointed to see how exsiting data looks like and I might have missed.
> [1:41 PM] Chris Godwin: I had a chat with Peter, the problem seems to be if you have a site selection first, then a marker after and the map is configured as "either site or marker" then the marker isn't added on edit.
> [1:42 PM] Chris Godwin: Maybe in this case the incorrect behaviour is actually on the create page, maybe after a marker is added the site should be blanked
> [1:42 PM] Chris Godwin: although to me it would make sense to display both the site and marker on the edit page if that was what the display looks like on the create page?
> [1:43 PM] Chris Godwin: Peter probably has a better idea on how he wants to to behave
> [2:00 PM] Peter Brenton: ATM the create behaviour is: select a site (zooms in and displays the site - centroid coords shown), then select and place the marker --> site and centroid coords removed and replaced by marker and verbatim coords.
> [2:10 PM] Peter Brenton: This behaviour is OK and appropriate for some UC's (eg. https://biocollect.ala.org.au/acsa/bioActivity/create/faba119c-9086-490d-949c-b02bed1dce15), but not perfect for all situations.
> [2:12 PM] Peter Brenton: In this respect, create is working as expected, though I've created issue #792 to further improve functionality for broader use case support, which might help to improve the current bug in some cases.

**Comment by javier-molina** [comment]
Display correct site or pin on edit mode.

Default layer is now Google maps instead of Open Layers

https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-220

**Comment by chrisala** [comment]
This error can still be reproduced (in a slightly different manner) for projects configured with a single site:
1. Go to: https://biocollect-test.ala.org.au/bioActivity/create/07a18ffd-d6c2-4cd5-9d83-0811823d97a1
2. Complete the form, but make sure to "drop a pin" for site selection.  Save.
3.  Navigate to the data tab on the project, and "Edit" your new record.

Expected results:
* The lat/lon / pin you dropped should be displayed.

Actual results:
* The project site is selected and your pin is gone.  (previously it had a NaN for lat/lon)
