### ISSUE TITLE
Ecoscience project type - project metadata template not respecting content display rules

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#795]
Create new project
Select 'Ecological science' project type
Scroll down page - should not display citizen science 'science type' and CS 'Get involved' sections, but is.

This is in both test and prod environments

High priority issue

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-233
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-86
