### ISSUE TITLE
Ecoscience project type - Project displaying as a works/schedule type project instead of a survey/event type project

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#796]
Example: https://biocollect-test.ala.org.au/dehp-qld/project/index/f610339d-cb69-4fd7-ab91-e1986db3c372

Open project metadata page - Type of project = Ecological science

This is in both test and prod environments

High priority issue

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-233
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-86
