### ISSUE TITLE
Sightings links from Biocache not implemented

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#800]
Links from biocache to sightings (BioCollect)
1. The previous ALA sightings app implemented a URL to show sightings for a given user, using their ALA user ID. E.g. http://sightings.ala.org.au/spotter/13. Those links fail at the moment. They should go to a version of the "my sightings" page but for a specific user (not the logged in user).
2. When viewing an individual occurrence record in biocache (for a ALA sighting) we need to be able to link back to the original sighting record in BioCollect. This is not currently possible as BioCollect does not provide a URL to the original record when data is passed to biocache. E.g. http://biocache.ala.org.au/occurrences/db1cbc2c-7ac1-4533-8154-b756b42a40f0 should have a field which is either `occurrenceId` or `recordNumber`. See http://biocache.ala.org.au/occurrences/0758c2e9-c09d-4bb4-b42d-2f9a1d3cfc37 as an example.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-250
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-94

**Comment by tanmoy1048** [comment]
Although I have not understood all the business logic, the code's logic looks pretty sound to me.

**Comment by nickdos** [comment]
Re-opening either way - if not in prod, then not resolved and if not a URL then not resolved.

**Comment by nickdos** [comment]
Can't see any URL in JSON either @temi 

https://biocache.ala.org.au/ws/occurrences/7ff26f43-5c20-4ad8-afb7-5530a1c27c59

**Comment by temi** [comment]
@nickdos It is provided in recordNumber property. Below is an example of an example JSON.

>    {
            "dateCreated": "2016-08-25T23:51:19Z",
            "lastUpdated": "2016-08-25T23:51:19Z",
            "occurrenceID": "6f7e964f-8281-4e00-a919-3717ebf24183",
            "status": "active",
            "recordedBy": "Sathish Babu Sathyamoorthy",
            "rightsHolder": "Atlas of Living Australia",
            "institutionID": "Atlas of Living Australia",
            "basisOfRecord": "HumanObservation",
            "datasetID": "e61eb018-02a9-4e3b-a4b3-9d6be33d9cbb",
            "datasetName": "Individual sighting",
            "eventID": "c323d82b-a04b-4007-a7bd-ffa766a11e74",
            "eventTime": "09:49 AM",
            "guid": "urn:lsid:biodiversity.org.au:afd.taxon:5ed80139-31bb-48a8-9f57-42d8015dacbb",
            "name": "AVES (Birds)",
            "scientificName": "AVES (Birds)",
            "dataResourceUid": "dr364",
            "multimedia": [],
            "activityId": "c323d82b-a04b-4007-a7bd-ffa766a11e74",
            "decimalLatitude": -37.5097258429375,
            "decimalLongitude": 144.8602294921875,
            "eventDate": "2016-08-24T14:00:00Z",
            "individualCount": 1,
            "outputId": "8466b49d-4fa0-4275-a78a-1af2de12ba12",
            "outputSpeciesId": "6e6d6057-6f57-4139-b772-04cbca0cc7cf",
            "projectActivityId": "e61eb018-02a9-4e3b-a4b3-9d6be33d9cbb",
            "projectId": "f813c99c-1a1d-4096-8eeb-cbc40e321101",
            "userId": "8443",
            "coordinateUncertaintyInMeters": null,
            "generalizedDecimalLatitude": null,
            "generalizedDecimalLongitude": null,
            "json": null,
            "numberOfOrganisms": null,
            "outputItemId": null,
            "recordNumber": "https://biocollect.ala.org.au/sightings/bioActivity/index/c323d82b-a04b-4007-a7bd-ffa766a11e74",
            "projectName": "ALA species sightings and OzAtlas"
        }

**Comment by nickdos** [comment]
Thanks @temi I'll see if data team can work out why its not appearing on the records.

**Comment by sadeghim** [comment]
It's now fixed:
https://biocache.ala.org.au/occurrences/ddeac170-97c9-4dad-a279-029d270b65d5

**Comment by nickdos** [comment]
Thanks everyone - Patricia is adding a fix to auto-link URLs so it should be clickable in next version.
