### ISSUE TITLE
ALA Sightings feature - suggest an identification

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#801]
The previous ALA sightings app had a "suggest an identification" widget that was linked to the "record a sighting page". It was a modal (BS) popup window that used a location lat/lng to suggest which species were known to occur at that location. It was entirely JS driven, so should be easy to implement on new sighting page.

See 
https://github.com/AtlasOfLivingAustralia/pigeonhole/blob/master/grails-app/views/submitSighting/index.gsp#L194 (button trigger)
https://github.com/AtlasOfLivingAustralia/pigeonhole/blob/25a16f75fee23554005220d538d10835fd5436f4/grails-app/views/submitSighting/index.gsp#L399 (modal div)
https://github.com/AtlasOfLivingAustralia/pigeonhole/blob/25a16f75fee23554005220d538d10835fd5436f4/grails-app/views/identify/_widget_nomap.gsp (modal div body)
https://github.com/AtlasOfLivingAustralia/pigeonhole/blob/3829ea38cd3718b72a5153fe94c467496e99a8bf/web-app/js/submitSighting.js#L376 (JS trigger modal)
https://github.com/AtlasOfLivingAustralia/pigeonhole/blob/3829ea38cd3718b72a5153fe94c467496e99a8bf/web-app/js/identify.js (JS AJAX code)

AJAX code is JQuery only so it might be worth-while converting to KnockoutJS... this could be useful for other BioCollect projects?

**Comment by matilda2812** [comment]
Closing given move to iNaturalist
