### ISSUE TITLE
GeoMap object - Add support for line feature

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#806]
Add geoMap support for a multi-segment (continuous) "line" spatial feature to facilitate spatial definition of transects. This should be treated as a long thin (1m wide) polygon, defined as a fixed buffer around a drown multi-segment line feature.

**Comment by temi** [comment]
There is an existing issue - siteId is not saved in activity. This causes records to be created without lat & long. This issue will be fixed in #921.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-270
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-106
