### ISSUE TITLE
Report a sighting links from species pages do not check CAS

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#810]
If a user is **logged out** and they click the link to submit a sighting on a species page, e.g. on http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:251bf742-2d52-49ed-93d4-85d404719148 click on "Record a sighting" (http://sightings.ala.org.au//urn:lsid:biodiversity.org.au:afd.taxon:251bf742-2d52-49ed-93d4-85d404719148), they are presented with the sighting form. And when the user submits the record they get an "unauthorised" error.

The expected action, from the species page link, is to get redirected to the login screen.

**Comment by temi** [comment]
fixed. Changed CAS settings!
