### ISSUE TITLE
Improvements to All records api.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#811]
1. Project editor role can only edit his own records, but "All records view" shows edit option for all records.

2. Improve "All records" load time. (It appears, load performance is affected due to showCrud call)

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-222 
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-79
