### ISSUE TITLE
Recent/My Sightings not always displaying record detail

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#823]
Many records on the Recent Sightings page are missing the "image" and "identification" sections.  When viewing the record directly this information exists, so likely something has gone wrong with the indexing?

**Comment by javier-molina** [comment]
> Hi Peter,
>  
> On our Veteran and Significant Tree BioCollect site, the images form the records are not showing on the main ‘data’ tab (but you can see them when you click to view the individual records).  Also, the map function/tab is not working, saying “Displaying the first 10,000 records returned. Use filter to reduce the number of returned results and to view other records. - No Results”.
>  
> Since BioCollect is still somewhat being developed, it would be great to have “report a technical issue” link (that way you would not receive all these annoying emails from me!) JJ.
>  
> https://biocollect.ala.org.au/project/index/7144ebcd-13b5-471b-b7c9-07b979598d58#
> 
> Cheers,
>

**Comment by javier-molina** [comment]
@chrisala, @pbrenton, @sathishala 

The 'Significant Trees Survey' form used in the  Veteran and Significant Trees of the Redlands Survey does not contain any species fields, only a drop down with a selection of species hence it does not produce any records.

The data tab sources its content from the records hence no image is displayed if no records are present. I will try to figure out what it is required to source the image from the output for this scenario.

**Comment by javier-molina** [comment]
Further to the above, For the recent sightings I spotted records like the one below. These records for some reason didn't get an outputSpeciesId for the species field which is a requirement to generate a record entry for them, hence they are displayed only as an activity lacking the image.

https://biocollect.ala.org.au/sightings/bioActivity/index/a3fc6f26-2212-46b3-ba6c-cd04464e4076?returnTo=%2Fsightings%2FbioActivity%2FprojectRecords%2Ff813c99c-1a1d-4096-8eeb-cbc40e321101 

I could not spot an entry that had a record with an image but the latter was not displayed in the data tab / Recent sightings.
