### ISSUE TITLE
Record event dates in download

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#829]
Customer reported issue:
The downloaded data from the “Koala Action Group - Koala Count-a-thon” is still incorrect.  The downloaded data in the “The date on which the sighting was made” column is still one day behind the actual record date.  Any idea on when this may be fixed, as I really need this data to incorporate into our GIS ASAP.

https://biocollect.ala.org.au/project/index/edad0555-32a6-473e-8956-c70cf80329c4?version=

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-83
