### ISSUE TITLE
Error creating project - null

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#849]
There are quite a few errors in the ecodata logs of the form: 
2017-06-21 11:22:22,066 ERROR [ProjectService]  Error creating project - null
2017-06-21 11:22:22,066 ERROR [ProjectController]  Error creating project - null

User report indicate this is a genuine failure to create a project in BioCollect.
(there are also similar errors around sites in the logs)

**Comment by chrisala** [comment]
No javascript errors existed at the time the project creation failed, but the presence of a ;jsessionid in the URL may indicate some timeout related problems.

**Comment by patkyn** [comment]
Could not replicate the issue.

**Comment by qifeng-bai** [comment]
Possible related issues:
1, Some exceptions are suppressed on the middle.
2, Some API calls cause a runtime exception which is captured by a default error handler in controller - the default error handler returns an HTML page instead of JSON object
3, Some Ajax calls do not handle error callback

**Comment by qifeng-bai** [comment]
Some examples:  in project create call:
A project is inited in project.js. It refers fieldcapture-application.js to inherit  viewModel.saveWithErrorDetection. This method posts data via ajax to a service. 
In this method, it passes exceptions to a call back.

However, there is no error callback defined in the save method in create.gsp

**Comment by qifeng-bai** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-259
