### ISSUE TITLE
Email config in prod is not working

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#850]
Currently it's in amazon trying to use ironpot which is failing.

**Comment by matthewandrews** [comment]
I can set up system mail (postfix configured to send via Amazon SES) if that helps.

**Comment by chrisala** [comment]
Thanks Matt, that would help.  The host is biocollect.ala.org.au, MERIT is working OK (ecodata & fieldcapture).

**Comment by matthewandrews** [comment]
Actually, now that I look at it, I'd already set up system mail long ago - mail from the command line (e.g. mailx) works fine; it's currently sending via Google Apps SMTP.

**Comment by pbrenton** [comment]
Also see issue #918

**Comment by matthewandrews** [comment]
Fixed this morning on Biocollect production, by changing app config to point to localhost for mail (i.e. letting postfix do the sending).
