### ISSUE TITLE
Image dataType - Additional View config options needed

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#854]
Add more view configuration options to the "image" dataType to:
- allowImageAdd = true/false
- showMetadata = true/false

This is needed to support important client requirement.

**Comment by pbrenton** [comment]
Also see #890

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-258
