### ISSUE TITLE
Works project - Roles

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#855]
Works Project:
--------------
Roles needs to be refactored and tested 
Roles: Editor role, Admin role
Workflow testing with roles.
Implement, access control mechanism for  project home page
Lock message during edit mode.
Visible tabs for non members - About, Blog and resources.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-234
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-87

**Comment by javier-molina** [comment]
Admin -> Project Settings not available for a user added as admin in project.

**Comment by temi** [comment]
@javier-molina it should be fixed now.. how about putting the comments in Upsource next time?

**Comment by javier-molina** [comment]
Project admin is also missing access to works tabs, see screenshot below. 

![screen shot 2017-07-17 at 5 27 01 pm](https://user-images.githubusercontent.com/8326394/28258617-682e6e64-6b15-11e7-8d23-6d499299fb4b.png)

@temi  I find upsource most useful for code level comments, I spotted the issues I am commenting here without looking yet at the code.

**Comment by temi** [comment]
@javier-molina interesting. It does not happen for me on dev box or test. Can you test this on biocollect-test?

**Comment by javier-molina** [comment]
Roles working as expected. 

Warning message displays as expected too.
