### ISSUE TITLE
Search results must show :- Works project related records

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#856]
Similar to home page search, 'all records' must display hub specific records
The best and fastest way to achieve this is to copy all project properties into activity during indexing. It will then be easy to apply hub's defaultFacetQuery on activity.

Note: my data/records page is removed from this ticket since it is not mandatory for this release. It will be added in a seperate ticket.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-235

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-240
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-89
