### ISSUE TITLE
New works project default values (like: Programme names, countries.)

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#857]
**Countries and UN region**

- 'This project is run in the following countries' and 'This project is located in the following UN regions' fields need to be changed to mandatory fields.

The default values will be:

- UN region: Ocenania by default
- Country: Australia

This applies for all project types

**Program/Sub program**

1. If there is one program, it should inherit the default program name and be read only.
2. Editable if there is more than one program. Compulsory.
3. Subprogram is optional.
4. Program and subprogram need to be shown for all projects.

**Comment by javier-molina** [comment]
Hi @pbrenton 

When possible would you mind confirming what are the default values for new works projects?

Thanks
Javier

**Comment by javier-molina** [comment]
UN: Ocenania by default
Country: Australia

Both fields compulsory for all project type.

If there is one program, it should inherit the default program name and be readonly.

Editable if there is more than one program. Compulsory.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-243
