### ISSUE TITLE
Isolate lists creation rollback issue

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#859]
Notes from Chris:
I haven't had any problems via the lists web UI so it might be specific to either the web service or how BioCollect uses the web service

**Comment by javier-molina** [comment]
> [10:11 AM] Chris Godwin: Hi BioCollect people.  Who knows about the BioCollect species list functionality?
> [10:12 AM] Chris Godwin: It is superficially appearing to me that lists created in production (haven't tested test at this point) are disappearing into the ether
> [10:12 AM] Peter Brenton: Hi Chris, Javier did most of the recent work on that, but I can give you an overview.
> [10:13 AM] Peter Brenton: That is not good!
> [10:14 AM] Chris Godwin: I just created a couple of lists for survey, got back a drxxx number but if you search for, or type in the URL for the list the lists app tells you no such list exists
> [10:16 AM] Chris Godwin: mmm, it might be that the lists service is rolling back the transaction after assigning a number
> [10:17 AM] Chris Godwin: there are suspicious errors in the logs on lists.ala.org.au
> [10:17 AM] Javier Molina: Hi Chris
> [10:17 AM] Sathish Babu Sathyamoorthy: Did we deploy any new changes to  lists.ala.org.au?
> [10:19 AM] Javier Molina: Not sure what has happened to lists.ala.org.au but I remembered Chris mentioning in the past that indeed lists service was indeed rolling back changes from time to time and yet it returned a dr number
> [10:20 AM] Chris Godwin: I haven't had any problems via the lists web UI so it might be specific to either the web service or how BioCollect uses the web service
> [10:24 AM] Javier Molina: Is is easily reproducible or happens from time to time?
> [10:35 AM] Sathish Babu Sathyamoorthy: Added a ticket to address this issue (#859
> Isolate lists creation rollback issue) Please add any additional info to the above ticket. ta
> [10:47 AM] Chris Godwin: Not sure Javier, it happened to me twice in a row and to the customers list

**Comment by chrisala** [comment]
It appears to be reproducable.
Looks like the problem is the dataResourceUid assignment in the lists webservice:
Field error in object 'au.org.ala
.specieslist.SpeciesList' on field 'dataResourceUid': rejected value [null];
