### ISSUE TITLE
ALA sightings: implement new skin

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#868]
See https://github.com/AtlasOfLivingAustralia/ala-bootstrap2/tree/may2017redesign although changes may be in `master` by the time this issue is actioned.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-244
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-90
