### ISSUE TITLE
Change project funding to embedded table

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#874]
Change project funding from simple property value to a "Project funding" table with the following properties:

- **fundingSource**    (short text) description="The full name of the organisation providing funding or in-kind resources"
- **fundingType**     (selection - values={Public - commonwealth, Public - state, Public - local, Public - in-kind, Private - in-kind, Private - industry, Private - philanthropic, Private - bequeath/other, Private - NGO})   description="The type of funding source or in-kind resources"   
- **fundingSourceAmount**    (integer) description="The amount/cost in whole AUD of the funding or in-kind resources"
- **fundingTotal**  (integer) description="The total AUD cost of the project"

Present as a table embedded in the project metadata form in-lieu of the current "funding". Allow "addRow" in table and show fundingTotal as auto-calc sum of fundingSourceAmount

**Comment by sat01a** [comment]
https://biocollect-test.ala.org.au/works-test/project/edit/511cb57e-f379-4e47-963b-5e162db2d97d

**Comment by qifeng-bai** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-254
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-99

**Comment by qifeng-bai** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-269

**Comment by temi** [comment]
@qifeng-bai addition is not working
