### ISSUE TITLE
DQ/QA processes - Survey list and other pages - survey metadata

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#876]
The survey list page is currently only displaying a small subset of the metadata for surveys. 

Also needs:

1. Database update to include new attributes, 
2. Addition of all survey metadata on the appropriate spreadsheet tab of the download file and web service output
3. Addition of all appropriate survey metadata attributes to available indexed hub facet options (ie. - categorical, date and short text (eg. data custodian)).
4. Addition of text on the "Survey info" (metadata) page to assist users with understanding and valuing the need to capture metadata and interpreting the different metadata fields/components. _** Need to discuss details of this re. design and content.**_
5. Improve metadata entry page behaviour for survey method attributes. ie. Have radio button selector for  "Opportunistic/ad-hoc observation recording" OR "Systematic method-based survey". If former, pre-pop methodName field with "Opportunistic/ad-hoc observation recording". If latter, activate section for  the 4 method attributes, methodName being mandatory and at least one of the methodDescription, methodUrl or methodDocument also being mandatory.

We need to show all survey metadata on the list page - namely:
**Always visible**
- Survey name _(already there)_
- Survey description _(already there)_
- Dataset reliability tags _**(need to add, mandatory)**_
- Status _(already there)_

**Under elipsis** [ _show more_ ]
- Public access to data: (true/false)  _**(need to add)**_ [default=false, but auto-set =true if record count >= 1 AND record(s) not subject to embargo.]
- Data access method:  _**(need to add. mandatory)**_ [need to define behaviour rules]
- Data access external URL:  _**(need to add)**_ 
- Last Updated (most recent activity/record) _**(need to add, derived)**_
- Number of data recording events in the dataset (count of activity records) _**(need to add, derived)**_
- Number of species records in the dataset (count of species records) _**(need to add, derived)**_
- Survey (dataset) attribution/citation _**(need to add)**_
- Data Sharing License _(already there)_
- Legal Custodian of the dataset _**(need to add, update field to pre-pop with the name of the projectOrganisation and set as mandatory)**_
- Data management policy documented: (true/false [default])  _**(need to add)**_ [Also include doc upload/access and/or url link to site as per survey method. Store as a document associated with the project.]
- Data quality assurance method _**(new attribute, need to add, see vocabulary below, mandatory)**_
- Data quality assurance description _**(new attribute, need to add)**_
- Survey/sampling method used _**(need to add)**_
- Description of survey/sampling method _**(need to add)**_
- Web site of survey/sampling method _**(need to add as url link)**_
- Document of survey/sampling method _**(need to add as document icon linked to doc artefact - open in resources page viewer or new tab)**_
- Dataset Usage Guide _**(need to add)**_  (display only if field has content. Should change this to description of "Data biases and constraints" and maybe also add a vocabulary for these.) 

[NB. Only display if field has content]

Vocabularies
- [ ] Data access method - MANDATORY _[rules should apply to some of these options]_
      - Open access structured raw data download from this system
      - Open access opaque raw data file attached in this system
      - Limited structured raw data access in this system - via request (subject to embargo)
      - Opaque raw data file attached in this system - via request
      - Open access structured raw data download from external source
      - Closed access structured raw data download from external source
      - Raw data not available
      - Only derived/interpreted data products available

- [ ] Dataset reliability tags (select one (radio buttons) in each category. Also include a tool-tip for definitions of each traffic light for each property) - MANDATORY
      - Spatial accuracy confidence - HIGH [green]
      - Spatial accuracy confidence - MODERATE [Yellow]
      - Spatial accuracy confidence - LOW [red]
      - Species identification confidence - HIGH [green]
      - Species identification confidence - MODERATE [Yellow]
      - Species identification confidence - LOW  [red]
      - Species identification confidence - N/A [grey]    (species/taxonomy is not applicable for dataset)
      - Temporal accuracy confidence - HIGH [green]
      - Temporal accuracy confidence - MODERATE [Yellow]
      - Temporal accuracy confidence - LOW [red]
      - Non-taxonomic data accuracy - HIGH [green]
      - Non-taxonomic data accuracy - MODERATE [Yellow]
      - Non-taxonomic data accuracy - LOW [red]

- [ ] Data quality assurance method (present as multi-select) - MANDATORY
      - Data owner curated _**[default value = true]**_
      - Subject matter expert record verification _**[default value = false]**_
      - Crowd-sourced record verification _**[default value = false]**_
      - Record annotation _**[default value = false]**_
      - System supported data attribute configuration _**[default value = true]**_
      - No DQ methods used _**[default value = false, mutually exclusive from above methods]**_
      - Not applicable _**[default value = false, mutually exclusive from above methods]**_

![issue 876 - survey list page](https://user-images.githubusercontent.com/8119351/43507082-72ac4b48-95af-11e8-9f58-cb002cc94030.png)

**Comment by qifeng-bai** [comment]
@Rita-C  FYI

I have implemented the ticket #845 change free text to dropdown list. This task may affect yours
Instead of storing name of licence,  I store the url of licence .

The branch has not been reviewed yet 

What the branch does:
1, in controller:     def licences = collectoryService.licence()   to get all supported licences
2, in view, visible binding to show the related information about the selected licence
`                          <g:each in="${licences}">
                            <span data-bind="visible: dataSharingLicense() == '${it.url}'"><a href="${it.url}" target="_blank"><img src="${resource(dir: 'images/licence/', file: it.logo)} ">${it.description}</a> </span>
                        </g:each>`

**Comment by pbrenton** [comment]
My initial testing includes the following results:

1. "Allow public users to enter data" is pre-selecting as true, but should be false
2. "Species identification confidence" tag should have "Not applicable" as well, as not all surveys have taxa.
3. "Data Sharing License" needs to move to below the logo and above legal custodian
4. "Data quality assurance description" needs to be immediately below "Data quality assurance method"
5. "Data access method" should be multi-select and apply same mutual exclusivity rules as for DQ assurance method. Note also that we will need some descriptive text in these sections to guide users. Will supply this to you separately.
6. Grouped fields (ie. same concept and/or co-dependent behaviour) need to have a visual grouping/styling around them to visually indicate that they belong together.
7. "Survey/sampling method used" should be a select list from a methods vocabulary, but with a way to add to the vocab. My preference for this would be to have "Other" available in the select list, which on-select would present a text box to enter a new method. Should also include an icon beside the method selector to open a dialogue box to allow search & select of methods, which will be important as the method list grows and gets more complex types and versions of methods. Will also need a way for ALA_ADMIN editing of the list so that it can be updated with appropriate new methods.

Also, I can't test properly/fully because it has stopped saving changes.
