### ISSUE TITLE
Page refresh required after project resource upload

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#879]
Attached documents don't appear on the document or admin tab's until after a page refresh.

To reproduce:
1. Admin -> Resources -> Attach Document

Expected:
You can see the new document after the upload completes

Actual Results:
The upload appears to have failed until you refresh the page - at this point your new document is visible.

**Comment by Rita-C** [comment]
Fixed by code change in  AtlasOfLivingAustralia/biocollect#885.
