### ISSUE TITLE
Project admins cannot upload project resources

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#885]
To reproduce:
1. Login as a project admin, *that is not also an ALA admin*
2. Upload a resource on the admin tab.

Expected results:
The resource is uploaded.

Actual results:
After pressing "Save" on the document attach dialog, the page immediately refreshes, cancelling the upload request and preventing the upload from working.

**Comment by chrisala** [comment]
This is probably related to #879 - in the case you are an ALA admin, the upload succeeds, but the new document doesn't appear in the list until you manually refresh the page.

**Comment by Rita-C** [comment]
Review link: https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-246
