### ISSUE TITLE
Custom Hub - Title not displaying properly on project finder

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#887]
See title on https://biocollect.ala.org.au/project/projectFinder?hub=biocontrolhub#isCitizenScience%3Dtrue%26isWorldWide%3Dfalse%26max%3D20%26sort%3DdateCreatedSort

**Comment by temi** [comment]
@pbrenton A fix has been made to display hub title. However, the title is not appear still because the configuration for heading text is white colour. Changing it to black will help but that means it will make heading invisible on [home page](https://biocollect.ala.org.au/biocontrolhub).
