### ISSUE TITLE
Project finder facet block blind toggle styling & other minor styling issues

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#888]
1. The button background-color of the Project finder facet block blind toggle button is black, but should be grey.  See - https://biocollect.ala.org.au/project/projectFinder?hub=biocontrolhub#isCitizenScience%3Dtrue%26isWorldWide%3Dfalse%26max%3D20%26sort%3DdateCreatedSort
2. Some padding has suddenly appeared between the menu and main content sections in custom hubs (see example https://biocollect.ala.org.au/biocontrolhub). Please remove the padding.

These bugs seem to have been introduced at the last code update.

**Comment by temi** [comment]
@pbrenton 1 is caused by template configuration - Default button colour when hovering. This sentence does reflect its functionality. I am changing it to 'Default button colour when active'.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-271
