### ISSUE TITLE
Hub Config - Project finder template - Add option to hide and style "Getting started" and "what's this" buttons

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#889]
Need to allow configuration of the visibility and styling of the "getting started" and "What's this" buttons as current styling is poor and there are situations in custom hubs where they are not relevant.

**Comment by javier-molina** [comment]
This particular requirement is a duplicate for point 1 of #1010 which cover more exhaustive changes.

**Comment by javier-molina** [comment]
Tested ok
