### ISSUE TITLE
Add view model attribute parameter for public visibility

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#890]
Add a view model parameter to allow individual attributes to hidden from public visibility and visible to only project members (and ALA admins). This visibility must extend also to data visibility in record downloads.

Suggested format:
"memberOnlyView": "true"

default status to remain as current, ie. everything is publically visible unless the above is explicitly included and is true.

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-257

**Comment by Rita-C** [comment]
Hi @pbrenton cc @sat01a,
Download has been implemented as to hide member only fields on the survey sheets, the dwc records sheet shows all dwc fields assuming they are not supposed to be hidden.
