### ISSUE TITLE
Survey metadata - Add methodUrl and methodAssociatedMedia attributes

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#891]
Globally there is an increasing need to provide evidence of the methods applied to capturing data. This is often an indicator of DQ and fitness for purpose, and also importantly helps to contextualise appropriate usage of the data. Sometimes methods are published elsewhere in other web resources or in document or video.

We currently support a methodName (samplingProtocol in DwC terms) and a methodDescription, but these need to be **augmented by allowing linkage to external resources and upload of document/media artefacts which fully describe a method**.

This will ensure that BioCollect stays aligned with global developments in this space.

**Comment by sat01a** [comment]
Additional fields to survey metadata:
methodUrl
Needs to be displayed on the survey list page (with more option).

Document upload:
Upload method document > methodAssociatedMedia

**Comment by Rita-C** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/pull/960
