### ISSUE TITLE
ALA Sightings enhancements

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#894]
I've had a few requests for this and Taryn has passed on feedback from school groups who also want these features.

- [x]  Move the link "Occurrence Explorer" from next to "Recent sightings" to being placed in or above the list or sightings. See screenshot below

- [x] The occurrence explorer URL should change depending on the "result" set, so it shows the corresponding records in biocache for what the user is seeing in BioCollect (e.g. my sightings, recent sightings, any selected **facets**, etc.)

- [x] Similarly the "map" tab should have a button to take the user to the Spatial Portal for the given search. Including any facets or other filtering the user has done (where possible). The SP uses the same parameters as biocache, so should be easy to implement. E.g. if the biocache URL is https://biocache.ala.org.au/occurrences/search?q=*:*&fq=(data_resource_uid:dr364)&fq=alau_user_id:13, then the SP URL is http://spatial.ala.org.au/?q=*%3A*&fq=%28data_resource_uid%3Adr364%29&fq=alau_user_id%3A13

Screenshot of mockup (ignore big arrow):

![recent_sightings___bio_collect](https://user-images.githubusercontent.com/532845/29645336-3146f54c-88c0-11e7-9238-0a59b956fe11.png)

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-253
