### ISSUE TITLE
Survey activity comments broken

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#897]
Example: https://biocollect.ala.org.au/ala-cs/bioActivity/index/f2f930fe-4557-4ef5-bb37-9b34bac89787;jsessionid=19D36E083223D9400AD0F7F522F4DF42;jsessionid=F7314EFAEBBB36ECBA2870477F54E8B8?returnTo=%2Fala-cs%2Fproject%2Findex%2F05029324-4bd6-4d3c-b960-366b4bf0ae31

Console log:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by qifeng-bai** [comment]
http://devt.ala.org.au:8080/ecodata/ws/comment

Failed calling web service. No signature of method: static java.net.URLEncoder.encode() is applicable for argument types: (java.lang.Boolean, java.lang.String) values: [true, UTF-8]
Possible solutions: encode(java.lang.String), encode(java.lang.String, java.lang.String), encodeAsJs(), decodeJs(), hashCode() URL= http://devt.ala.org.au:8080/ecodata/ws/comment.

**Comment by qifeng-bai** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-247
