### ISSUE TITLE
Project page load issue with sightings project.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#898]
Sighting project takes long time to load:

https://biocollect.ala.org.au/ala/project/index/f813c99c-1a1d-4096-8eeb-cbc40e321101?version=

**Comment by qifeng-bai** [comment]
Default pagination of Knockout JS loads up all records and render them together. That slows down the process.  The size of page is 27.5M

**Comment by qifeng-bai** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-92
