### ISSUE TITLE
Home page - initial load issue

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#90]
* Performance, possibly caused by retrieving all Projects and paging on the client side.
* Investigate quick solutions
* Alternatively, push paging into the server side

**Comment by temi** [comment]
now paging, querying is done on server side.
project finder page is used in other gsp pages like organisation and my project. The change will support all these dependencies.

**Comment by m-r-c** [comment]
Biocollect pull request: https://github.com/AtlasOfLivingAustralia/biocollect/pull/159
Ecodata pull request: https://github.com/AtlasOfLivingAustralia/ecodata/pull/133

**Comment by m-r-c** [comment]
Reviewed. Just a couple changes suggested in ecodata.
