### ISSUE TITLE
Cannot delete an image blog entry

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/biocollect#900]
To reproduce:

- Login and find a project you have Admin rights
- Go tot Admin ->Edit Blog
- Add a new blog entry with image
- Delete the entry

Expected results:
The blog is removed.

Actual results:
The blog is still there.

**Comment by temi** [comment]
@Rita-C  can you pls create code review for this issue?

**Comment by Rita-C** [comment]
@temi , here is the link https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-260
