### ISSUE TITLE
Add new home page facet.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#901]
1. Add "Contributing data to ALA" facet
2. Increase elastic search score for the following fields on homepage index:
Title/project name, Description, Organisation name.

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-251
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-96
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-97
