### ISSUE TITLE
Project finder page - Button styling issue in configurable hubs

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#912]
Some buttons (eg. the facet panel toggle button and the geographic filter button) turn black when onSelect=true. These 2 buttons should remain the same colour as  their off/false state or behave the same as the select=true colour for sort and display options on the project finder page.

**Comment by pbrenton** [comment]
Also see issue #888

**Comment by temi** [comment]
fixed in #888
