### ISSUE TITLE
External Projects > Implement delete with warning/confirmation message

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#92]
* Implement soft delete for projects and all related records
* Possible bug with updating the index to remove deleted records

**Comment by m-r-c** [comment]
When an external project is deleted, the Project entity's status is set to 'deleted', but the associated Site entity is not. The Site's projectId is cleared, leaving an orphan record.

Is that correct?

**Comment by m-r-c** [comment]
Permissions are 'hard deleted', but the project is soft deleted.

**Comment by sat01a** [comment]
Requirements around sIte delete needs to be ironed out. I will raise a seperate ticket.

**Comment by m-r-c** [comment]
Permissions will be changed to soft deletes under #96. Sites will be covered under a separate task. 

Merging.
