### ISSUE TITLE
Biocollect 4.0 production release

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/biocollect#925]
Document required manual changes
Do the following
- ecodata 1.34.1
- biocollect 4.0.2
- run script migrateProjectFinderFacets.js
- set facet configuration for hubs -sightings and ala
- run updateAllowPloygonsForExistingRecords.js
- run createSiteFromPointCoordinates.js
- run updateActivitySiteId.js
- uriFilterPattern=./user/.,.*/site/(?!(index|list|elasticsearch|getImages|getPoiImages|ajaxUpdate))

**Comment by Rita-C** [comment]
The script updateRecordDocument.js in ticket #907 needs to be run in ecodata to update the migrated sightings record with document id. This is to enable download to retrieve the document for the multimedia

**Comment by temi** [comment]
updateRecordDocument.js was run on 26/10 when releasing the fix for downloads issue to production.

**Comment by sat01a** [comment]
update biocollect config.
uriFilterPattern=.*/user/.*,.*/site/(?!(index|list|elasticsearch|getImages|getPoiImages|**ajaxUpdate**))
