### ISSUE TITLE
Sightings map issue

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect#929]
The map for the ALA sightings is not allowing user to search for a locality. The locality search works as expected but after the marker is placed on the map, it is NOT updating the lat/lng fields. Also, the marker is not able to be moved once the locality sets the marker on the map, thus there is no way to set the (required) lat/lng fields and user is "stuck".

A user has reported this issue earlier to day. I also couldn't get it to work on Chrome (Mac).

**Comment by sat01a** [comment]
Spinning icon issue.

**Comment by qifeng-bai** [comment]
Fire events of 'dataloading' and 'dataload' to start spinning and stop. However, if map.panto, map.zoomto or maybe others is called after dataloading event is fired and before 'dataload' event is fired, the spin icon will stay on the map. 

Do not know why

**Comment by qifeng-bai** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-15
