### ISSUE TITLE
Internal Projects > Fix UI issues

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#93]
* The banner does not display with the correct size when the page loads (may depend on which tab you landed on after navigating to the page)
* The site map also sometimes does not display (possibly an issue with initialising google maps before the div is visible, resulting in a 0x0 map)
  * To reproduce, open a project, select a different tab (doesn't matter which as long as it is not About), go back to the home page and then open the project again. You should land on the tab you selected before: click the About tab now -> the map will not be displayed correctly.
* Add a "loading...." spinner or equivalent while the page loads

**Comment by m-r-c** [comment]
_Banner:_
The problem was with the loading of the carousel behaviour. Since this is not required for the first release (we only support 1 image), I have removed the carousel and fixed the CSS of the image and caption.

_Map:_
The problem was due to trying to load the map when the surrounding div was not visible (i.e. when you land on a tab other than About). The fix was in 2 parts: 1) Change the mechanism for loading the map to use google map's ```addDomListener```'s load event, and only initialise the map if the div is visible (i.e. the map is only initialised on page load if the user is landing on the About tab); 2) add a knockoutjs click event to the About tab icon to initialise the map (if it is not already initialised) when the user selects the About tab.

**Comment by m-r-c** [comment]
To Test:
_Banner:_

1. Edit a project add a banner image
1. Go back to the project finder page
1. Select the project
1. Go to the about tab
1. Verify that the banner image is correctly displayed
1. Edit the project, remove the banner image and add a Website
1. Go back to the project finder page and select the project
1. Verify that the 'Visit us at' text & website URL are displayed without the banner.

_Map:_
1. Go the project finder page
1. Select a project
1. You should land on the About tab
1. Verify that the map is displayed with the correct region, and that the zoom controls are visible.
1. Select another tab
1. Go back to the project finder page
1. Select the project again
1. You should land on the tab you had selected before
1. Select the About tab
1. Verify that the map is displayed with the correct region, and that the zoom controls are visible.

_Spinner:_
1. Go the project finder page.
1. Verify that the "Loading..." spinner displays while the project list is being processed
1. Select a project
1. Verify that the "Loading..." spinner displays while the project page is loading.

**Comment by sat01a** [comment]
Banner appears looks bit awkward. (refer attachment
(I have already merged it.)
![screen shot 2015-10-22 at 10 43 49 am](https://cloud.githubusercontent.com/assets/4197871/10653293/d400fc0c-78a9-11e5-9080-728b9eb45637.png)
)

**Comment by m-r-c** [comment]
Updated to make sure the banner image is always full-width
