### ISSUE TITLE
Add facets for survey year and month

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#937]
Currently activityLastUpdatedMonthFacet and activityLastUpdatedYearFacet is used. This is not necessarily when survey was conducted. Add new facets to solve this issue. This is important since we are linking with ALA system where survey month, year is used.

**Comment by temi** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-264
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-103

**Comment by sat01a** [comment]
Review completed.
