### ISSUE TITLE
Survey Settings > Incorporating UAT feedback 

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#94]
Add tooltip and explanatory text to pages. PB to provide text.

**Comment by pbrenton** [comment]
See attached for content.

Also, it would add usability value to show the tab header text ("Step n of ...") as an on-hover tool-tip on the tabs themselves as well as a heading on the tab page itself.  This will make them more obvious as tabs and reinforce the workflow nature of the survey configuration process.

[BioCollect survey config tool-tips.xlsx | uploaded via ZenHub](https://files.zenhub.io/56315fdfa8c15a0a3edc1657)

**Comment by pbrenton** [comment]
Per discussion with Sathish, please note the following amendments to the above:
1) add "next" buttons to each tab beside the Save button
2) add a new tab to publish as part of the workflow and move the publish function from the Info tab to the new publish tab
3) Add heading text on the publish page as: "Step 6 of 6 - Publish the survey to enter data" with sub-heading text as: "The survey must be published to be accessible on the survey list for data entry." The save button on this page (no next button) will save and open the survey list page.
4) When survey status ="published", the publish tab will display the Unpublish button and text immediately above "Unpublishing this survey will remove it from the survey list and allow you to change configuration settings. However, you cannot unpublish the survey whilst it has data associated with it as changing survey settings may adversely affect existing data. Therefore records must be deleted before the survey can be unpublished.
Are you sure you want to proceed? <Unpublish>"
5) When survey status="published", add a clear message to each of the species, location and survey form tabs advising the following: "Whilst the status of this survey is "Published" settings on this page cannot be changed. See the Publish tab for more information." Use the same green "Published" indicator/logo from the Info tab in place of the word in "... is "Published" settings ..." above.

**Comment by sat01a** [comment]
Ecodata PR >> https://github.com/AtlasOfLivingAustralia/ecodata/pull/143
