### ISSUE TITLE
Data migrations BDRS --> BioCollect - Biocontrol hub

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#940]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 31  (http://root.ala.org.au/bdrs-core/wbiocont/admin/home.htm)

- [ ] BDRS survey id = 360  to BioCollect survey id = f6408b80-8e9b-4baf-bb21-5b09cb5c44c9
- [ ] BDRS survey id = 358 to BioCollect survey id = 29b423b0-f6b7-4cf5-93f4-619dbbacfe5a
- [ ] BDRS survey id = 359 to BioCollect survey id =  2d1020c3-81c3-4f99-97ea-7e160105650b
- [ ] BDRS survey id = 183 to BioCollect survey id = ed152222-d29b-4816-afda-5aedc1b11f98
- [ ] BDRS survey id = 119  to BioCollect survey id = dc1db4c0-0b58-4c66-aac4-eb346df52830
- [ ] BDRS survey id = 144  to BioCollect survey id = b7bf8a26-7dd5-43f1-a3d4-92bfcb15ba55
- [ ] BDRS survey id = 118  to BioCollect survey id = 6ca77990-4fc9-46e4-b2dc-75a5e39056ee
- [ ] BDRS survey id = 117 to BioCollect survey id = 7021572d-5fed-4d07-b807-905a9fac1d79
- [ ] BDRS survey id = 105 to BioCollect survey id =  c30a71fc-0a8e-4594-aae1-55d91870737f
- [ ] BDRS survey id = 142  to BioCollect survey id = 4d12bf79-73f9-4183-b857-cf11104ed8e1
- [ ] BDRS survey id = 131  to BioCollect survey id = b6d004d3-752b-4348-be0b-1ee54c03611f
- [ ] BDRS survey id = 137  to BioCollect survey id = 03c940a2-a4c0-4aee-98f0-6267a91fbc06   (note that there are already some records logged in this BioCollect survey)
- [ ] BDRS survey id = 104 to BioCollect survey id = eeb62aff-56c6-4daf-a1d5-242bea84de1f
- [ ] BDRS survey id = 172 to BioCollect survey id = 5a8e7dc1-dd3c-426e-b39f-9cf58154c680
- [ ] BDRS survey id = 171 to BioCollect survey id =  b44bdae9-4810-4ce5-b8fc-aba23e25d663
- [ ] BDRS survey id = 164 to BioCollect survey id = b9e64489-f788-4c0a-bc76-f064679e5659
- [ ] BDRS survey id = 140 to BioCollect survey id = 304a3650-df94-4eb3-b32c-06a692c52b1b   (note that there are already some records logged in this BioCollect survey)
- [ ] BDRS survey id = 161 to BioCollect survey id = d716eee9-00fd-4377-8f61-da62cf50ae92
- [ ] BDRS survey id = 139 to BioCollect survey id = 730b1efb-fef5-455e-abc5-d061375772b5
- [ ] BDRS survey id = 116 to BioCollect survey id = e42e6278-4882-4938-8959-372cae4b6532
- [ ] BDRS survey id = 115 to BioCollect survey id =  7200f135-5fb7-49ca-8d87-edce4f29a5c3
- [ ] BDRS survey id = 158 to BioCollect survey id = 51b84973-1e75-4367-bd6d-6dfb562cec87
- [ ] BDRS survey id = 124 to BioCollect survey id = d4642eb4-8760-4ace-b04a-d23b827d2f80
- [ ] BDRS survey id = 125 to BioCollect survey id = a7320516-c49a-469a-8227-56788b0153ef
- [ ] BDRS survey id = 126 to BioCollect survey id = 32e61e30-8944-481f-94c6-fbd520156cee
- [ ] BDRS survey id = 103 to BioCollect survey id = b71bfe15-512c-4237-8a79-04178f104744    (note that there are already some records logged in this BioCollect survey)
- [ ] BDRS survey id = 112 to BioCollect survey id = b2405cd0-b518-45c9-a55a-5e8a9d132900
- [ ] BDRS survey id = 110 to BioCollect survey id = 705265bf-fda6-4a5e-a288-dce99527c75c    (note that there are already some records logged in this BioCollect survey)
- [ ] BDRS survey id = 111 to BioCollect survey id = 5175e1bf-f88c-41fa-a1a9-5fa44babd3dd
- [ ] BDRS survey id = 100 to BioCollect survey id =  0d9feb9f-4204-4a30-87e6-36af0670a738
- [ ] BDRS survey id = 113 to BioCollect survey id = c4470bac-0419-4eef-884a-670a6b05bfdb
- [ ] BDRS survey id = 114 to BioCollect survey id = 3ae1508e-ef66-4d36-91c0-02d26004d8d7
- [ ] BDRS survey id = 108 to BioCollect survey id = 44c2d038-1d57-44b1-9ae1-a71e6e996dec
- [ ] BDRS survey id = 102 to BioCollect survey id = 4c3b60dd-2b40-4bc4-b4d5-997eaf91af5d
- [ ] BDRS survey id = 107 to BioCollect survey id = 34e3f9d7-422f-49a2-8a1c-252fc1f12559
- [ ] BDRS survey id = 130 to BioCollect survey id = 9ea3b0fa-4359-4f81-9df3-464af1285931
- [ ] BDRS survey id = 127 to BioCollect survey id = 8da35bbe-cccb-4e4c-bde6-2648f860cab3
- [ ] BDRS survey id = 129 to BioCollect survey id =  f23916da-1ca2-490b-a56c-13f5464e66ed
- [ ] BDRS survey id = 128 to BioCollect survey id = e5914ac0-9d86-48d2-a725-86bd79b705d8
- [ ] BDRS survey id = 132 to BioCollect survey id = 6aa5f403-e218-4799-b1bf-c66798de821d
- [ ] BDRS survey id = 101 to BioCollect survey id = 13b7e9ab-1c37-4c83-bb96-907233c93d9f
- [ ] BDRS survey id = 90 to BioCollect survey id = 486d5fd3-a41a-4d6c-908b-b3f01fbe1e66
- [ ] BDRS survey id = 157 to BioCollect survey id =  d2b18987-2f7e-41c2-b2ac-a2793a125c93
- [ ] BDRS survey id = 120 to BioCollect survey id = d4985adf-7880-4fbd-84a9-3635c22572b4
- [ ] BDRS survey id = 121 to BioCollect survey id = f522c889-7282-43e1-a61f-a79a51cb3e2a
- [ ] BDRS survey id = 122 to BioCollect survey id = 452eacb1-94b0-4c7a-b702-ee11a33e0d98
- [ ] BDRS survey id = 99 to BioCollect survey id = 47dfddb0-47c7-4f31-b476-dabdd46a07e7

**Comment by chrisala** [comment]
Surveys have been processed and uploaded
