### ISSUE TITLE
Data migrations BDRS --> BioCollect - SA Murray-Darling Basin

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#941]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 54
(http://root.ala.org.au/bdrs-core/mdnrm/home.htm)

- [x] BDRS survey id = 324 to BioCollect survey id = 15ad05d9-74f3-49a9-aa62-e1f167406bdb   (note that there are already some records logged in this BioCollect survey)
- [x] BDRS survey id = 316 to BioCollect survey id = 62cb12cd-0e5c-40f2-8ce4-ccf0cb4a5f38   (note that there are already some records logged in this BioCollect survey)
- [x] BDRS survey id = 287 to BioCollect survey id =  [survey not yet created]   (note that there are already some records logged in this BioCollect survey)

**Comment by matilda2812** [comment]
done
