### ISSUE TITLE
Data migrations BDRS --> BioCollect - Goanna Watch

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#942]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 
(http://root-uat.ala.org.au/bdrs-core/unisa/admin/home.htm) - note this one in on the UAT server

- [ ] BDRS survey id = 365 (species = Varanus gouldii) to BioCollect survey id = fc89081b-fe0f-442d-9016-a8e6d1a658dd
- [ ] BDRS survey id = 365 (species = Varanus varius)  to BioCollect survey id = 534dfa1c-5b78-480e-9eb5-f26d087f9a77
- [ ] BDRS survey id = 365 (species = Varanus giganteus)  to BioCollect survey id =  dc147397-82c0-4754-854f-8014b8d0d470#
- [ ] BDRS survey id = 365 (species = Varanus rosenbergi)  to BioCollect survey id =  6ea589d6-252e-40ea-b63a-4b980dd7d8a1
- [ ] BDRS survey id = 365 (species = Unknown Goanna)  to BioCollect survey id =  e14a3597-3dea-403b-845d-afee66beb5d1

**Comment by chrisala** [comment]
Updated survey xls produced and attached.
