### ISSUE TITLE
Data migrations BDRS --> BioCollect - ACT & Southern Tablelands Weed Spotter

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#945]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 41
(http://root.ala.org.au/bdrs-core/act-esdd/home.htm)

BDRS survey id = 169 to BioCollect survey name = 
BDRS survey id = 206 to BioCollect survey name = 
BDRS survey id = 170 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
https://biocollect.ala.org.au/acsa/project/index/2a186934-8692-4a17-ba79-eb69cdf70fb4
