### ISSUE TITLE
 Data migrations BDRS --> BioCollect - Great Vic Koala Count

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#947]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 67
(http://root.ala.org.au/bdrs-core/gvkc/home.htm)

BDRS survey id = 330 to BioCollect survey name = 
BDRS survey id = 338 to BioCollect survey name = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
data migrated directly to ALA
