### ISSUE TITLE
Data migrations BDRS --> BioCollect - GER K2C species

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#948]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 13
(https://root.ala.org.au/bdrs-core/portal/13/home.htm)

BDRS survey id = 29 to BioCollect survey name = 
BDRS survey id = 35 to BioCollect survey name = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
Data moved directly to Atlas
