### ISSUE TITLE
Data migrations BDRS --> BioCollect - Australian Bat Ecolocation Database

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#949]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 27
(https://root.ala.org.au/bdrs-core/portal/27/home.htm)

BDRS survey id = 67 to BioCollect survey name = 

Need to create forms in BioCollect to hold the data

Dependent on support for audio data type

**Comment by matilda2812** [comment]
No data in BDRS
