### ISSUE TITLE
Internal Projects > Survey workflow change to lock species, form and location selection

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#95]
Do not allow surveys with submitted records to be changed.

* The Publish/Unpublish button will allow a survey to be shown/hidden on the surveys tab.
* Disable Unpublish if there have been records submitted for that survey
* Add text saying that the survey cannot be edited because records exist - to edit the survey, delete all records.

**Comment by sat01a** [comment]
Note: Disable publish button not implemented.

**Comment by m-r-c** [comment]
Testing failed - you can still modify the survey constraints even when there are records

1. Edit a survey with records.
1. Change the species constraint
1. Go to the info tab
1. Save
-> The constraints have now been saved.

**Comment by m-r-c** [comment]
I would recommend disabling the fields that cannot be edited. That way it will be more obvious to the user, and you won't need to try and selectively update data that has been changed.

**Comment by sat01a** [comment]
Fixed the bug and also disabled unpublish button.
