### ISSUE TITLE
Data migrations BDRS --> BioCollect - Condamine Alliance

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#950]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 29
(https://root.ala.org.au/bdrs-core/portal/29/home.htm)

BDRS survey id = 188 to BioCollect survey name = 
BDRS survey id = 211 to BioCollect survey name = 
BDRS survey id = 89 to BioCollect survey id = 
BDRS survey id = 179 to BioCollect survey id = 
BDRS survey id = 94 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
data moved to ALA directly.
