### ISSUE TITLE
Data migrations BDRS --> BioCollect - Hume Forests

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#951]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 57
(https://root.ala.org.au/bdrs-core/humefrst/home.htm)

BDRS survey id = 300 to BioCollect survey name = 
BDRS survey id = 301 to BioCollect survey name = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
Done
