### ISSUE TITLE
Data migrations BDRS --> BioCollect - Natural Resources Eyre Peninsula

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#952]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 53
(https://root.ala.org.au/bdrs-core/portal/53/home.htm)

BDRS survey id = 285 to BioCollect survey name = 

Need to create forms in BioCollect to hold the data and also to provide support for bird quiz files as resources

**Comment by matilda2812** [comment]
migrated to biocollect: https://biocollect.ala.org.au/acsa/project/index/c32d1811-afbc-410d-b68b-4835ba2dc7a5
