### ISSUE TITLE
Data migrations BDRS --> BioCollect - Mangrove Watch

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#954]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 63
(http://root.ala.org.au/bdrs-core/portal/63/home.htm)

BDRS survey id = 318 to BioCollect survey name = 
BDRS survey id = 323 to BioCollect survey name = 
BDRS survey id = 317 to BioCollect survey id = 
BDRS survey id = 320 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data

Contact Norm Duke about this

**Comment by matilda2812** [comment]
loaded here: https://biocollect.ala.org.au/acsa/project/index/5a0714b4-f1ef-4479-8ac0-285e0315d55c
