### ISSUE TITLE
Data migrations BDRS --> BioCollect - OEH Superb Parrot

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#962]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 61
(http://root.ala.org.au/bdrs-core/portal/61/home.htm)

BDRS survey id = 307 to BioCollect survey name = 
BDRS survey id = 308 to BioCollect survey name = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
done
