### ISSUE TITLE
Data migrations BDRS --> BioCollect - NT WildWatch

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#963]
Decommission BDRS ACT water watch and notify clients.

Export data from BDRS.
Use ACT scripts and migrate form 1 data
Use ACT scripts and migrate form 1 data
Use ACT scripts and migrate form 3 data
Testing & Review

Migrate record level data (including record images and record submitter names) from BDRS portal id = 66
(http://root.ala.org.au/bdrs-core/portal/66/home.htm)

BDRS survey id = 346 to BioCollect survey name = 
BDRS survey id = 347 to BioCollect survey name = 
BDRS survey id = 348 to BioCollect survey id = 
BDRS survey id = 349 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data

**Comment by chrisala** [comment]
The survey data has been processed and uploaded to the drive.
