### ISSUE TITLE
Data migrations BDRS --> BioCollect - SA SE NRM

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#964]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 47
(http://root.ala.org.au/bdrs-core/senrm/home.htm)

BDRS survey id = 242 to BioCollect survey name = 
BDRS survey id = 304 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
done
