### ISSUE TITLE
Data migrations BDRS --> BioCollect - SA AMLR

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#965]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 33
(http://root.ala.org.au/bdrs-core/amlr/home.htm)

BDRS survey id = 249 to BioCollect survey name = 
BDRS survey id = 250 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
done.
