### ISSUE TITLE
Data migrations BDRS --> BioCollect - ACT WaterWatch

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#966]
Tasks:
----------------------------------------------------------------------------------------
Decommission BDRS ACT water watch and notify clients.
--
Export data from BDRS.
Data Mapping - Update and match BioCollect Form 1
Data Mapping - Update and match BioCollect Form 2
Data Mapping - Update and match BioCollect Form 3
Client sign off. (Non-dev)
Write script and migrate form 1 data
Write script and migrate form 2 data
Write script and migrate form 3 data
Testing & Review

----------------------------------------------------------------------------------------

Migrate record level data (including record images and record submitter names) from BDRS portal id = 21
(http://umwaterwatch.ala.org.au/bdrs-core/portal/21/home.htm)

BDRS survey id = 332 to BioCollect survey id = b3efa2eb-ed40-4dc8-ae0a-0c9f0c25ab0e
BDRS survey id = 333 to BioCollect survey id = 386e479e-2fe7-4ae1-b505-bf1998f0732f
BDRS survey id = 334 to BioCollect survey id = 30b265b1-5aac-47eb-8131-11eaaafc8219
BDRS survey id = 335 to BioCollect survey id = b72699e9-80ac-4bbe-8a12-d42d08d93cfc
BDRS survey id = 336 + 337 to BioCollect survey id = 179bc591-7e62-4a92-9d20-c4f1259ffc82
BDRS survey id = 281 to BioCollect survey id = 49c36965-ee68-47e3-8847-4187005c7ace
BDRS survey id = 259 to BioCollect survey id = 63f606d1-dc4e-41dc-8550-e3a4b46a8886
BDRS survey id = 278 to BioCollect survey id = 9a7167d5-1dcb-46a1-9804-678026b0cf6a
BDRS survey id = 280 + 277 to BioCollect survey id = 6603e2c0-dab6-4eb3-bb08-f631ce0bddf8
BDRS survey id = 260 to BioCollect survey id = b91e234f-f1cb-4040-8a3b-d4b8213f3266
BDRS survey id = 262 to BioCollect survey id = 2318f116-ff07-4609-8d04-e978b640d0e9
BDRS survey id = 261 + 276 to BioCollect survey id = c4d99bf5-9653-43d9-923a-0780da3e47f6
BDRS survey id = 263 to BioCollect survey id = 57493b3e-18ea-466a-a520-4dea28b4ea5e
BDRS survey id = 275 to BioCollect survey id = 36933aca-f344-4a03-947c-b9a128007e6d
BDRS survey id = 279 to BioCollect survey id = 4948b263-ebad-4a98-883e-d0e8e2646d17

Need to create forms in BioCollect to hold the data
Can't switch over until we can properly support complex expression calculations in BioCollect

**Comment by matilda2812** [comment]
@pbrenton can I close this?
