### ISSUE TITLE
Data migrations BDRS --> BioCollect - NSW WaterWatch

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#967]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 37
(http://root.ala.org.au/bdrs-core/nswww/home.htm)

BDRS survey id = 217 to BioCollect survey id = 
BDRS survey id = 219 to BioCollect survey id = 
BDRS survey id = 221 to BioCollect survey id = 
BDRS survey id = 225 to BioCollect survey id = 
BDRS survey id = 223 to BioCollect survey id = 
BDRS survey id = 227 to BioCollect survey id = 
BDRS survey id = 228 to BioCollect survey id = 
BDRS survey id = 230 to BioCollect survey id = 
BDRS survey id = 229 to BioCollect survey id = 
BDRS survey id = 233 to BioCollect survey id = 
BDRS survey id = 232 to BioCollect survey id = 
BDRS survey id = 231 to BioCollect survey id = 
BDRS survey id = 218 to BioCollect survey id = 
BDRS survey id = 220 to BioCollect survey id = 
BDRS survey id = 222 to BioCollect survey id = 
BDRS survey id = 226 to BioCollect survey id = 
BDRS survey id = 224 to BioCollect survey id = 
BDRS survey id = 235 to BioCollect survey id = 
BDRS survey id = 241 to BioCollect survey id = 
BDRS survey id = 237 to BioCollect survey id = 
BDRS survey id = 236 to BioCollect survey id = 
BDRS survey id = 238 to BioCollect survey id = 
BDRS survey id = 239 to BioCollect survey id = 
BDRS survey id = 240 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data
Can't switch over until we can properly support complex expression calculations in BioCollect

**Comment by matilda2812** [comment]
done
