### ISSUE TITLE
Data migrations BDRS --> BioCollect - Melbourne Water Healthy Waterways

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#968]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 72
(http://root.ala.org.au/bdrs-core/portal/72/home.htm)

BDRS survey id = 341 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data
Can't switch over until we can properly support complex expression calculations in BioCollect

**Comment by matilda2812** [comment]
done
