### ISSUE TITLE
 Data migrations BDRS --> BioCollect - OEH Warrumbungle Snap

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#969]
Migrate record level data (including record images and record submitter names) from BDRS portal id = 62
(http://root.ala.org.au/bdrs-core/portal/62/home.htm)

BDRS survey id = 314 to BioCollect survey id = 

Need to create forms in BioCollect to hold the data

**Comment by matilda2812** [comment]
done
