### ISSUE TITLE
View records shows all records, not these records related to the particular survey

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocollect#972]
For example, a project has multiple surveys, and records for different surveys.  Not matter which view record button clicks, it will show all records

![screen shot 2017-11-17 at 1 41 09 pm](https://user-images.githubusercontent.com/31238531/32926741-07b2a45e-cb9d-11e7-9bf4-66212b09f3f7.png)

**Comment by matilda2812** [comment]
Closing as issue duplicated
