### ISSUE TITLE
Exception viewing project with bad site data

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#973]
Clicking on https://biocollect.ala.org.au/ala/project/index/283fe919-6511-441e-9d98-174b0b41a71f was throwing an exception.
It appeared that the project site was missing somehow, the error was:
 Error executing tag <r:script>: Cannot get property 'extent' on null object
        at gsp_biocollect_projectcsProjectTemplate_gsp$_run_closure2.doCall(gsp_biocollect_projectcsProjectTemplate_gsp.groovy:279)

Editing the project, the site was there (it was South Australia).  Resaving the project information fixed the project homepage.

The audit log is timing out at the moment so it's hard to see what state the data was in.

**Comment by javier-molina** [comment]
Our customers from IBSA are facing this on a regular basis, here below are the three projects reported this week

https://biocollect.ala.org.au/ibsa/project/index/00c15993-0425-47f1-9323-f9d2803e2b83
https://biocollect.ala.org.au/ibsa/project/index/4611c5fb-f04c-48c4-b5a8-99c481110a9d
https://biocollect.ala.org.au/ibsa/project/index/3e8142e6-56a3-4d1c-bc5c-3f0fda90485f

![Capture3](https://user-images.githubusercontent.com/8326394/59470571-664db100-8e7b-11e9-86d2-0a33bc4bf0ce.PNG)
![Capture2](https://user-images.githubusercontent.com/8326394/59470572-66e64780-8e7b-11e9-8956-a12f99cf697e.PNG)
![Capture1](https://user-images.githubusercontent.com/8326394/59470573-66e64780-8e7b-11e9-8b6d-54279b55e142.PNG)
![Capture](https://user-images.githubusercontent.com/8326394/59470575-66e64780-8e7b-11e9-8765-2ff638871aab.PNG)

I have used the workaround Chris suggest about editing and saving but I don't want to use that yet until investigated.

Here below are the steps to reproduce that the I asked IBSA customers to document:
----------------------------------------------------------------------------
*Steps to reproduce*

1. Click New Survey
2. Fill in Mandatory fields
3. Choose no for Do you want to record project data for this site
4. Draw a polygon in Define the spatial extent of project area
5. Do not select a base layer
6. Click on Save changes
7. Project (Survey) is created and landing page displayed
8. Click attach document in Project Resources
9. Enter title
10. Document type information
11. Click make this document public on the project “resources” tab
12. Attach file
13. Click save

*Expected*
Document is uploaded to project resources.
 
*Actual*
An error with the message “I can’t access property extent on null object“ is displayed every time the project is accessed from the Project Finder.
 
Occasionally the error will occur at step 7, but majority of the time it is when I try to upload the attachments.
 
-------------------------------------------------------------------------------

I was not able to reproduce that in test after three attempts.

**Comment by sat01a** [comment]
This issue should mostly be addressed as part of 4.8.4 release. Given that its hard to reproduce. We will keep an eye on this.
