### ISSUE TITLE
Project Data  > permissions

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#98]
Only ALA Admin, Project Admin, or the Record/Activity owner, should be able to edit or delete items from the list.

This covers items 15 (partially), 27, and 28.

**Comment by sat01a** [comment]
Dependent on ecodata PR - https://github.com/AtlasOfLivingAustralia/ecodata/pull/134

**Comment by sat01a** [comment]
Biocollect changes  > https://github.com/AtlasOfLivingAustralia/biocollect/pull/167/files
