### ISSUE TITLE
Production Release 4.0 Regression Testing

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#987]
**Show stopper:**
** Looks like issues are related to single sightings form **

> 1. Activity edit fails - Doesn't load the data (https://biocollect-test.ala.org.au/ala/bioActivity/edit/382a1a7e-6400-43dd-aae1-d82268273eec?returnTo=%2Fala%2Fproject%2Findex%2F6f799353-5160-4fe6-93da-7095d4e792b4) 
--FIXED

> 2. Map tab not showing activity/record. (Example : Project > Data > Maps ) 
--FIXED

> 3. Activity > Can't drop a pin on the MAP (Inconsistent behaviour) -- CANNOT REPRODUCED

> 4. Activity load fails (Example: https://biocollect-test.ala.org.au/ala/bioActivity/index/382a1a7e-6400-43dd-aae1-d82268273eec?returnTo=%2Fala%2Fproject%2Findex%2F6f799353-5160-4fe6-93da-7095d4e792b4) 

--FIXED

5. Replacing polygon with a drop a pin doesn't update the map. After few tries map popup appears.
(https://biocollect-test.ala.org.au/ala/bioActivity/edit/cdaf77e9-daac-4471-a642-261363b564bd?returnTo=%2Fala%2Fproject%2Findex%2F6f799353-5160-4fe6-93da-7095d4e792b4)
(Another example: https://biocollect-test.ala.org.au/ala/bioActivity/create/d2342592-4720-435d-9c01-6d0274da4c8d)
-- CANNOT REPRODUCED
-- Suspect choosing a circle instead of point. This mistake happened on me many times

**Minor:**

1. Site creation seems to take more than 2 to 3 sec. One factor could be the load on spatial portal since it is generating facets by intersecting with it.
   -- Site creation has a few AJax calls:  1: create site.  2: refresh sites list, 3: add private site in if need. The 3rd step may cause the delay
   --  Fixed the private site creation, test on it

> 2. Project creation fails, when map line feature is selected. --FIXED

3. Record creation, map not zooming to project area when predefined layer is selected
4. All records > List > Image view not expanding.
5. Multiple funding addition is not working
6. All records page > facet configuration > presence / absence > not working

**Comment by tanmoy1048** [comment]
In Android device,  I found an issue while putting a pin on the map. It works, however it shows an error message.
![screenshot_1513730377](https://user-images.githubusercontent.com/11676155/34185649-acc6cd34-e57a-11e7-9f62-9e1ffdbfe5c4.png)

**Comment by matilda2812** [comment]
@sat01a can this be closed?
