### ISSUE TITLE
Burnt: boolean field is not rendered properly 

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocollect#999]
https://biocollect.ala.org.au/ala/bioActivity/index/59c2fe85-02e5-40ad-94b4-b55ea2f9091d

In Wolli project, there is boolean field: burnt.  It is not display properly and the checkbox is not checked, if it set true.  
DB has the correct value

**Comment by matilda2812** [comment]
No longer relevant.
